PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX persoon_loket: <http://data.vlaanderen.be/ns/persoon#>

# Map from http persoon to https persoon namespace

CONSTRUCT {
  ?s persoon:isLidVan ?o .
} WHERE {
  ?s persoon_loket:isLidVan ?o .
}
