PREFIX foaf: <http://xmlns.com/foaf/0.1/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s a <http://www.w3.org/ns/person#Person>;
      ?p ?o.
  }
} WHERE {

  VALUES ?p {
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
    <http://mu.semte.ch/vocabularies/core/uuid>
    foaf:givenName
    foaf:familyName
    <http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam>
  }

  ?functionaris a <http://data.lblod.info/vocabularies/leidinggevenden/Functionaris>;
    <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?s.

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s a <http://www.w3.org/ns/person#Person>;
      ?p ?o.
  }
}