PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX mu:   <http://mu.semte.ch/vocabularies/core/>
PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?vlaamsGewest a prov:Location ;
                  mu:uuid ?uuid ;
                  rdfs:label "Vlaams Gewest" ;
                  ext:werkingsgebiedNiveau "Gewest" ;
                  skos:exactMatch <http://vocab.belgif.be/auth/refnis2025/2000> ,
                                  <http://vocab.belgif.be/auth/refnis2019/2000> .
  }
} WHERE {
  BIND(SHA256(CONCAT("Werkingsgebied for Vlaams Gewest")) AS ?uuid)
  BIND(IRI(CONCAT("http://data.lblod.info/id/werkingsgebieden/", STR(?uuid))) AS ?vlaamsGewest)
  FILTER NOT EXISTS {
    GRAPH <http://mu.semte.ch/graphs/public> {
      ?existing ext:werkingsgebiedNiveau "Gewest" ;
                rdfs:label "Vlaams Gewest" .
    }
  }
}
