PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  VALUES ?p {
    persoon:registratie
    persoon:heeftNationaliteit
    persoon:heeftGeboorte
    persoon:datum
    persoon:geslacht
  }

  ?s ?p ?o .
}
