
PREFIX  ext:  <http://mu.semte.ch/vocabularies/ext/>
 PREFIX  besluit: <http://data.vlaanderen.be/ns/besluit#>
 PREFIX  mu:   <http://mu.semte.ch/vocabularies/core/>
 PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
 PREFIX  dcterms: <http://purl.org/dc/terms/>
 PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
 
 INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organizations/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> {
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> mu:uuid "564e329c-ebc2-44ba-a2e4-82fd555a9361" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:familyName "AgbApbLezer" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:account <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> mu:uuid "f9ca539e-4129-41d8-9f26-3ccb75b7996a" .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> ext:sessionRole "ABBOrganisatiePortaalAgbApb-lezer" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> mu:uuid "b193b6ff-e92c-4f88-afef-1a521358ca4d" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:familyName "AgbApbEditeerder" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:account <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> mu:uuid "83df465f-b7de-49f5-b95a-50c5f31015a2" .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> ext:sessionRole "ABBOrganisatiePortaalAgbApb-editeerder" .
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
     <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> besluit:Bestuurseenheid .
     <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> mu:uuid "141d9d6b-54af-4d17-b313-8d1c30bc3f5b" .
     <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> skos:prefLabel "Agentschap Binnenlands Bestuur" .
     <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> dcterms:identifier "OVO001835" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> mu:uuid "564e329c-ebc2-44ba-a2e4-82fd555a9361" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:familyName "AgbApbLezer" .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/564e329c-ebc2-44ba-a2e4-82fd555a9361> foaf:account <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> mu:uuid "f9ca539e-4129-41d8-9f26-3ccb75b7996a" .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/f9ca539e-4129-41d8-9f26-3ccb75b7996a> ext:sessionRole "ABBOrganisatiePortaalAgbApb-lezer" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> mu:uuid "b193b6ff-e92c-4f88-afef-1a521358ca4d" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:familyName "AgbApbEditeerder" .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/b193b6ff-e92c-4f88-afef-1a521358ca4d> foaf:account <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> mu:uuid "83df465f-b7de-49f5-b95a-50c5f31015a2" .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/83df465f-b7de-49f5-b95a-50c5f31015a2> ext:sessionRole "ABBOrganisatiePortaalAgbApb-editeerder" .
     }


 }
