PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> mu:uuid "73018124-9b28-42b0-817f-7e08a90cfe9f" ;
      skos:prefLabel """Pajottegem""" ;
      regorg:legalName """Pajottegem""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053708> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> adms:identifier <http://data.lblod.info/id/identificatoren/f18fe9b0-f9e7-4bb7-ac7d-b8590570b633> .
    <http://data.lblod.info/id/identificatoren/f18fe9b0-f9e7-4bb7-ac7d-b8590570b633> a adms:Identifier ;
      mu:uuid """f18fe9b0-f9e7-4bb7-ac7d-b8590570b633""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/289880d3-2de5-46a2-a2e6-81a67f216773> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/289880d3-2de5-46a2-a2e6-81a67f216773> a generiek:GestructureerdeIdentificator ;
      mu:uuid """289880d3-2de5-46a2-a2e6-81a67f216773""" ;
      generiek:lokaleIdentificator """1010784738""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> adms:identifier <http://data.lblod.info/id/identificatoren/05e0a7b3-1a34-47e5-b1f4-1ccf46d03758> .
    <http://data.lblod.info/id/identificatoren/05e0a7b3-1a34-47e5-b1f4-1ccf46d03758> a adms:Identifier ;
      mu:uuid """05e0a7b3-1a34-47e5-b1f4-1ccf46d03758""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/3a53414e-ba06-4197-a4ea-f9d301160bc9> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/3a53414e-ba06-4197-a4ea-f9d301160bc9> a generiek:GestructureerdeIdentificator ;
      mu:uuid """3a53414e-ba06-4197-a4ea-f9d301160bc9""" ;
      generiek:lokaleIdentificator """OVO053708""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/identificatoren/f26a54be-f91d-42d2-9815-a1b7253e353c> a adms:Identifier ;
      mu:uuid "f26a54be-f91d-42d2-9815-a1b7253e353c" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/fd1bdea2-5c0d-44d5-ac62-a385a120b775> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/fd1bdea2-5c0d-44d5-ac62-a385a120b775> a generiek:GestructureerdeIdentificator ;
      mu:uuid "fd1bdea2-5c0d-44d5-ac62-a385a120b775" .
  }
}
#
# Governing bodies
#
;
## Voorzitter van het Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/9f421c11-72c8-4b33-a6c0-b074ba843441> a besluit:Bestuursorgaan ;
      mu:uuid """9f421c11-72c8-4b33-a6c0-b074ba843441""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/bec6982c-827d-4e05-b04c-46e275d3ca0f> a besluit:Bestuursorgaan ;
      mu:uuid """bec6982c-827d-4e05-b04c-46e275d3ca0f""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/9f421c11-72c8-4b33-a6c0-b074ba843441> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Raad voor Maatschappelijk Welzijn
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/7ff76277-5ee6-4ec9-bdd5-40508cc10587> a besluit:Bestuursorgaan ;
      mu:uuid """7ff76277-5ee6-4ec9-bdd5-40508cc10587""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/c74ce5d9-5fa1-40cd-9c9a-44e593d49edc> a besluit:Bestuursorgaan ;
      mu:uuid """c74ce5d9-5fa1-40cd-9c9a-44e593d49edc""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/7ff76277-5ee6-4ec9-bdd5-40508cc10587> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Vast Bureau
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/47f9d813-8838-4e27-ad10-286e5a57c768> a besluit:Bestuursorgaan ;
      mu:uuid """47f9d813-8838-4e27-ad10-286e5a57c768""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/56cc5d11-e8b8-40d5-8fbf-635615a8e76e> a besluit:Bestuursorgaan ;
      mu:uuid """56cc5d11-e8b8-40d5-8fbf-635615a8e76e""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/47f9d813-8838-4e27-ad10-286e5a57c768> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/a212b975-3bd4-42a7-aeb9-4e0ec84f7236> a besluit:Bestuursorgaan ;
      mu:uuid """a212b975-3bd4-42a7-aeb9-4e0ec84f7236""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/f84b8bb7-a359-415f-aadf-ef50a504870f> a besluit:Bestuursorgaan ;
      mu:uuid """f84b8bb7-a359-415f-aadf-ef50a504870f""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/a212b975-3bd4-42a7-aeb9-4e0ec84f7236> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/73018124-9b28-42b0-817f-7e08a90cfe9f> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Vlaams-Brabant""" .
  }
}
