PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> mu:uuid "3190ca10-104c-481d-92a5-42a9bb033a65" ;
      skos:prefLabel """Merelbeke-Melle""" ;
      regorg:legalName """Merelbeke-Melle""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053387> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> adms:identifier <http://data.lblod.info/id/identificatoren/e494623a-29be-4478-83f4-01a216a1ff8f> .
    <http://data.lblod.info/id/identificatoren/e494623a-29be-4478-83f4-01a216a1ff8f> a adms:Identifier ;
      mu:uuid """e494623a-29be-4478-83f4-01a216a1ff8f""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/d4b3548e-256c-4667-a600-20e9702cf0f8> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/d4b3548e-256c-4667-a600-20e9702cf0f8> a generiek:GestructureerdeIdentificator ;
      mu:uuid """d4b3548e-256c-4667-a600-20e9702cf0f8""" ;
      generiek:lokaleIdentificator """1010775830""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> adms:identifier <http://data.lblod.info/id/identificatoren/7a82ba6c-c571-4672-a893-224bbcabeda9> .
    <http://data.lblod.info/id/identificatoren/7a82ba6c-c571-4672-a893-224bbcabeda9> a adms:Identifier ;
      mu:uuid """7a82ba6c-c571-4672-a893-224bbcabeda9""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/c9d1ccd6-a9cb-431e-9919-1120e157549b> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/c9d1ccd6-a9cb-431e-9919-1120e157549b> a generiek:GestructureerdeIdentificator ;
      mu:uuid """c9d1ccd6-a9cb-431e-9919-1120e157549b""" ;
      generiek:lokaleIdentificator """OVO053387""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/identificatoren/cbdebc3e-463a-4365-b44f-5c1cf03e46cc> a adms:Identifier ;
      mu:uuid "cbdebc3e-463a-4365-b44f-5c1cf03e46cc" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/a16c1585-cd67-422b-a7a9-2ff8b04a633e> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/a16c1585-cd67-422b-a7a9-2ff8b04a633e> a generiek:GestructureerdeIdentificator ;
      mu:uuid "a16c1585-cd67-422b-a7a9-2ff8b04a633e" .
  }
}
;
# scope
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/dcfebd37-162e-486f-9598-1b292a67e3e9> .
    <http://data.lblod.info/id/werkingsgebieden/dcfebd37-162e-486f-9598-1b292a67e3e9> a prov:Location ;
      mu:uuid """dcfebd37-162e-486f-9598-1b292a67e3e9""" ;
      rdfs:label """Merelbeke-Melle""" ;
      ext:werkingsgebiedNiveau "Gemeente" .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/werkingsgebieden/dcfebd37-162e-486f-9598-1b292a67e3e9> geo:sfWithin ?locatedWithin .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?locatedWithin a <http://www.w3.org/ns/prov#Location> ;
      rdfs:label ?label .
    FILTER (STR(?label) = """Regio Gent""")
  }
}
#
# Governing bodies
#
;
## Burgemeester
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/13d87f34-c6d5-431f-a566-273efdc9c7f4> a besluit:Bestuursorgaan ;
      mu:uuid """13d87f34-c6d5-431f-a566-273efdc9c7f4""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/31775fb5-59b0-464c-bb01-53d44309e5da> a besluit:Bestuursorgaan ;
      mu:uuid """31775fb5-59b0-464c-bb01-53d44309e5da""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/13d87f34-c6d5-431f-a566-273efdc9c7f4> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Gemeenteraad
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/b4fca2a8-4534-46e1-8f7b-1ba949969ec0> a besluit:Bestuursorgaan ;
      mu:uuid """b4fca2a8-4534-46e1-8f7b-1ba949969ec0""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/efc20a9c-f5bd-48ee-af68-3bb679564a0c> a besluit:Bestuursorgaan ;
      mu:uuid """efc20a9c-f5bd-48ee-af68-3bb679564a0c""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/b4fca2a8-4534-46e1-8f7b-1ba949969ec0> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## College van Burgemeester en Schepenen
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/35d1a73d-d45a-4c84-b98c-bd3fa97a7b8b> a besluit:Bestuursorgaan ;
      mu:uuid """35d1a73d-d45a-4c84-b98c-bd3fa97a7b8b""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/c8d5ae0a-4857-48e4-9bbd-d68bb738ba89> a besluit:Bestuursorgaan ;
      mu:uuid """c8d5ae0a-4857-48e4-9bbd-d68bb738ba89""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/35d1a73d-d45a-4c84-b98c-bd3fa97a7b8b> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/94dc4fee-3398-46d4-9c5d-da744ac2ec65> a besluit:Bestuursorgaan ;
      mu:uuid """94dc4fee-3398-46d4-9c5d-da744ac2ec65""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/e16b32cf-78d6-4690-b76b-1590044e5d09> a besluit:Bestuursorgaan ;
      mu:uuid """e16b32cf-78d6-4690-b76b-1590044e5d09""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/94dc4fee-3398-46d4-9c5d-da744ac2ec65> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Adjunct-algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/8a2edd81-6b5f-40dc-bc78-188b07695972> a besluit:Bestuursorgaan ;
      mu:uuid """8a2edd81-6b5f-40dc-bc78-188b07695972""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/4ec1bb3b-20f3-4b45-946f-f8ce6f6d48c4> a besluit:Bestuursorgaan ;
      mu:uuid """4ec1bb3b-20f3-4b45-946f-f8ce6f6d48c4""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/8a2edd81-6b5f-40dc-bc78-188b07695972> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/2c0f1995-7664-44d5-b175-112f51d0b663> a besluit:Bestuursorgaan ;
      mu:uuid """2c0f1995-7664-44d5-b175-112f51d0b663""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/5e48f15a-501f-4811-96e5-e2a2be6102fd> a besluit:Bestuursorgaan ;
      mu:uuid """5e48f15a-501f-4811-96e5-e2a2be6102fd""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/2c0f1995-7664-44d5-b175-112f51d0b663> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Adjunct-financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/ef9163c2-1b7e-4001-a8aa-6d08466c230c> a besluit:Bestuursorgaan ;
      mu:uuid """ef9163c2-1b7e-4001-a8aa-6d08466c230c""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/b95eca68-9b0e-4c21-8426-26defe00579e> a besluit:Bestuursorgaan ;
      mu:uuid """b95eca68-9b0e-4c21-8426-26defe00579e""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/ef9163c2-1b7e-4001-a8aa-6d08466c230c> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/3190ca10-104c-481d-92a5-42a9bb033a65> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
