PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> mu:uuid "1379f3ac-01d0-40e1-b31a-0c47be0320b0" ;
      skos:prefLabel """Pajottegem""" ;
      regorg:legalName """Pajottegem""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053708> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> adms:identifier <http://data.lblod.info/id/identificatoren/07b21e78-6759-4cc0-80ab-53aa0213d051> .
    <http://data.lblod.info/id/identificatoren/07b21e78-6759-4cc0-80ab-53aa0213d051> a adms:Identifier ;
      mu:uuid """07b21e78-6759-4cc0-80ab-53aa0213d051""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/c563a143-0daf-4cba-ad87-d50fe282f56b> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/c563a143-0daf-4cba-ad87-d50fe282f56b> a generiek:GestructureerdeIdentificator ;
      mu:uuid """c563a143-0daf-4cba-ad87-d50fe282f56b""" ;
      generiek:lokaleIdentificator """1010784738""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> adms:identifier <http://data.lblod.info/id/identificatoren/4fef8ca5-ace0-42ae-97a1-1b90f91eb266> .
    <http://data.lblod.info/id/identificatoren/4fef8ca5-ace0-42ae-97a1-1b90f91eb266> a adms:Identifier ;
      mu:uuid """4fef8ca5-ace0-42ae-97a1-1b90f91eb266""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/f78fdcbc-4c48-4723-bd02-67dda5c53b3a> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/f78fdcbc-4c48-4723-bd02-67dda5c53b3a> a generiek:GestructureerdeIdentificator ;
      mu:uuid """f78fdcbc-4c48-4723-bd02-67dda5c53b3a""" ;
      generiek:lokaleIdentificator """OVO053708""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> adms:identifier <http://data.lblod.info/id/identificatoren/fccba08b-44af-451c-a462-2139784f757b> .
    <http://data.lblod.info/id/identificatoren/fccba08b-44af-451c-a462-2139784f757b> a adms:Identifier ;
      mu:uuid "fccba08b-44af-451c-a462-2139784f757b" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/923ff3e2-12d8-46a9-99b8-3297c1363624> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/923ff3e2-12d8-46a9-99b8-3297c1363624> a generiek:GestructureerdeIdentificator ;
      mu:uuid "923ff3e2-12d8-46a9-99b8-3297c1363624" .
  }
}
#
# Governing bodies
#
;
## Voorzitter van het Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/f61853c2-ea02-451b-8471-3c0a46dff25e> a besluit:Bestuursorgaan ;
      mu:uuid """f61853c2-ea02-451b-8471-3c0a46dff25e""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/f832ac00-f2aa-4fb3-95aa-227e2f9f3b18> a besluit:Bestuursorgaan ;
      mu:uuid """f832ac00-f2aa-4fb3-95aa-227e2f9f3b18""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/f61853c2-ea02-451b-8471-3c0a46dff25e> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Raad voor Maatschappelijk Welzijn
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/f8852bb9-c4b2-4fcd-ac12-9c225ee31946> a besluit:Bestuursorgaan ;
      mu:uuid """f8852bb9-c4b2-4fcd-ac12-9c225ee31946""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/5c2e04ed-7eff-471b-8ab8-9ab6b510576f> a besluit:Bestuursorgaan ;
      mu:uuid """5c2e04ed-7eff-471b-8ab8-9ab6b510576f""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/f8852bb9-c4b2-4fcd-ac12-9c225ee31946> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Vast Bureau
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/9f2b4748-afb1-4e47-8ebb-ec10272a5dd4> a besluit:Bestuursorgaan ;
      mu:uuid """9f2b4748-afb1-4e47-8ebb-ec10272a5dd4""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/a252d287-af74-460c-ab0e-98b15f4b1d20> a besluit:Bestuursorgaan ;
      mu:uuid """a252d287-af74-460c-ab0e-98b15f4b1d20""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/9f2b4748-afb1-4e47-8ebb-ec10272a5dd4> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
;
## Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/cbdc0bd8-a4fb-48d2-8bbe-df3beb3a2053> a besluit:Bestuursorgaan ;
      mu:uuid """cbdc0bd8-a4fb-48d2-8bbe-df3beb3a2053""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/be43239f-53a2-4058-ae60-c2d6086969fe> a besluit:Bestuursorgaan ;
      mu:uuid """be43239f-53a2-4058-ae60-c2d6086969fe""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/cbdc0bd8-a4fb-48d2-8bbe-df3beb3a2053> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Pajottegem") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/1379f3ac-01d0-40e1-b31a-0c47be0320b0> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Vlaams-Brabant""" .
  }
}
