PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> mu:uuid "874e2504-94f2-4e46-adca-a142d0c3bd4a" ;
      skos:prefLabel """Beveren-Kruibeke-Zwijndrecht""" ;
      regorg:legalName """Beveren-Kruibeke-Zwijndrecht""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053710> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> adms:identifier <http://data.lblod.info/id/identificatoren/fff686b4-364c-4cfe-98c1-73b4df54b685> .
    <http://data.lblod.info/id/identificatoren/fff686b4-364c-4cfe-98c1-73b4df54b685> a adms:Identifier ;
      mu:uuid """fff686b4-364c-4cfe-98c1-73b4df54b685""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/bacd57ef-f3e2-4318-9c8a-2a61225ef4e7> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/bacd57ef-f3e2-4318-9c8a-2a61225ef4e7> a generiek:GestructureerdeIdentificator ;
      mu:uuid """bacd57ef-f3e2-4318-9c8a-2a61225ef4e7""" ;
      generiek:lokaleIdentificator """1010783748""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> adms:identifier <http://data.lblod.info/id/identificatoren/4e5ca357-f617-4c6c-a395-7691cdf7bd8a> .
    <http://data.lblod.info/id/identificatoren/4e5ca357-f617-4c6c-a395-7691cdf7bd8a> a adms:Identifier ;
      mu:uuid """4e5ca357-f617-4c6c-a395-7691cdf7bd8a""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/8103a7a1-fc6d-4514-8b37-445140331096> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/8103a7a1-fc6d-4514-8b37-445140331096> a generiek:GestructureerdeIdentificator ;
      mu:uuid """8103a7a1-fc6d-4514-8b37-445140331096""" ;
      generiek:lokaleIdentificator """OVO053710""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> adms:identifier <http://data.lblod.info/id/identificatoren/a4641567-9532-4c84-b4be-568babf14fca> .
    <http://data.lblod.info/id/identificatoren/a4641567-9532-4c84-b4be-568babf14fca> a adms:Identifier ;
      mu:uuid "a4641567-9532-4c84-b4be-568babf14fca" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/cf7c85fc-c697-4b87-8d37-4ea9543abe49> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/cf7c85fc-c697-4b87-8d37-4ea9543abe49> a generiek:GestructureerdeIdentificator ;
      mu:uuid "cf7c85fc-c697-4b87-8d37-4ea9543abe49" .
  }
}
#
# Governing bodies
#
;
## Voorzitter van het Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/80b24985-71e3-46df-9210-956d015b435e> a besluit:Bestuursorgaan ;
      mu:uuid """80b24985-71e3-46df-9210-956d015b435e""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/80282fc7-1366-498b-b4cc-4f09cf838555> a besluit:Bestuursorgaan ;
      mu:uuid """80282fc7-1366-498b-b4cc-4f09cf838555""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/80b24985-71e3-46df-9210-956d015b435e> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Raad voor Maatschappelijk Welzijn
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/8e379191-7839-44b0-bd95-38f183283cb5> a besluit:Bestuursorgaan ;
      mu:uuid """8e379191-7839-44b0-bd95-38f183283cb5""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/871bc9e7-be83-4bff-b570-765888d841bf> a besluit:Bestuursorgaan ;
      mu:uuid """871bc9e7-be83-4bff-b570-765888d841bf""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/8e379191-7839-44b0-bd95-38f183283cb5> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Vast Bureau
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/01562624-5636-42a4-ad7f-f9d5438222bb> a besluit:Bestuursorgaan ;
      mu:uuid """01562624-5636-42a4-ad7f-f9d5438222bb""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/87844365-e1e3-4c2f-8c8f-50b809e4b9f0> a besluit:Bestuursorgaan ;
      mu:uuid """87844365-e1e3-4c2f-8c8f-50b809e4b9f0""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/01562624-5636-42a4-ad7f-f9d5438222bb> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/3810ab8d-72da-4010-8bae-1b06b0643648> a besluit:Bestuursorgaan ;
      mu:uuid """3810ab8d-72da-4010-8bae-1b06b0643648""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/8e6864c5-f2dd-41c6-9af0-0bc6ee2e6922> a besluit:Bestuursorgaan ;
      mu:uuid """8e6864c5-f2dd-41c6-9af0-0bc6ee2e6922""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/3810ab8d-72da-4010-8bae-1b06b0643648> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/874e2504-94f2-4e46-adca-a142d0c3bd4a> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
