PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> mu:uuid "f488e898-dfc6-4b23-babc-343408b2c5b5" ;
      skos:prefLabel """Merelbeke-Melle""" ;
      regorg:legalName """Merelbeke-Melle""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053711> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> adms:identifier <http://data.lblod.info/id/identificatoren/2732aa07-aa78-4f38-aa0f-222f7bf2262c> .
    <http://data.lblod.info/id/identificatoren/2732aa07-aa78-4f38-aa0f-222f7bf2262c> a adms:Identifier ;
      mu:uuid """2732aa07-aa78-4f38-aa0f-222f7bf2262c""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/2867a412-2b13-4d89-8afd-a52b2b17a86b> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/2867a412-2b13-4d89-8afd-a52b2b17a86b> a generiek:GestructureerdeIdentificator ;
      mu:uuid """2867a412-2b13-4d89-8afd-a52b2b17a86b""" ;
      generiek:lokaleIdentificator """1010776127""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> adms:identifier <http://data.lblod.info/id/identificatoren/85778865-e416-4f6e-a1a4-e7feef79162a> .
    <http://data.lblod.info/id/identificatoren/85778865-e416-4f6e-a1a4-e7feef79162a> a adms:Identifier ;
      mu:uuid """85778865-e416-4f6e-a1a4-e7feef79162a""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/062c2f45-4cf0-4c94-8233-bbb608b10945> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/062c2f45-4cf0-4c94-8233-bbb608b10945> a generiek:GestructureerdeIdentificator ;
      mu:uuid """062c2f45-4cf0-4c94-8233-bbb608b10945""" ;
      generiek:lokaleIdentificator """OVO053711""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> adms:identifier <http://data.lblod.info/id/identificatoren/0336029e-3fcd-4792-ab5a-0824d7e651b3> .
    <http://data.lblod.info/id/identificatoren/0336029e-3fcd-4792-ab5a-0824d7e651b3> a adms:Identifier ;
      mu:uuid "0336029e-3fcd-4792-ab5a-0824d7e651b3" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/d9ba739a-9435-4029-8495-ba34f7060609> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/d9ba739a-9435-4029-8495-ba34f7060609> a generiek:GestructureerdeIdentificator ;
      mu:uuid "d9ba739a-9435-4029-8495-ba34f7060609" .
  }
}
#
# Governing bodies
#
;
## Voorzitter van het Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/2387d0ed-4347-4b6e-a945-3a1f1c966f83> a besluit:Bestuursorgaan ;
      mu:uuid """2387d0ed-4347-4b6e-a945-3a1f1c966f83""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/a4d25ad2-45ee-4b7f-a1fc-55cede04b1a9> a besluit:Bestuursorgaan ;
      mu:uuid """a4d25ad2-45ee-4b7f-a1fc-55cede04b1a9""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/2387d0ed-4347-4b6e-a945-3a1f1c966f83> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Raad voor Maatschappelijk Welzijn
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/54ca6105-7f8c-40f2-b07e-c83a32886f08> a besluit:Bestuursorgaan ;
      mu:uuid """54ca6105-7f8c-40f2-b07e-c83a32886f08""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/868dd90d-4342-46f3-9e8a-f9b053c2dce0> a besluit:Bestuursorgaan ;
      mu:uuid """868dd90d-4342-46f3-9e8a-f9b053c2dce0""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/54ca6105-7f8c-40f2-b07e-c83a32886f08> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Vast Bureau
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/6fd5d904-a9a0-416c-879b-152f7d6f232f> a besluit:Bestuursorgaan ;
      mu:uuid """6fd5d904-a9a0-416c-879b-152f7d6f232f""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/83c6a681-1bb5-4604-9e2f-8be38cd39fcc> a besluit:Bestuursorgaan ;
      mu:uuid """83c6a681-1bb5-4604-9e2f-8be38cd39fcc""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/6fd5d904-a9a0-416c-879b-152f7d6f232f> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
;
## Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/25812229-a8da-4df6-81b7-99c9f38faf59> a besluit:Bestuursorgaan ;
      mu:uuid """25812229-a8da-4df6-81b7-99c9f38faf59""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/0eb8bc3f-c420-4228-b6a6-2713c4422d4e> a besluit:Bestuursorgaan ;
      mu:uuid """0eb8bc3f-c420-4228-b6a6-2713c4422d4e""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/25812229-a8da-4df6-81b7-99c9f38faf59> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Merelbeke-Melle") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/f488e898-dfc6-4b23-babc-343408b2c5b5> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
