PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> mu:uuid "6f4471e0-c155-4bf1-8558-e77c3cf75638" ;
      skos:prefLabel """Nazareth-De Pinte""" ;
      regorg:legalName """Nazareth-De Pinte""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002> .

    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053712> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> adms:identifier <http://data.lblod.info/id/identificatoren/2c1cb3ad-b930-4898-af69-bfb2b6291a4a> .
    <http://data.lblod.info/id/identificatoren/2c1cb3ad-b930-4898-af69-bfb2b6291a4a> a adms:Identifier ;
      mu:uuid """2c1cb3ad-b930-4898-af69-bfb2b6291a4a""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/a68ce2bc-aa30-4824-a154-dd427e7f077a> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/a68ce2bc-aa30-4824-a154-dd427e7f077a> a generiek:GestructureerdeIdentificator ;
      mu:uuid """a68ce2bc-aa30-4824-a154-dd427e7f077a""" ;
      generiek:lokaleIdentificator """1010782461""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> adms:identifier <http://data.lblod.info/id/identificatoren/59e56381-1ba0-4f1c-8775-33d1c280ef28> .
    <http://data.lblod.info/id/identificatoren/59e56381-1ba0-4f1c-8775-33d1c280ef28> a adms:Identifier ;
      mu:uuid """59e56381-1ba0-4f1c-8775-33d1c280ef28""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/ead20f21-c482-4290-921a-114b8596790b> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/ead20f21-c482-4290-921a-114b8596790b> a generiek:GestructureerdeIdentificator ;
      mu:uuid """ead20f21-c482-4290-921a-114b8596790b""" ;
      generiek:lokaleIdentificator """OVO053712""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> adms:identifier <http://data.lblod.info/id/identificatoren/b9db6699-1eab-4581-b8d0-c6df515b0dd0> .
    <http://data.lblod.info/id/identificatoren/b9db6699-1eab-4581-b8d0-c6df515b0dd0> a adms:Identifier ;
      mu:uuid "b9db6699-1eab-4581-b8d0-c6df515b0dd0" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/1375c2ac-bfb1-41f9-acde-68bde8ad505f> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/1375c2ac-bfb1-41f9-acde-68bde8ad505f> a generiek:GestructureerdeIdentificator ;
      mu:uuid "1375c2ac-bfb1-41f9-acde-68bde8ad505f" .
  }
}
#
# Governing bodies
#
;
## Voorzitter van het Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/1fd33f8c-9ead-43cd-bb8d-839754ce8647> a besluit:Bestuursorgaan ;
      mu:uuid """1fd33f8c-9ead-43cd-bb8d-839754ce8647""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/2b92a052-8bcd-42b4-ab3b-8028fa5609c5> a besluit:Bestuursorgaan ;
      mu:uuid """2b92a052-8bcd-42b4-ab3b-8028fa5609c5""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/1fd33f8c-9ead-43cd-bb8d-839754ce8647> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/53c0d8cd-f3a2-411d-bece-4bd83ae2bbc9> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Raad voor Maatschappelijk Welzijn
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/7882e0f2-b29c-4d00-b495-71a6f5f04860> a besluit:Bestuursorgaan ;
      mu:uuid """7882e0f2-b29c-4d00-b495-71a6f5f04860""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/43f2ea32-ec1f-415f-b18b-0ecda65e39af> a besluit:Bestuursorgaan ;
      mu:uuid """43f2ea32-ec1f-415f-b18b-0ecda65e39af""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/7882e0f2-b29c-4d00-b495-71a6f5f04860> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000007> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Vast Bureau
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/89292601-de7a-4c5e-b3e4-095616b209cb> a besluit:Bestuursorgaan ;
      mu:uuid """89292601-de7a-4c5e-b3e4-095616b209cb""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/e43538ff-573c-4584-9a5b-6e64327a3e70> a besluit:Bestuursorgaan ;
      mu:uuid """e43538ff-573c-4584-9a5b-6e64327a3e70""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/89292601-de7a-4c5e-b3e4-095616b209cb> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000008> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Bijzonder Comité voor de Sociale Dienst
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/88078a5b-a9a1-4d7a-ac60-19ccf4f4f2c7> a besluit:Bestuursorgaan ;
      mu:uuid """88078a5b-a9a1-4d7a-ac60-19ccf4f4f2c7""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/a6c6402f-987b-4bac-858d-cd9f1a91d29c> a besluit:Bestuursorgaan ;
      mu:uuid """a6c6402f-987b-4bac-858d-cd9f1a91d29c""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/88078a5b-a9a1-4d7a-ac60-19ccf4f4f2c7> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/6f4471e0-c155-4bf1-8558-e77c3cf75638> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
