PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> mu:uuid "cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412" ;
      skos:prefLabel """Beveren-Kruibeke-Zwijndrecht""" ;
      regorg:legalName """Beveren-Kruibeke-Zwijndrecht""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053390> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> adms:identifier <http://data.lblod.info/id/identificatoren/e48e6a1f-8079-427e-9ae4-a0fdbf3d8a1c> .
    <http://data.lblod.info/id/identificatoren/e48e6a1f-8079-427e-9ae4-a0fdbf3d8a1c> a adms:Identifier ;
      mu:uuid """e48e6a1f-8079-427e-9ae4-a0fdbf3d8a1c""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/3d540e3e-e1ea-4ecc-9a70-476e97581d70> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/3d540e3e-e1ea-4ecc-9a70-476e97581d70> a generiek:GestructureerdeIdentificator ;
      mu:uuid """3d540e3e-e1ea-4ecc-9a70-476e97581d70""" ;
      generiek:lokaleIdentificator """1010783451""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> adms:identifier <http://data.lblod.info/id/identificatoren/38cca492-b0be-41a5-b96a-812d4451a6d9> .
    <http://data.lblod.info/id/identificatoren/38cca492-b0be-41a5-b96a-812d4451a6d9> a adms:Identifier ;
      mu:uuid """38cca492-b0be-41a5-b96a-812d4451a6d9""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/2cf8e7f4-d3a2-4662-854b-bb49d4d04cbb> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/2cf8e7f4-d3a2-4662-854b-bb49d4d04cbb> a generiek:GestructureerdeIdentificator ;
      mu:uuid """2cf8e7f4-d3a2-4662-854b-bb49d4d04cbb""" ;
      generiek:lokaleIdentificator """OVO053390""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/identificatoren/052b2f93-ba5b-4f53-a8a3-ebcf99a48e9c> a adms:Identifier ;
      mu:uuid "052b2f93-ba5b-4f53-a8a3-ebcf99a48e9c" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/30ae130f-3b8f-4a4c-8e08-f62e59ab7ccb> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/30ae130f-3b8f-4a4c-8e08-f62e59ab7ccb> a generiek:GestructureerdeIdentificator ;
      mu:uuid "30ae130f-3b8f-4a4c-8e08-f62e59ab7ccb" .
  }
}
;
# scope
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/c9a29e0e-0c7f-4069-910d-641258daa6cb> .
    <http://data.lblod.info/id/werkingsgebieden/c9a29e0e-0c7f-4069-910d-641258daa6cb> a prov:Location ;
      mu:uuid """c9a29e0e-0c7f-4069-910d-641258daa6cb""" ;
      rdfs:label """Beveren-Kruibeke-Zwijndrecht""" ;
      ext:werkingsgebiedNiveau "Gemeente" .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/werkingsgebieden/c9a29e0e-0c7f-4069-910d-641258daa6cb> geo:sfWithin ?locatedWithin .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?locatedWithin a <http://www.w3.org/ns/prov#Location> ;
      rdfs:label ?label .
    FILTER (STR(?label) = """Waasland""")
  }
}
#
# Governing bodies
#
;
## Burgemeester
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/e2351257-1ebc-48ea-9b14-bd7698dec7fe> a besluit:Bestuursorgaan ;
      mu:uuid """e2351257-1ebc-48ea-9b14-bd7698dec7fe""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/ecc2d683-b804-4266-9cfd-b3fca23b712e> a besluit:Bestuursorgaan ;
      mu:uuid """ecc2d683-b804-4266-9cfd-b3fca23b712e""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/e2351257-1ebc-48ea-9b14-bd7698dec7fe> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Gemeenteraad
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/dc048d1e-16a6-4bc6-988d-06f676bae795> a besluit:Bestuursorgaan ;
      mu:uuid """dc048d1e-16a6-4bc6-988d-06f676bae795""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/69c9dd66-c624-494e-a796-696ad29ae0cc> a besluit:Bestuursorgaan ;
      mu:uuid """69c9dd66-c624-494e-a796-696ad29ae0cc""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/dc048d1e-16a6-4bc6-988d-06f676bae795> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## College van Burgemeester en Schepenen
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/df293266-aa4e-4f2d-bce4-9e90ba1d10ce> a besluit:Bestuursorgaan ;
      mu:uuid """df293266-aa4e-4f2d-bce4-9e90ba1d10ce""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/8a7a3797-92db-4a61-9a96-a6e9906ae75f> a besluit:Bestuursorgaan ;
      mu:uuid """8a7a3797-92db-4a61-9a96-a6e9906ae75f""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/df293266-aa4e-4f2d-bce4-9e90ba1d10ce> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/474fc497-860b-47ca-93bd-09538c61a0f4> a besluit:Bestuursorgaan ;
      mu:uuid """474fc497-860b-47ca-93bd-09538c61a0f4""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/44a3c3df-3518-402e-9941-dfda997da444> a besluit:Bestuursorgaan ;
      mu:uuid """44a3c3df-3518-402e-9941-dfda997da444""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/474fc497-860b-47ca-93bd-09538c61a0f4> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Adjunct-algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/550ad610-6954-4170-ad6b-b6ea25b1f0c5> a besluit:Bestuursorgaan ;
      mu:uuid """550ad610-6954-4170-ad6b-b6ea25b1f0c5""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/8c0d39ba-bffc-4a08-ac3f-f36fcf446694> a besluit:Bestuursorgaan ;
      mu:uuid """8c0d39ba-bffc-4a08-ac3f-f36fcf446694""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/550ad610-6954-4170-ad6b-b6ea25b1f0c5> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/c8b77803-6490-4b74-be22-9f6a0d31884e> a besluit:Bestuursorgaan ;
      mu:uuid """c8b77803-6490-4b74-be22-9f6a0d31884e""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/544013f9-9d58-41ce-9413-63d49c83dc30> a besluit:Bestuursorgaan ;
      mu:uuid """544013f9-9d58-41ce-9413-63d49c83dc30""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/c8b77803-6490-4b74-be22-9f6a0d31884e> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
;
## Adjunct-financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/c61f2753-f767-40cc-923c-cd46f22b1394> a besluit:Bestuursorgaan ;
      mu:uuid """c61f2753-f767-40cc-923c-cd46f22b1394""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/eedad091-80a0-4ce1-b99f-657a0e6ca246> a besluit:Bestuursorgaan ;
      mu:uuid """eedad091-80a0-4ce1-b99f-657a0e6ca246""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/c61f2753-f767-40cc-923c-cd46f22b1394> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Beveren-Kruibeke-Zwijndrecht") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/cc2c8c98-5f2a-471a-b6e2-65fa1c7dd412> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
