PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
      <http://www.w3.org/ns/org#Organization> ,
      <http://purl.org/dc/terms/Agent> .
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> mu:uuid "5bcd5343-d784-47a4-9818-871a5550fb19" ;
      skos:prefLabel """Nazareth-De Pinte""" ;
      regorg:legalName """Nazareth-De Pinte""" ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> regorg:orgStatus <http://lblod.data.gift/concepts/abf4fee82019f88cf122f986830621ab> . # In oprichting

    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> owl:sameAs <http://data.vlaanderen.be/doc/organisatie/OVO053388> .

    # KBO number
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> adms:identifier <http://data.lblod.info/id/identificatoren/30cc9d05-a936-4db2-a349-5d54cdb3e26a> .
    <http://data.lblod.info/id/identificatoren/30cc9d05-a936-4db2-a349-5d54cdb3e26a> a adms:Identifier ;
      mu:uuid """30cc9d05-a936-4db2-a349-5d54cdb3e26a""" ;
      skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/571d3b79-1870-493a-8273-6b8d70403b1d> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/571d3b79-1870-493a-8273-6b8d70403b1d> a generiek:GestructureerdeIdentificator ;
      mu:uuid """571d3b79-1870-493a-8273-6b8d70403b1d""" ;
      generiek:lokaleIdentificator """1010781867""" .

    # OVO number
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> adms:identifier <http://data.lblod.info/id/identificatoren/b64ebc3d-013d-49ef-a211-57892f02bdc5> .
    <http://data.lblod.info/id/identificatoren/b64ebc3d-013d-49ef-a211-57892f02bdc5> a adms:Identifier ;
      mu:uuid """b64ebc3d-013d-49ef-a211-57892f02bdc5""" ;
      skos:notation "OVO-nummer" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/446ed124-9ae3-42bf-a398-54c94752236d> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/446ed124-9ae3-42bf-a398-54c94752236d> a generiek:GestructureerdeIdentificator ;
      mu:uuid """446ed124-9ae3-42bf-a398-54c94752236d""" ;
      generiek:lokaleIdentificator """OVO053388""" .

    # Placeholder for SharePoint identifier
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> adms:identifier <http://data.lblod.info/id/identificatoren/e6610cfe-98ac-4989-9dca-0318003143b1> .
    <http://data.lblod.info/id/identificatoren/e6610cfe-98ac-4989-9dca-0318003143b1> a adms:Identifier ;
      mu:uuid "e6610cfe-98ac-4989-9dca-0318003143b1" ;
      skos:notation "SharePoint identificator" ;
      generiek:gestructureerdeIdentificator <http://data.lblod.info/id/gestructureerdeIdentificatoren/c05ffb8a-4823-40a0-aada-add563448c7b> .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/c05ffb8a-4823-40a0-aada-add563448c7b> a generiek:GestructureerdeIdentificator ;
      mu:uuid "c05ffb8a-4823-40a0-aada-add563448c7b" .
  }
}
;
# scope
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> besluit:werkingsgebied <http://data.lblod.info/id/werkingsgebieden/f3f6db7a-504f-4645-b8b8-8ffb6c81ae61> .
    <http://data.lblod.info/id/werkingsgebieden/f3f6db7a-504f-4645-b8b8-8ffb6c81ae61> a prov:Location ;
      mu:uuid """f3f6db7a-504f-4645-b8b8-8ffb6c81ae61""" ;
      rdfs:label """Nazareth-De Pinte""" ;
      ext:werkingsgebiedNiveau "Gemeente" .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/werkingsgebieden/f3f6db7a-504f-4645-b8b8-8ffb6c81ae61> geo:sfWithin ?locatedWithin .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?locatedWithin a <http://www.w3.org/ns/prov#Location> ;
      rdfs:label ?label .
    FILTER (STR(?label) = """Regio Gent""")
  }
}
#
# Governing bodies
#
;
## Burgemeester
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/7d1d11c3-b314-4171-9c3f-ab9c845ef6b4> a besluit:Bestuursorgaan ;
      mu:uuid """7d1d11c3-b314-4171-9c3f-ab9c845ef6b4""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/3f0c4f34-bd15-444d-8ecc-5cb31dc9a9ff> a besluit:Bestuursorgaan ;
      mu:uuid """3f0c4f34-bd15-444d-8ecc-5cb31dc9a9ff""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/7d1d11c3-b314-4171-9c3f-ab9c845ef6b4> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Gemeenteraad
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/798206f4-d390-47ef-a3cc-207646daf7e2> a besluit:Bestuursorgaan ;
      mu:uuid """798206f4-d390-47ef-a3cc-207646daf7e2""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/769f75aa-3e64-437b-a472-2ce7a336e78d> a besluit:Bestuursorgaan ;
      mu:uuid """769f75aa-3e64-437b-a472-2ce7a336e78d""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/798206f4-d390-47ef-a3cc-207646daf7e2> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## College van Burgemeester en Schepenen
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/ebefd20f-da7e-44cf-960a-1c431fec32bc> a besluit:Bestuursorgaan ;
      mu:uuid """ebefd20f-da7e-44cf-960a-1c431fec32bc""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/4b908c93-ac33-4cfa-b857-1d1044c99e13> a besluit:Bestuursorgaan ;
      mu:uuid """4b908c93-ac33-4cfa-b857-1d1044c99e13""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/ebefd20f-da7e-44cf-960a-1c431fec32bc> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/42259c88-e000-4744-b08c-f9dc044270b3> a besluit:Bestuursorgaan ;
      mu:uuid """42259c88-e000-4744-b08c-f9dc044270b3""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/9d1448e3-9916-4c1e-bf22-1b39bee87e4a> a besluit:Bestuursorgaan ;
      mu:uuid """9d1448e3-9916-4c1e-bf22-1b39bee87e4a""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/42259c88-e000-4744-b08c-f9dc044270b3> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Adjunct-algemeen directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/d10c6635-7ff3-4686-8a96-31f8a927cbc8> a besluit:Bestuursorgaan ;
      mu:uuid """d10c6635-7ff3-4686-8a96-31f8a927cbc8""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/9e1f022a-1e07-45f8-b53d-e141f32dda98> a besluit:Bestuursorgaan ;
      mu:uuid """9e1f022a-1e07-45f8-b53d-e141f32dda98""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/d10c6635-7ff3-4686-8a96-31f8a927cbc8> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/b8dd7224-07bd-4fc3-86c2-245a5bcd8dc4> a besluit:Bestuursorgaan ;
      mu:uuid """b8dd7224-07bd-4fc3-86c2-245a5bcd8dc4""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/dab9769c-91f1-422f-b361-15707320292b> a besluit:Bestuursorgaan ;
      mu:uuid """dab9769c-91f1-422f-b361-15707320292b""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/b8dd7224-07bd-4fc3-86c2-245a5bcd8dc4> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
;
## Adjunct-financieel directeur
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    # Abstract governing body
    <http://data.lblod.info/id/bestuursorganen/89bf525d-536d-4a28-a54a-7e0936ffb5a5> a besluit:Bestuursorgaan ;
      mu:uuid """89bf525d-536d-4a28-a54a-7e0936ffb5a5""" ;
      skos:prefLabel ?governingBodyLabel ;
      besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> ;
      org:classification <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> .

    # Timed specialisation for governing body
    <http://data.lblod.info/id/bestuursorganen/0e5dabc6-ad06-40c9-ac69-57aa87e2a9b2> a besluit:Bestuursorgaan ;
      mu:uuid """0e5dabc6-ad06-40c9-ac69-57aa87e2a9b2""" ;
      generiek:isTijdspecialisatieVan <http://data.lblod.info/id/bestuursorganen/89bf525d-536d-4a28-a54a-7e0936ffb5a5> ;
      mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime .
  }
} WHERE {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0> skos:prefLabel ?classificationLabel .

    BIND(CONCAT(?classificationLabel, " ", "Nazareth-De Pinte") as ?governingBodyLabel)
}
#
# Related province
#
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?province org:hasSubOrganization <http://data.lblod.info/id/bestuurseenheden/5bcd5343-d784-47a4-9818-871a5550fb19> .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?province skos:prefLabel """Oost-Vlaanderen""" .
  }
}
