PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX scheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX concept: <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    concept:35833ba2-7371-400b-8df2-2912f66fb153 a code:BestuurseenheidClassificatieCode ;
      a ext:OrganizationClassificationCode ;
      core:uuid "35833ba2-7371-400b-8df2-2912f66fb153" ;
      skos:prefLabel "Vereniging of vennootschap voor sociale dienstverlening" ;
      skos:inScheme scheme:BestuurseenheidClassificatieCode ;
      skos:topConceptOf scheme:BestuurseenheidClassificatieCode .
  }
}
