PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX scheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX concept: <http://data.vlaanderen.be/id/concept/GeregistreerdeOrganisatieClassificatieCode/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    concept:82fd21dc-e8bb-4d13-a010-f4a12358ef10 a ext:GeregistreerdeOrganisatieClassificatieCode ;
      a ext:OrganizationClassificationCode ;
      core:uuid "82fd21dc-e8bb-4d13-a010-f4a12358ef10" ;
      skos:prefLabel "Woonzorgvereniging of woonzorgvennootschap" ;
      skos:inScheme scheme:GeregistreerdeOrganisatieClassificatieCode ;
      skos:topConceptOf scheme:GeregistreerdeOrganisatieClassificatieCode .
  }
}
