PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX person: <http://www.w3.org/ns/person#>

# DL and OP both use persoon:gebruikteVoornaam but with different semantics (!)

# Alternatieve voornaam: foaf:name => persoon:gebruikteVoornaam

CONSTRUCT {
  ?s persoon:gebruikteVoornaam ?name .
} WHERE {
  ?s a person:Person ;
    foaf:name ?name .
}
