delete where {
 graph ?g {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/00b8f19ce0fafa090df049498337aad8> ?p ?o.
 }
}

;

delete {
 graph ?g {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/0da11d9fdef2d45f90fd4ebd353ecd3c> <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
 }
}
insert {
 graph ?g {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/0da11d9fdef2d45f90fd4ebd353ecd3c> <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> 100.
 }
}
where {
 graph ?g {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/0da11d9fdef2d45f90fd4ebd353ecd3c> <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
 }
}
