INSERT 
{ GRAPH <http://mu.semte.ch/graphs/administrative-unit>  
	{ ?address <https://data.vlaanderen.be/ns/adres#adresIsGelegenIn> ?province_uri} 
} 
WHERE 
{ 
	?address rdf:type <http://www.w3.org/ns/locn#Address> . 
	?address <http://www.w3.org/ns/locn#adminUnitL2> ?province_literal . 
	?province_uri rdfs:label ?province_literal. 
	?province_uri <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Provincie".
}


