
  # Classification Directiecomité

  INSERT {
    GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?orgaanInTime a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaanInTime ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00"^^xsd:dateTime .
  
    ?orgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaan ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?orgaanLabel ;
      <http://www.w3.org/ns/org#classification> ?classificationOrgaan ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> ?bestuurseenheid .
    }
  } WHERE {
    VALUES ?classificationBestuurseenheid {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>
    }
  
    VALUES ?classificationOrgaan {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8>
    }
  
    VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/c7c5afb0-33b6-4c12-9a91-0313c5e99e09>
<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
<http://data.lblod.info/id/bestuurseenheden/2d7e83eb-ce57-4739-917c-66564653ad63>
<http://data.lblod.info/id/bestuurseenheden/dc0bae7b-c4b3-4318-a6d5-63da2026a19f>
<http://data.lblod.info/id/bestuurseenheden/47fe127d-40c9-4598-a651-fca0311d3546>
<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
<http://data.lblod.info/id/bestuurseenheden/68691928-eb23-4cc4-a66a-9deb0a7228ac>
<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
<http://data.lblod.info/id/bestuurseenheden/682c21df-fe6a-4266-8f97-109e5b5b4ae4>
<http://data.lblod.info/id/bestuurseenheden/989ffd59-fdc4-4faf-959b-929aadc42f00>
<http://data.lblod.info/id/bestuurseenheden/b8228e3a-13ab-40ff-9299-a547b408b296>
<http://data.lblod.info/id/bestuurseenheden/85594b7a-4637-417e-a8ae-6b77c1988dcd>
<http://data.lblod.info/id/bestuurseenheden/fcbcb79b-20d1-4ed0-8ef1-744ca783ab14>
<http://data.lblod.info/id/bestuurseenheden/42fe138a-47b0-426e-a319-66bbf7927168>
<http://data.lblod.info/id/bestuurseenheden/173816cd-8ab6-45b8-9e98-1b8a71ad7ba0>
    }
  
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      skos:prefLabel ?bestuurseenheidLabel .
  
    ?classificationOrgaan skos:prefLabel ?classificationOrgaanLabel .
  
    BIND(CONCAT(?bestuurseenheidLabel, " Leidend ambtenaar") as ?functieLabel)
    BIND(CONCAT(?classificationOrgaanLabel, " ", ?bestuurseenheidLabel) as ?orgaanLabel)
  
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaanInTime")) as ?uuidOrgaanInTime)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaan")) as ?uuidOrgaan)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaanInTime)) AS ?orgaanInTime)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaan)) AS ?orgaan)
  }
  
  ;
  
  # Classification Raad van bestuur

  INSERT {
    GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?orgaanInTime a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaanInTime ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00"^^xsd:dateTime .
  
    ?orgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaan ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?orgaanLabel ;
      <http://www.w3.org/ns/org#classification> ?classificationOrgaan ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> ?bestuurseenheid .
    }
  } WHERE {
    VALUES ?classificationBestuurseenheid {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>
    }
  
    VALUES ?classificationOrgaan {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943>
    }
  
    VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/c7c5afb0-33b6-4c12-9a91-0313c5e99e09>
<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
<http://data.lblod.info/id/bestuurseenheden/2d7e83eb-ce57-4739-917c-66564653ad63>
<http://data.lblod.info/id/bestuurseenheden/dc0bae7b-c4b3-4318-a6d5-63da2026a19f>
<http://data.lblod.info/id/bestuurseenheden/47fe127d-40c9-4598-a651-fca0311d3546>
<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
<http://data.lblod.info/id/bestuurseenheden/68691928-eb23-4cc4-a66a-9deb0a7228ac>
<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
<http://data.lblod.info/id/bestuurseenheden/682c21df-fe6a-4266-8f97-109e5b5b4ae4>
<http://data.lblod.info/id/bestuurseenheden/989ffd59-fdc4-4faf-959b-929aadc42f00>
<http://data.lblod.info/id/bestuurseenheden/b8228e3a-13ab-40ff-9299-a547b408b296>
<http://data.lblod.info/id/bestuurseenheden/85594b7a-4637-417e-a8ae-6b77c1988dcd>
<http://data.lblod.info/id/bestuurseenheden/fcbcb79b-20d1-4ed0-8ef1-744ca783ab14>
<http://data.lblod.info/id/bestuurseenheden/42fe138a-47b0-426e-a319-66bbf7927168>
<http://data.lblod.info/id/bestuurseenheden/173816cd-8ab6-45b8-9e98-1b8a71ad7ba0>
    }
  
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      skos:prefLabel ?bestuurseenheidLabel .
  
    ?classificationOrgaan skos:prefLabel ?classificationOrgaanLabel .
  
    BIND(CONCAT(?bestuurseenheidLabel, " Leidend ambtenaar") as ?functieLabel)
    BIND(CONCAT(?classificationOrgaanLabel, " ", ?bestuurseenheidLabel) as ?orgaanLabel)
  
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaanInTime")) as ?uuidOrgaanInTime)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaan")) as ?uuidOrgaan)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaanInTime)) AS ?orgaanInTime)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaan)) AS ?orgaan)
  }
  
  ;
  
  # Classification Bevoegd beslissingsorgaan
  
  INSERT {
    GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?orgaanInTime a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaanInTime ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00"^^xsd:dateTime .
  
    ?orgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaan ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?orgaanLabel ;
      <http://www.w3.org/ns/org#classification> ?classificationOrgaan ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> ?bestuurseenheid .
    }
  } WHERE {
    VALUES ?classificationBestuurseenheid {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>
    }
  
    VALUES ?classificationOrgaan {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/0dbc70ec-6be9-4997-b8e1-11b6c0542382>
    }
  
    VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/c7c5afb0-33b6-4c12-9a91-0313c5e99e09>
<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
<http://data.lblod.info/id/bestuurseenheden/2d7e83eb-ce57-4739-917c-66564653ad63>
<http://data.lblod.info/id/bestuurseenheden/dc0bae7b-c4b3-4318-a6d5-63da2026a19f>
<http://data.lblod.info/id/bestuurseenheden/47fe127d-40c9-4598-a651-fca0311d3546>
<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
<http://data.lblod.info/id/bestuurseenheden/68691928-eb23-4cc4-a66a-9deb0a7228ac>
<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
<http://data.lblod.info/id/bestuurseenheden/682c21df-fe6a-4266-8f97-109e5b5b4ae4>
<http://data.lblod.info/id/bestuurseenheden/989ffd59-fdc4-4faf-959b-929aadc42f00>
<http://data.lblod.info/id/bestuurseenheden/b8228e3a-13ab-40ff-9299-a547b408b296>
<http://data.lblod.info/id/bestuurseenheden/85594b7a-4637-417e-a8ae-6b77c1988dcd>
<http://data.lblod.info/id/bestuurseenheden/fcbcb79b-20d1-4ed0-8ef1-744ca783ab14>
<http://data.lblod.info/id/bestuurseenheden/42fe138a-47b0-426e-a319-66bbf7927168>
<http://data.lblod.info/id/bestuurseenheden/173816cd-8ab6-45b8-9e98-1b8a71ad7ba0>
    }
  
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      skos:prefLabel ?bestuurseenheidLabel .
  
    ?classificationOrgaan skos:prefLabel ?classificationOrgaanLabel .
  
    BIND(CONCAT(?bestuurseenheidLabel, " Leidend ambtenaar") as ?functieLabel)
    BIND(CONCAT(?classificationOrgaanLabel, " ", ?bestuurseenheidLabel) as ?orgaanLabel)
  
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaanInTime")) as ?uuidOrgaanInTime)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaan")) as ?uuidOrgaan)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaanInTime)) AS ?orgaanInTime)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaan)) AS ?orgaan)
  }
  
  ;
  
  # Classification Algemene vergadering
  
  INSERT {
    GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?orgaanInTime a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaanInTime ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00"^^xsd:dateTime .
  
    ?orgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaan ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?orgaanLabel ;
      <http://www.w3.org/ns/org#classification> ?classificationOrgaan ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> ?bestuurseenheid .
    }
  } WHERE {
    VALUES ?classificationBestuurseenheid {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>
    }
  
    VALUES ?classificationOrgaan {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528>
    }
  
    VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/c7c5afb0-33b6-4c12-9a91-0313c5e99e09>
<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
<http://data.lblod.info/id/bestuurseenheden/2d7e83eb-ce57-4739-917c-66564653ad63>
<http://data.lblod.info/id/bestuurseenheden/dc0bae7b-c4b3-4318-a6d5-63da2026a19f>
<http://data.lblod.info/id/bestuurseenheden/47fe127d-40c9-4598-a651-fca0311d3546>
<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
<http://data.lblod.info/id/bestuurseenheden/68691928-eb23-4cc4-a66a-9deb0a7228ac>
<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
<http://data.lblod.info/id/bestuurseenheden/682c21df-fe6a-4266-8f97-109e5b5b4ae4>
<http://data.lblod.info/id/bestuurseenheden/989ffd59-fdc4-4faf-959b-929aadc42f00>
<http://data.lblod.info/id/bestuurseenheden/b8228e3a-13ab-40ff-9299-a547b408b296>
<http://data.lblod.info/id/bestuurseenheden/85594b7a-4637-417e-a8ae-6b77c1988dcd>
<http://data.lblod.info/id/bestuurseenheden/fcbcb79b-20d1-4ed0-8ef1-744ca783ab14>
<http://data.lblod.info/id/bestuurseenheden/42fe138a-47b0-426e-a319-66bbf7927168>
<http://data.lblod.info/id/bestuurseenheden/173816cd-8ab6-45b8-9e98-1b8a71ad7ba0>
    }
  
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      skos:prefLabel ?bestuurseenheidLabel .
  
    ?classificationOrgaan skos:prefLabel ?classificationOrgaanLabel .
  
    BIND(CONCAT(?bestuurseenheidLabel, " Leidend ambtenaar") as ?functieLabel)
    BIND(CONCAT(?classificationOrgaanLabel, " ", ?bestuurseenheidLabel) as ?orgaanLabel)
  
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaanInTime")) as ?uuidOrgaanInTime)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaan")) as ?uuidOrgaan)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaanInTime)) AS ?orgaanInTime)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaan)) AS ?orgaan)
  }
  
  ;
  
  # Classification Leidend Ambtenaar
  
  INSERT {
    GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?orgaanInTime a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaanInTime ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> ?orgaan ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00"^^xsd:dateTime ;
      <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> ?functie .
  
    ?orgaan a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidOrgaan ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?orgaanLabel ;
      <http://www.w3.org/ns/org#classification> ?classificationOrgaan ;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> ?bestuurseenheid .

    ?functie a <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuidFunctie ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> ?functieLabel ;
      <http://www.w3.org/ns/org#role> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/855489b9-b584-4f34-90b2-39aea808cd9f> .
    }
  } WHERE {
    VALUES ?classificationBestuurseenheid {
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>
      <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/80310756-ce0a-4a1b-9b8e-7c01b6cc7a2d>
    }
  
    VALUES ?classificationOrgaan {
      <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/41caf7e6-b040-4720-9cc2-a96cfffed5b4>
    }
  
    VALUES ?bestuurseenheid {
      <http://data.lblod.info/id/bestuurseenheden/c7c5afb0-33b6-4c12-9a91-0313c5e99e09>
<http://data.lblod.info/id/bestuurseenheden/0f3d264a-dc1e-4a67-b2dc-b16b8aa1320d>
<http://data.lblod.info/id/bestuurseenheden/cc175465-0aa7-4f86-b6c1-fb9e4968def9>
<http://data.lblod.info/id/bestuurseenheden/ab64b799-fc73-417a-9fde-ad15da02944e>
<http://data.lblod.info/id/bestuurseenheden/923b203c-b8e0-4f20-9076-c2381e0f4294>
<http://data.lblod.info/id/bestuurseenheden/8c8fb770-1b84-4d18-8bcc-3ed9440476d5>
<http://data.lblod.info/id/bestuurseenheden/2d7e83eb-ce57-4739-917c-66564653ad63>
<http://data.lblod.info/id/bestuurseenheden/dc0bae7b-c4b3-4318-a6d5-63da2026a19f>
<http://data.lblod.info/id/bestuurseenheden/47fe127d-40c9-4598-a651-fca0311d3546>
<http://data.lblod.info/id/bestuurseenheden/d0125202-c4b1-4372-ba12-d6de58b12660>
<http://data.lblod.info/id/bestuurseenheden/68691928-eb23-4cc4-a66a-9deb0a7228ac>
<http://data.lblod.info/id/bestuurseenheden/344ff196-00d6-4d31-8abf-bda1a3c06b23>
<http://data.lblod.info/id/bestuurseenheden/26009b3c-256e-4a6c-aa3f-48e37b5d5c64>
<http://data.lblod.info/id/bestuurseenheden/682c21df-fe6a-4266-8f97-109e5b5b4ae4>
<http://data.lblod.info/id/bestuurseenheden/989ffd59-fdc4-4faf-959b-929aadc42f00>
<http://data.lblod.info/id/bestuurseenheden/b8228e3a-13ab-40ff-9299-a547b408b296>
<http://data.lblod.info/id/bestuurseenheden/85594b7a-4637-417e-a8ae-6b77c1988dcd>
<http://data.lblod.info/id/bestuurseenheden/fcbcb79b-20d1-4ed0-8ef1-744ca783ab14>
<http://data.lblod.info/id/bestuurseenheden/42fe138a-47b0-426e-a319-66bbf7927168>
<http://data.lblod.info/id/bestuurseenheden/173816cd-8ab6-45b8-9e98-1b8a71ad7ba0>
    }
  
    ?bestuurseenheid a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ;
      skos:prefLabel ?bestuurseenheidLabel .
  
    ?classificationOrgaan skos:prefLabel ?classificationOrgaanLabel .
  
    BIND(CONCAT(?bestuurseenheidLabel, " Leidend ambtenaar") as ?functieLabel)
    BIND(CONCAT(?classificationOrgaanLabel, " ", ?bestuurseenheidLabel) as ?orgaanLabel)
  
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaanInTime")) as ?uuidOrgaanInTime)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "orgaan")) as ?uuidOrgaan)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaanInTime)) AS ?orgaanInTime)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursorganen/", ?uuidOrgaan)) AS ?orgaan)
    BIND(MD5(CONCAT(?bestuurseenheid, ?classificationOrgaan, "functieLabel")) as ?uuidFunctie)
    BIND(IRI(CONCAT("http://data.lblod.info/id/bestuursfuncties/", ?uuidFunctie)) AS ?functie)
  }
  