
      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0686668938" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459795044" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862298029" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0678818074" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0456552868" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0749418139" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0893525002" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0639968287" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0741624386" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0507873093" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0413873759" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0895509839" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0462429187" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0630602344" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0665587076" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0469368647" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0468105073" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542485762" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0543423395" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542480220" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0543424880" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542487247" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0867303526" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0474761451" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0455635130" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866093105" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0820653751" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0771948863" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0418558364" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0450062281" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0841556855" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0749895122" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0413845055" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0436978070" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0410436890" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0802469815" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0546845319" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0422264556" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0407576182" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0420175591" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0464169348" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0861837773" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881008933" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0642642123" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0445294237" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0420392258" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0806608349" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0463025441" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    