
        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://gezinszorgronse.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0686668938" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.antwerpen.be/nl/info/52d5051c39d8a6ec798b4670/pwa-plaatselijk-werkgelegenheidsagentschap" .
            ?contact <http://schema.org/email> "wijkwerken.antwerpen@vdab.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459795044" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.paddenbroek.be/" .
            ?contact <http://schema.org/email> "info@gooik.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862298029" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://demuseumstichting.be/" .
            ?contact <http://schema.org/email> "info@demuseumstichting.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0678818074" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.inforegio.be/pwa-dienstenbedrijf-dico" .
            ?contact <http://schema.org/email> "info@herk-de-stad.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0456552868" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+32489692388" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.buitengoed.be/" .
            ?contact <http://schema.org/email> "info@buitengoed.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0749418139" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3259242300" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://odoo.economischhuis.be/" .
            ?contact <http://schema.org/email> "info@economischhuis.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0893525002" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3213460644" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.diest.be/ontmoetingscentra" .
            ?contact <http://schema.org/email> "evenementenloket@diest.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0639968287" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://handelshart.be/" .
            ?contact <http://schema.org/email> "info@handelshart.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0741624386" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292657840" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.amal.gent/" .
            ?contact <http://schema.org/email> "info@amal.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0507873093" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292665380" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://sodi.gent.be/" .
            ?contact <http://schema.org/email> "sodigent@stad.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0413873759" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292187590" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.vzwregent.be/" .
            ?contact <http://schema.org/email> "info@vzwregent.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0895509839" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292668300" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://stad.gent/nl/werken-ondernemen/werken/werken-regio-gent/wijk-werken-gent" .
            ?contact <http://schema.org/email> "wijk-werken@stad.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0462429187" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292668400" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://stad.gent/nl/puur-gent/alles-over-puurgent" .
            ?contact <http://schema.org/email> "puurgent@stad.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0630602344" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292667700" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://fietsambassade.gent.be/nl" .
            ?contact <http://schema.org/email> "info.defietsambassade@stad.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0665587076" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3293236565" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://decentrale.be/" .
            ?contact <http://schema.org/email> "decentrale@stad.gent" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0469368647" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3293236111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.bijloke.be/" .
            ?contact <http://schema.org/email> "info@debijloke.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0468105073" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250819830" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.oostkamp.be/cowgom_vzw" .
            ?contact <http://schema.org/email> "personeelsdienst@oostkamp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542485762" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250819900" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.oostkamp.be/jeugdhuis-joc-den-artisjoc" .
            ?contact <http://schema.org/email> "jeugd@oostkamp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0543423395" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250819900" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.oostkamp.be/spwok_vzw" .
            ?contact <http://schema.org/email> "jeugd@oostkamp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542480220" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250819800" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.oostkamp.be/raad/detail/25/uitleendienst-feestmateriaal-vzw" .
            ?contact <http://schema.org/email> "gebouwen@oostkamp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0543424880" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250819900" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.oostkamp.be/raad/detail/28/verbroederingscomite-vzw" .
            ?contact <http://schema.org/email> "vrijetijd@oostkamp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0542487247" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253607256" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sint-lievens-houtem.be/eva-vzw-welzijnsraad" .
            ?contact <http://schema.org/email> "info@ocmwsintlievenshoutem.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0867303526" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3293623062" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.muziekcentrum.org" .
            ?contact <http://schema.org/email> "muziekcentrum@telenet.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0474761451" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253607259" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sint-lievens-houtem.be/eva-vzw-dco-livinus" .
            ?contact <http://schema.org/email> "poetsdienst@sint-lievens-houtem.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0455635130" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.tongeren.be/plinius" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866093105" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3257346668" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.poperinge.be/vzw-ondernemen-hoppeland" .
            ?contact <http://schema.org/email> "ondernemen@poperinge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0820653751" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.vlaamsbrabant.be/nl/erfgoed/erfgoedstichting-vlaams-brabant-erf" .
            ?contact <http://schema.org/email> "info@erfgoedstichting.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0771948863" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3236666741" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.arboretumkalmthout.be/" .
            ?contact <http://schema.org/email> "info@arboretumkalmthout.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0418558364" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215557005" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.denekker.be/" .
            ?contact <http://schema.org/email> "reservatie@denekker.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0450062281" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214562870" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.provincieantwerpen.be/aanbod/dese/dlp1/proefbedrijf-pluimveehouderij-vzw.html" .
            ?contact <http://schema.org/email> "proefbedrijf@provincieantwerpen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0841556855" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215228233" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.kempenslandschap.be/nl" .
            ?contact <http://schema.org/email> "info@kempenslandschap.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0749895122" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3216290174" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.vlaamsbrabant.be/nl/economie-en-landbouw/praktijkpunt-landbouw-vlaams-brabant-vzw" .
            ?contact <http://schema.org/email> "praktijkpuntlandbouw@vlaamsbrabant.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0413845055" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211239711" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.hasselt.be/nl/crematorium" .
            ?contact <http://schema.org/email> "crematorium@hasselt.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0436978070" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292678610" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.erov.be/" .
            ?contact <http://schema.org/email> "info@erov.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0410436890" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250636560" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.blankenberge.be/lokale-economie" .
            ?contact <http://schema.org/email> "middenstand@blankenberge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0802469815" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3223716316" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sint-pieters-leeuw.be/cc-coloma" .
            ?contact <http://schema.org/email> "cultuur@sint-pieters-leeuw.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0546845319" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://erfgoedlommel.be/" .
            ?contact <http://schema.org/email> "info@erfgoedlommel.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0422264556" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211399600" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://toerismelommel.be/" .
            ?contact <http://schema.org/email> "info@toerismelommel.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0407576182" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3223800119" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.fermehollekenhoeve.be/nl/" .
            ?contact <http://schema.org/email> "info@fermehollekenhoeve.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0420175591" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3223800480" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://linkebeeksport.be/nl/wensen-van-linkebeek-sport" .
            ?contact <http://schema.org/email> "info@linkebeeksport.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0464169348" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215294900" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.lamot-mechelen.be/contact/" .
            ?contact <http://schema.org/email> "sales@lamot-mechelen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0861837773" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215297901" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.mechelen.be/contact-mechelen-feest" .
            ?contact <http://schema.org/email> "mechelenfeest@mechelen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881008933" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      


        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215677246" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://jamvzw.be/" .
            ?contact <http://schema.org/email> "boekhouding@jamvzw.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0445294237" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214557901" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.delilsebergen.be/" .
            ?contact <http://schema.org/email> "info@lilsebergen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0420392258" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.stichtinglsm.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0806608349" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3258335571" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.veurne.be/nl/bestuur/overzicht-bestuur/de-vleermuis-veurne-eva-vzw" .
            ?contact <http://schema.org/email> "jeugddienst@veurne.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0463025441" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      