PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?timedBody mandaat:bindingEinde "2024-12-31"^^xsd:dateTime
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?agb a besluit:Bestuurseenheid;
           org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/36a82ba0-7ff1-4697-a9dd-2e94df73b721>. # AGB
      ?body besluit:bestuurt ?agb;
            org:classification ?classification.
      ?timedBody generiek:isTijdspecialisatieVan ?body.
      FILTER NOT EXISTS {?timedBody mandaat:bindingEinde ?endDate.}
  }
  VALUES ?classification {
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> # Algemene vergadering
    <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> # Raad van bestuur
  }
}
