

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-09-25"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620E5F3D5747C883CA1D2ED9" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-09-25"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620E60565747C883CA1D2EDD" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-08-30"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F7B69D51BFC225E4ECF0DC" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-09-20"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63E4D0441C2DE4F40F38C090" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-09-20"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62062E625747C883CA1D2CC2" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-21"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620E5CF95747C883CA1D2ED5" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-07"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F93F2451BFC225E4ECF3A6" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-22"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62052EAC5747C883CA1D2C53" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-08-18"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F93CD951BFC225E4ECF389" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-31"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA2EFD51BFC225E4ECF424" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-31"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA315E51BFC225E4ECF42A" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA2EFD51BFC225E4ECF424" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA325B51BFC225E4ECF438" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-31"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA315E51BFC225E4ECF42A" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-30"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA325B51BFC225E4ECF438" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-30"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA315E51BFC225E4ECF42A" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-15"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F90E2551BFC225E4ECF2CE" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-23"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620E62AC5747C883CA1D2EE1" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA374D51BFC225E4ECF45F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F90CAF51BFC225E4ECF2CA" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA374D51BFC225E4ECF45F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F9303C51BFC225E4ECF31F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-10-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA374D51BFC225E4ECF45F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F90CAF51BFC225E4ECF2CA" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA356951BFC225E4ECF44D" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA38EC51BFC225E4ECF46E" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA374D51BFC225E4ECF45F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F9303C51BFC225E4ECF31F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA384A51BFC225E4ECF46B" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61FA38EC51BFC225E4ECF46E" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F93B2351BFC225E4ECF379" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-11-29"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620630025747C883CA1D2CC6" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-02"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F94D7E51BFC225E4ECF3EF" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-02"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F9434F51BFC225E4ECF3BE" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-02"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F94DEA51BFC225E4ECF3FA" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-02"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F94D7E51BFC225E4ECF3EF" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-02"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "6203649251BFC225E4ECF8C3" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2013-03-17"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61EFCD721CF2D31D1748D7F6" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-13"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "6203622F51BFC225E4ECF8C0" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-13"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F92B0A51BFC225E4ECF2FF" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2021-12-13"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "61F92B8D51BFC225E4ECF307" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-01-08"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620A68685747C883CA1D2DA8" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-01-08"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "620A6AE35747C883CA1D2DAC" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-03"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "628635101D2B7BB5B2CB0643" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-17"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62332D0AB72F9F4B33507FBE" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-17"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62332DC7B72F9F4B33507FC2" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-17"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62332D0AB72F9F4B33507FBE" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-12"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "6243FC267B850F1C3687AB3F" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-02-28"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "6256B9048A3D153ADACC03F4" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-04-15"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62C6BE97D7779543F77795DA" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-04-23"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "62D110D6D7779543F777966B" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-06-03"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "630F1AED2F583C7A1CD0DBC3" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-06-24"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "633A9EDB036B579F0A26FFC9" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-06-28"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "633EB3B6036B579F0A270012" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-10-10"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63A2CAC726577078270F82F1" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-08-20"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "6380DDD34B5FEAF28DEDE982" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-11-23"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63BBFE764E1F899807CFF9BD" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-11-18"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63C512F34E1F899807CFFB75" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-12-06"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63D3E96E5410CAD909EF6D10" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2022-12-16"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63FF1583886F92ABFC08D0E6" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-01-04"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63F345051C2DE4F40F38C0A9" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-01-04"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63F345E71C2DE4F40F38C0B1" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-01-04"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63F345051C2DE4F40F38C0A9" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-01-04"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63F345E71C2DE4F40F38C0B1" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-01-04"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "63F345051C2DE4F40F38C0A9" 
        }
      }
      ;

      DELETE{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date
        }
      }
      INSERT{
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> "2023-04-05"^^xsd:date
        }
      }
      WHERE {
        VALUES ?g {
          <http://mu.semte.ch/graphs/worship-service>
          
        }
        GRAPH ?g {
          ?changeEvent <http://purl.org/dc/terms/date> ?date ;
                       <http://mu.semte.ch/vocabularies/core/uuid> "642D68BEE025A7C706F41E58" 
        }
      }
      ;
