

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5F3D5747C883CA1D2ED9> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5F3D5747C883CA1D2ED9> <http://purl.org/dc/terms/date> "2021-09-25"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5F3D5747C883CA1D2ED9> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E60565747C883CA1D2EDD> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E60565747C883CA1D2EDD> <http://purl.org/dc/terms/date> "2021-09-25"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E60565747C883CA1D2EDD> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F7B69D51BFC225E4ECF0DC> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F7B69D51BFC225E4ECF0DC> <http://purl.org/dc/terms/date> "2021-08-30"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F7B69D51BFC225E4ECF0DC> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63E4D0441C2DE4F40F38C090> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63E4D0441C2DE4F40F38C090> <http://purl.org/dc/terms/date> "2021-09-20"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63E4D0441C2DE4F40F38C090> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62062E625747C883CA1D2CC2> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62062E625747C883CA1D2CC2> <http://purl.org/dc/terms/date> "2021-09-20"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62062E625747C883CA1D2CC2> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5CF95747C883CA1D2ED5> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5CF95747C883CA1D2ED5> <http://purl.org/dc/terms/date> "2021-10-21"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5CF95747C883CA1D2ED5> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93F2451BFC225E4ECF3A6> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93F2451BFC225E4ECF3A6> <http://purl.org/dc/terms/date> "2021-10-07"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93F2451BFC225E4ECF3A6> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62052EAC5747C883CA1D2C53> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62052EAC5747C883CA1D2C53> <http://purl.org/dc/terms/date> "2021-10-22"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62052EAC5747C883CA1D2C53> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93CD951BFC225E4ECF389> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93CD951BFC225E4ECF389> <http://purl.org/dc/terms/date> "2021-08-18"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93CD951BFC225E4ECF389> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA2EFD51BFC225E4ECF424> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA2EFD51BFC225E4ECF424> <http://purl.org/dc/terms/date> "2021-10-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA2EFD51BFC225E4ECF424> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA325B51BFC225E4ECF438> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA325B51BFC225E4ECF438> <http://purl.org/dc/terms/date> "2021-10-30"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA325B51BFC225E4ECF438> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA315E51BFC225E4ECF42A> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA315E51BFC225E4ECF42A> <http://purl.org/dc/terms/date> "2021-10-30"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA315E51BFC225E4ECF42A> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90E2551BFC225E4ECF2CE> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90E2551BFC225E4ECF2CE> <http://purl.org/dc/terms/date> "2021-11-15"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90E2551BFC225E4ECF2CE> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E62AC5747C883CA1D2EE1> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E62AC5747C883CA1D2EE1> <http://purl.org/dc/terms/date> "2021-12-23"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E62AC5747C883CA1D2EE1> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90CAF51BFC225E4ECF2CA> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90CAF51BFC225E4ECF2CA> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F90CAF51BFC225E4ECF2CA> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA356951BFC225E4ECF44D> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA356951BFC225E4ECF44D> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA356951BFC225E4ECF44D> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA374D51BFC225E4ECF45F> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA374D51BFC225E4ECF45F> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA374D51BFC225E4ECF45F> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9303C51BFC225E4ECF31F> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9303C51BFC225E4ECF31F> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9303C51BFC225E4ECF31F> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA384A51BFC225E4ECF46B> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA384A51BFC225E4ECF46B> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA384A51BFC225E4ECF46B> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA38EC51BFC225E4ECF46E> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA38EC51BFC225E4ECF46E> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61FA38EC51BFC225E4ECF46E> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93B2351BFC225E4ECF379> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93B2351BFC225E4ECF379> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F93B2351BFC225E4ECF379> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620630025747C883CA1D2CC6> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620630025747C883CA1D2CC6> <http://purl.org/dc/terms/date> "2021-11-29"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620630025747C883CA1D2CC6> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9434F51BFC225E4ECF3BE> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9434F51BFC225E4ECF3BE> <http://purl.org/dc/terms/date> "2021-12-02"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F9434F51BFC225E4ECF3BE> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94DEA51BFC225E4ECF3FA> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94DEA51BFC225E4ECF3FA> <http://purl.org/dc/terms/date> "2021-12-02"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94DEA51BFC225E4ECF3FA> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94D7E51BFC225E4ECF3EF> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94D7E51BFC225E4ECF3EF> <http://purl.org/dc/terms/date> "2021-12-02"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F94D7E51BFC225E4ECF3EF> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203649251BFC225E4ECF8C3> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203649251BFC225E4ECF8C3> <http://purl.org/dc/terms/date> "2021-12-02"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203649251BFC225E4ECF8C3> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61EFCD721CF2D31D1748D7F6> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61EFCD721CF2D31D1748D7F6> <http://purl.org/dc/terms/date> "2013-03-17"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61EFCD721CF2D31D1748D7F6> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203622F51BFC225E4ECF8C0> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203622F51BFC225E4ECF8C0> <http://purl.org/dc/terms/date> "2021-12-13"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6203622F51BFC225E4ECF8C0> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B0A51BFC225E4ECF2FF> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B0A51BFC225E4ECF2FF> <http://purl.org/dc/terms/date> "2021-12-13"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B0A51BFC225E4ECF2FF> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B8D51BFC225E4ECF307> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B8D51BFC225E4ECF307> <http://purl.org/dc/terms/date> "2021-12-13"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/61F92B8D51BFC225E4ECF307> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A68685747C883CA1D2DA8> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A68685747C883CA1D2DA8> <http://purl.org/dc/terms/date> "2022-01-08"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A68685747C883CA1D2DA8> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A6AE35747C883CA1D2DAC> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A6AE35747C883CA1D2DAC> <http://purl.org/dc/terms/date> "2021-01-08"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620A6AE35747C883CA1D2DAC> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/628635101D2B7BB5B2CB0643> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/628635101D2B7BB5B2CB0643> <http://purl.org/dc/terms/date> "2022-02-03"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/628635101D2B7BB5B2CB0643> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332DC7B72F9F4B33507FC2> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332DC7B72F9F4B33507FC2> <http://purl.org/dc/terms/date> "2022-02-17"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332DC7B72F9F4B33507FC2> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332D0AB72F9F4B33507FBE> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332D0AB72F9F4B33507FBE> <http://purl.org/dc/terms/date> "2022-02-17"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62332D0AB72F9F4B33507FBE> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6243FC267B850F1C3687AB3F> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6243FC267B850F1C3687AB3F> <http://purl.org/dc/terms/date> "2022-02-12"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6243FC267B850F1C3687AB3F> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6256B9048A3D153ADACC03F4> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6256B9048A3D153ADACC03F4> <http://purl.org/dc/terms/date> "2022-02-28"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6256B9048A3D153ADACC03F4> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62C6BE97D7779543F77795DA> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62C6BE97D7779543F77795DA> <http://purl.org/dc/terms/date> "2022-04-15"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62C6BE97D7779543F77795DA> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62D110D6D7779543F777966B> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62D110D6D7779543F777966B> <http://purl.org/dc/terms/date> "2022-04-23"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/62D110D6D7779543F777966B> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/630F1AED2F583C7A1CD0DBC3> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/630F1AED2F583C7A1CD0DBC3> <http://purl.org/dc/terms/date> "2022-06-03"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/630F1AED2F583C7A1CD0DBC3> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633A9EDB036B579F0A26FFC9> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633A9EDB036B579F0A26FFC9> <http://purl.org/dc/terms/date> "2022-06-24"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633A9EDB036B579F0A26FFC9> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633EB3B6036B579F0A270012> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633EB3B6036B579F0A270012> <http://purl.org/dc/terms/date> "2022-06-28"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/633EB3B6036B579F0A270012> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63A2CAC726577078270F82F1> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63A2CAC726577078270F82F1> <http://purl.org/dc/terms/date> "2022-10-10"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63A2CAC726577078270F82F1> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://purl.org/dc/terms/date> "2022-08-20"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63BBFE764E1F899807CFF9BD> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63BBFE764E1F899807CFF9BD> <http://purl.org/dc/terms/date> "2022-11-23"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63BBFE764E1F899807CFF9BD> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63C512F34E1F899807CFFB75> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63C512F34E1F899807CFFB75> <http://purl.org/dc/terms/date> "2022-11-18"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63C512F34E1F899807CFFB75> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63D3E96E5410CAD909EF6D10> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63D3E96E5410CAD909EF6D10> <http://purl.org/dc/terms/date> "2022-12-06"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63D3E96E5410CAD909EF6D10> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63FF1583886F92ABFC08D0E6> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63FF1583886F92ABFC08D0E6> <http://purl.org/dc/terms/date> "2022-12-16"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63FF1583886F92ABFC08D0E6> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345E71C2DE4F40F38C0B1> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345E71C2DE4F40F38C0B1> <http://purl.org/dc/terms/date> "2023-01-04"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345E71C2DE4F40F38C0B1> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345051C2DE4F40F38C0A9> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345051C2DE4F40F38C0A9> <http://purl.org/dc/terms/date> "2023-01-04"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/63F345051C2DE4F40F38C0A9> <http://purl.org/dc/terms/date> ?date 
  }
}
;

DELETE{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/642D68BEE025A7C706F41E58> <http://purl.org/dc/terms/date> ?date
  }
}
INSERT{
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/642D68BEE025A7C706F41E58> <http://purl.org/dc/terms/date> "2023-04-05"
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/administrative-unit>
  }
  GRAPH ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/642D68BEE025A7C706F41E58> <http://purl.org/dc/terms/date> ?date 
  }
}
;
