DELETE {
  GRAPH ?g {
    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type  ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid . 
  }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/administrative-unit>
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/public>
    <http://mu.semte.ch/graphs/privacy-centric-graph>
    <http://mu.semte.ch/graphs/worship-privacy-centric-graph>
  }
  GRAPH ?g {
    ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type  ;
      <http://mu.semte.ch/vocabularies/core/uuid> ?uuid .

    FILTER NOT EXISTS {
      FILTER (?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
      FILTER (?p != <http://mu.semte.ch/vocabularies/core/uuid>)
      ?s ?p ?o .
    }
  }
}
