DELETE {
  GRAPH ?g {
    <http://lblod.data.gift/concepts/fbec5e94aba343b0a7361aca8a0c7d79> ?a ?b.
  }
}
WHERE {
  GRAPH ?g {
    <http://lblod.data.gift/concepts/fbec5e94aba343b0a7361aca8a0c7d79> ?a ?b.
  }
}