PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
   <http://data.lblod.info/id/representatieveOrganen/45a0c64b0f2ee4ac0fa8c151e6f2209c> a ere:RepresentatiefOrgaan ;
         ere:typeEredienst <http://lblod.data.gift/concepts/cbd4c767ea184b41bf51b65d406754d4>
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
   <http://data.lblod.info/id/representatieveOrganen/5871503aa86b44cd470f97228a2ce413> a ere:RepresentatiefOrgaan ;
         ere:typeEredienst <http://lblod.data.gift/concepts/f076c85e72814278814776b038ac33f7>
  }
}