DELETE {
  GRAPH ?g {
    ?org ?orgP ?orgO .
  }
}
WHERE {
  VALUES ?org {
    <http://data.lblod.info/id/bestuurseenheden/6584318A90264E79DCA99E67>
    <http://data.lblod.info/id/bestuurseenheden/658432DF90264E79DCA99E69>
    <http://data.lblod.info/id/bestuurseenheden/6584351590264E79DCA99E6B>
    <http://data.lblod.info/id/bestuurseenheden/6584361290264E79DCA99E70>
    <http://data.lblod.info/id/bestuurseenheden/6584395890264E79DCA99E73>
    <http://data.lblod.info/id/bestuurseenheden/6584396790264E79DCA99E76>
    <http://data.lblod.info/id/bestuurseenheden/65843A8090264E79DCA99E79>
    <http://data.lblod.info/id/bestuurseenheden/65843B0090264E79DCA99E7B>
    <http://data.lblod.info/id/bestuurseenheden/65CD2F939E3C83CF14AEEC59>
  }

  GRAPH ?g {
    ?org ?orgP ?orgO .
  }
}
