PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a7164f51e0e68820b9d2d4d53aaf48f9> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a7164f51e0e68820b9d2d4d53aaf48f9> regorg:legalName """Anglicaanse Kerkfabriek Saint John""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a7164f51e0e68820b9d2d4d53aaf48f9> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a57ce399c9020f6f1a3f976c2510976e> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a57ce399c9020f6f1a3f976c2510976e> regorg:legalName """Anglicaanse Kerkfabriek Sint-Bonifacius""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a57ce399c9020f6f1a3f976c2510976e> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/cb69c277a4021bf71a8c7cacc22bd9bc> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/cb69c277a4021bf71a8c7cacc22bd9bc> regorg:legalName """Anglicaanse Kerkfabriek te Oostende""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/cb69c277a4021bf71a8c7cacc22bd9bc> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a596850e9aa27969a25f73137d300306> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a596850e9aa27969a25f73137d300306> regorg:legalName """The Anglican Chaplaincy of Saint Paul's Church""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a596850e9aa27969a25f73137d300306> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/42adfc9a7b2cfa0e6ead719da03406b5> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/42adfc9a7b2cfa0e6ead719da03406b5> regorg:legalName """Anglicaanse Kerkfabriek Saint George""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/42adfc9a7b2cfa0e6ead719da03406b5> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/46b8da1347c6bcab415ad53a1b94da26> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/46b8da1347c6bcab415ad53a1b94da26> regorg:legalName """Anglicaanse Kerkfabriek Saint George te Knokke""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/46b8da1347c6bcab415ad53a1b94da26> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2eea8a352821c9c1f1827f1cfde9f24> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2eea8a352821c9c1f1827f1cfde9f24> regorg:legalName """Anglicaanse Kerkfabriek Saint Martha and Mary's""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2eea8a352821c9c1f1827f1cfde9f24> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/24ff08070bc1e47b498ab8139b9d3792> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/24ff08070bc1e47b498ab8139b9d3792> regorg:legalName """Heusden-Zolder Selimiye Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/24ff08070bc1e47b498ab8139b9d3792> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7b0d877894765abf5052e12c7bed553e> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7b0d877894765abf5052e12c7bed553e> regorg:legalName """Beraat""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7b0d877894765abf5052e12c7bed553e> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8faa182c59167da7551f40979dc5022> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8faa182c59167da7551f40979dc5022> regorg:legalName """Yavuz Sultan Selim""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8faa182c59167da7551f40979dc5022> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/db46915e77fbf8f083e9861c802b2b13> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/db46915e77fbf8f083e9861c802b2b13> regorg:legalName """Mehmet Akif""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/db46915e77fbf8f083e9861c802b2b13> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/4fd6da5f1e1ea6e60f611abc4df28456> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/4fd6da5f1e1ea6e60f611abc4df28456> regorg:legalName """Culturele en Islamitische Vereniging Badr""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/4fd6da5f1e1ea6e60f611abc4df28456> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/619a5721094b28807dca8d04de69e3e0> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/619a5721094b28807dca8d04de69e3e0> regorg:legalName """Yunus Emre""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/619a5721094b28807dca8d04de69e3e0> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7e3fb673922f9495c48251f316c5c4ff> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7e3fb673922f9495c48251f316c5c4ff> regorg:legalName """Yesil Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7e3fb673922f9495c48251f316c5c4ff> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/adeaab8a02815bf2c5816165a45ad4c5> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/adeaab8a02815bf2c5816165a45ad4c5> regorg:legalName """Sultan Ahmet""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/adeaab8a02815bf2c5816165a45ad4c5> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c1c334a2cc56ac501badce5e879aec65> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c1c334a2cc56ac501badce5e879aec65> regorg:legalName """Hicret Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c1c334a2cc56ac501badce5e879aec65> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c7d6827eb88cd977146e72583461071b> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c7d6827eb88cd977146e72583461071b> regorg:legalName """Ensar""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c7d6827eb88cd977146e72583461071b> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ca0daee18a29e187017bf236e26f1ec2> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ca0daee18a29e187017bf236e26f1ec2> regorg:legalName """Marokkaanse Islamitische en Culturele Vereniging Winterslag Hassan Ebno Tabit""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ca0daee18a29e187017bf236e26f1ec2> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f95b761af55091b491fd62bd6bed11dc> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f95b761af55091b491fd62bd6bed11dc> regorg:legalName """Al Ihsaan""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f95b761af55091b491fd62bd6bed11dc> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b540096ac8be2c9c72dafd59e61080c5> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b540096ac8be2c9c72dafd59e61080c5> regorg:legalName """Tevhid Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b540096ac8be2c9c72dafd59e61080c5> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/0f2a4604a962926d67518bb3846af1c9> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/0f2a4604a962926d67518bb3846af1c9> regorg:legalName """Yildirim Beyazit Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/0f2a4604a962926d67518bb3846af1c9> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58d6bea16bd86c7df65caa9625af97aa> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58d6bea16bd86c7df65caa9625af97aa> regorg:legalName """Mevlana Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58d6bea16bd86c7df65caa9625af97aa> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a6e0531c6c4b5885552604163cfabfbc> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a6e0531c6c4b5885552604163cfabfbc> regorg:legalName """Selimiye Camii""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a6e0531c6c4b5885552604163cfabfbc> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8880f3d8b482788c5f3adbf58f01b4f> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8880f3d8b482788c5f3adbf58f01b4f> regorg:legalName """Al Mouhsinine""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8880f3d8b482788c5f3adbf58f01b4f> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ef77bb3094fdc4a7ed7e09551500acfe> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ef77bb3094fdc4a7ed7e09551500acfe> regorg:legalName """Attaqwa""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ef77bb3094fdc4a7ed7e09551500acfe> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/8c46fc84fb7a11cca44bde007a0c081c> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/8c46fc84fb7a11cca44bde007a0c081c> regorg:legalName """Innerlijke Vrede""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/8c46fc84fb7a11cca44bde007a0c081c> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/928335b5a7b1cb7850c7cc98574e9ec9> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/928335b5a7b1cb7850c7cc98574e9ec9> regorg:legalName """Fatih Moskee""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/928335b5a7b1cb7850c7cc98574e9ec9> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/934cb872a84a86ceb9a9e10abb1d08fa> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/934cb872a84a86ceb9a9e10abb1d08fa> regorg:legalName """Barmhartig""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/934cb872a84a86ceb9a9e10abb1d08fa> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/fd4ae252fffca29852354b12ef37b086> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/fd4ae252fffca29852354b12ef37b086> regorg:legalName """Assounah""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/fd4ae252fffca29852354b12ef37b086> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8d9f1a45c11c6761306bdf680349593> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8d9f1a45c11c6761306bdf680349593> regorg:legalName """Ensarija""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a8d9f1a45c11c6761306bdf680349593> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62B968EDD7779543F777954A> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62B968EDD7779543F777954A> regorg:legalName """Tauhid""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62B968EDD7779543F777954A> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C427EBD7779543F777959E> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C427EBD7779543F777959E> regorg:legalName """El Mouslimine""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C427EBD7779543F777959E> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/104a6b6eabd0192afdeb70d3b517aef1> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/104a6b6eabd0192afdeb70d3b517aef1> regorg:legalName """Kevser Moskee""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/104a6b6eabd0192afdeb70d3b517aef1> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b798c1a0e56ace342d225a503dcc384c> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b798c1a0e56ace342d225a503dcc384c> regorg:legalName """Moeder Gods, Troosteres der Bedroefden""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/b798c1a0e56ace342d225a503dcc384c> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6c16ba36223ff4e2dd0e76036a0b0d50> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6c16ba36223ff4e2dd0e76036a0b0d50> regorg:legalName """Heilige Barbara""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6c16ba36223ff4e2dd0e76036a0b0d50> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/9daaa2917a374a55e3d8ba100bf329e5> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/9daaa2917a374a55e3d8ba100bf329e5> regorg:legalName """Heilige Dimitrios""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/9daaa2917a374a55e3d8ba100bf329e5> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e0e7121368dfc45d9a809a1a36b65e32> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e0e7121368dfc45d9a809a1a36b65e32> regorg:legalName """Heiligen Konstantijn en Helena""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e0e7121368dfc45d9a809a1a36b65e32> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/eecb5159c45e6e9fa263d6d697f3b446> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/eecb5159c45e6e9fa263d6d697f3b446> regorg:legalName """Heilige Amandus""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/eecb5159c45e6e9fa263d6d697f3b446> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/064d0956f36a54c27e9d93828a34f538> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/064d0956f36a54c27e9d93828a34f538> regorg:legalName """Maria Boodschap""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/064d0956f36a54c27e9d93828a34f538> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1808db0b0ef2934850e3dde50db08f6b> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1808db0b0ef2934850e3dde50db08f6b> regorg:legalName """Heilige Nectarios""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1808db0b0ef2934850e3dde50db08f6b> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/39090eb31b28e111e47e75dc38eaff42> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/39090eb31b28e111e47e75dc38eaff42> regorg:legalName """De Geboorte van Moeder Gods""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/39090eb31b28e111e47e75dc38eaff42> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bb00c66671c9bf05025876eb749d2a02> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bb00c66671c9bf05025876eb749d2a02> regorg:legalName """Heilige Apostel Andreas""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bb00c66671c9bf05025876eb749d2a02> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c821b81409bd4c56b8eb9e32ce09a841> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c821b81409bd4c56b8eb9e32ce09a841> regorg:legalName """Oekraïns-orthodoxe parochie""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c821b81409bd4c56b8eb9e32ce09a841> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c85d82dfc9fcf2ab5857bb9891a6c447> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c85d82dfc9fcf2ab5857bb9891a6c447> regorg:legalName """Orthodoxe parochie Heilige Apostel en Evangelist Mattheos""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c85d82dfc9fcf2ab5857bb9891a6c447> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6b860cbdc90a8952bdd14b707817225e> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6b860cbdc90a8952bdd14b707817225e> regorg:legalName """HH. Kyrillos en Methodios""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/6b860cbdc90a8952bdd14b707817225e> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a76be3cc51350736372b1cb61f5a8245> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a76be3cc51350736372b1cb61f5a8245> regorg:legalName """HH. Drie Hiërarchen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/a76be3cc51350736372b1cb61f5a8245> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bba84f42c09cd7c8b2e5a9829a820cf5> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bba84f42c09cd7c8b2e5a9829a820cf5> regorg:legalName """Heilige Johannes de Theoloog""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/bba84f42c09cd7c8b2e5a9829a820cf5> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/43fb31ca870d9c3ea47d02f153c8be6f> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/43fb31ca870d9c3ea47d02f153c8be6f> regorg:legalName """Heilige Apostel Andreas en Heilige Materne""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/43fb31ca870d9c3ea47d02f153c8be6f> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C40176D7779543F7779593> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C40176D7779543F7779593> regorg:legalName """Orthodoxe Parochie Heiligen Georgios en Alena""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C40176D7779543F7779593> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C584C5D7779543F77795CA> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C584C5D7779543F77795CA> regorg:legalName """Orthodoxe Parochie H. Georgios Turnhout""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C584C5D7779543F77795CA> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ccc351e0430689ca49e09d77cd074a5d> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ccc351e0430689ca49e09d77cd074a5d> regorg:legalName """Christus' Geboorte""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/ccc351e0430689ca49e09d77cd074a5d> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/20667054581bba972a5968d2d47b5ed4> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/20667054581bba972a5968d2d47b5ed4> regorg:legalName """Christelijk Gereformeerde kerk""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/20667054581bba972a5968d2d47b5ed4> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/580873b83ab874b95711ec2db3ca1717> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/580873b83ab874b95711ec2db3ca1717> regorg:legalName """Christengemeente Ichtus""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/580873b83ab874b95711ec2db3ca1717> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2f5b8e0224b1af556165508195ccb76> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2f5b8e0224b1af556165508195ccb76> regorg:legalName """Evangelische Christengemeente Houthalen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e2f5b8e0224b1af556165508195ccb76> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1b8737e8a8870c5edaee0f9edf72a881> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1b8737e8a8870c5edaee0f9edf72a881> regorg:legalName """Evangelische Christengemeente Berchem""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1b8737e8a8870c5edaee0f9edf72a881> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1ddd00f077b747579a58189a2151c05c> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1ddd00f077b747579a58189a2151c05c> regorg:legalName """Philadelphia""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/1ddd00f077b747579a58189a2151c05c> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/25364ce478850ac57891a6ea8b4125d6> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/25364ce478850ac57891a6ea8b4125d6> regorg:legalName """Deutschsprachige Evangelische Gemeinde Provinz Antwerpen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/25364ce478850ac57891a6ea8b4125d6> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58dfa349109d8725d9b7fb54adfed721> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58dfa349109d8725d9b7fb54adfed721> regorg:legalName """Evangelische Kerk Leuven""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/58dfa349109d8725d9b7fb54adfed721> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/77fd7b2aeb6bcb3f7d80db6e25a98e41> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/77fd7b2aeb6bcb3f7d80db6e25a98e41> regorg:legalName """De Shelter""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/77fd7b2aeb6bcb3f7d80db6e25a98e41> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7a705f8e2b9cf99d192cd1b1619b3e42> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7a705f8e2b9cf99d192cd1b1619b3e42> regorg:legalName """Pinkstergemeente De Kruispoort""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/7a705f8e2b9cf99d192cd1b1619b3e42> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c2740896a4a3c80c7967ddca52887829> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c2740896a4a3c80c7967ddca52887829> regorg:legalName """De Hoeksteen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c2740896a4a3c80c7967ddca52887829> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e046f7d370958c8822e2bfa241851774> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e046f7d370958c8822e2bfa241851774> regorg:legalName """Bethel""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e046f7d370958c8822e2bfa241851774> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f0acc5869aa714bf445fb29fc0d26c1b> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f0acc5869aa714bf445fb29fc0d26c1b> regorg:legalName """Evangelische Christengemeente Beringen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f0acc5869aa714bf445fb29fc0d26c1b> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/110aa9cc86de3760f583a9c31b5add39> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/110aa9cc86de3760f583a9c31b5add39> regorg:legalName """Evangelische kerk Bourgoyen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/110aa9cc86de3760f583a9c31b5add39> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/44329be9ac7054b39adbc583b6203ba2> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/44329be9ac7054b39adbc583b6203ba2> regorg:legalName """Christengemeente Emmanuel""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/44329be9ac7054b39adbc583b6203ba2> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/be87d5a9a250eee7232772dc99401b86> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/be87d5a9a250eee7232772dc99401b86> regorg:legalName """Vrije evangelische Gemeente De Burg""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/be87d5a9a250eee7232772dc99401b86> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c13018155cfdffc26169eae78f1a300d> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c13018155cfdffc26169eae78f1a300d> regorg:legalName """Evangelische gemeente Paulus""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/c13018155cfdffc26169eae78f1a300d> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e004568673ac1db1cb3d9c158c520a48> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e004568673ac1db1cb3d9c158c520a48> regorg:legalName """Gereformeerd Kerkcentrum Kerk aan de Leie""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/e004568673ac1db1cb3d9c158c520a48> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/622EFE7FB72F9F4B33507E89> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/622EFE7FB72F9F4B33507E89> regorg:legalName """Evangelische Kerk Bilzen""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/622EFE7FB72F9F4B33507E89> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C550A8D7779543F77795BF> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C550A8D7779543F77795BF> regorg:legalName """Evangelische Gemeente de Pottenbakker""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/62C550A8D7779543F77795BF> regorg:legalName ?existingLegalName .
  }
}
;
DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f99035f2eca9a50996e719c445d2cfd2> regorg:legalName ?existingLegalName .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f99035f2eca9a50996e719c445d2cfd2> regorg:legalName """Evangelische Kerk Kortrijk Wijkkerk Mariadorp""" .
  }
} WHERE {
   GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/besturenVanDeEredienst/f99035f2eca9a50996e719c445d2cfd2> regorg:legalName ?existingLegalName .
  }
}
