INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/52cc9d8d-1c9a-4d92-9936-da9d4a622ec4>
      <http://www.w3.org/2004/02/skos/core#prefLabel>  "Agentschap Binnenlands Bestuur" ;
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://www.w3.org/2004/02/skos/core#Concept> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf>  <http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode> ;
      <http://mu.semte.ch/vocabularies/core/uuid>  "52cc9d8d-1c9a-4d92-9936-da9d4a622ec4" ;
      <http://www.w3.org/2004/02/skos/core#inScheme>  <http://data.vlaanderen.be/id/conceptscheme/BestuurseenheidClassificatieCode>.

     <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/52cc9d8d-1c9a-4d92-9936-da9d4a622ec4>.
  }
}