PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX session: <http://mu.semte.ch/vocabularies/session/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org: <http://www.w3.org/ns/org>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
      ?s ?p ?o
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?s ?p ?o
  }
}

WHERE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    ?s a ?type; ?p ?o.
    
    filter (?type in (
       <https://data.vlaanderen.be/ns/persoon#Geboorte>,
                        <http://www.w3.org/ns/prov#Location>,
                        <http://www.w3.org/ns/org#Site>,
                        <http://www.w3.org/ns/locn#Address>,
                        <http://schema.org/ContactPoint>,
                        <http://xmlns.com/foaf/0.1/Image>,
                        <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject>
    ))

  }
}
;

DELETE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>;
    mu:uuid ?uuid;
    <http://www.w3.org/ns/org#classification> ?classification;
    skos:prefLabel ?name.


  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>;
        mu:uuid ?uuid;
    <http://www.w3.org/ns/org#classification> ?classification;
    skos:prefLabel ?name.

  }
}

WHERE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    ?s a <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>; 
    <http://www.w3.org/ns/org#classification> ?classification;
        mu:uuid ?uuid;
    skos:prefLabel ?name.

    filter(?classification in (
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000000>,
    <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>
    ))
    

  }
}
