INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/e84a58df-37f5-4b2b-bc0c-00f4658e87da>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e84a58df-37f5-4b2b-bc0c-00f4658e87da" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Vorst" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21007> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025818>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b5f7fbe1-72b0-4908-aee1-716d0c2116c2" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Vorst" ;
      <http://www.w3.org/ns/regorg#legalName> "Vorst" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025818>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/e84a58df-37f5-4b2b-bc0c-00f4658e87da> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/0254289b-a981-4016-a47b-e094da4230b5> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/b02f2258-d89b-4d5f-9052-49fe79deb395> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/41104d5e-5eea-47d3-aba3-680737890023> ;
      <http://purl.org/dc/terms/source> <https://data.vlaanderen.be/doc/organisatie> .

    <http://data.lblod.info/id/identificatoren/0254289b-a981-4016-a47b-e094da4230b5>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/65471c13-b9df-4cf4-9cff-38948521413b>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "0254289b-a981-4016-a47b-e094da4230b5" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/65471c13-b9df-4cf4-9cff-38948521413b>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207367489" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "65471c13-b9df-4cf4-9cff-38948521413b" .

    <http://data.lblod.info/id/identificatoren/b02f2258-d89b-4d5f-9052-49fe79deb395>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/b6827353-40ab-4b75-b60a-b705f5917f86>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b02f2258-d89b-4d5f-9052-49fe79deb395" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/b6827353-40ab-4b75-b60a-b705f5917f86>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025818" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b6827353-40ab-4b75-b60a-b705f5917f86" .

    <http://data.lblod.info/id/vestigingen/41104d5e-5eea-47d3-aba3-680737890023>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "41104d5e-5eea-47d3-aba3-680737890023" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/629515a1-4afd-4b5c-96f5-b6a25aba8034> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/72d4d8b8-70a6-428b-8a4e-1ab6039fca94> .

    <http://data.lblod.info/id/contact-punten/629515a1-4afd-4b5c-96f5-b6a25aba8034>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "629515a1-4afd-4b5c-96f5-b6a25aba8034" ;
      <http://schema.org/email> "contact@vorst.brussels" ;
      <http://schema.org/telephone> "tel:+3223702211" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://vorst.brussels/" .

    <http://data.lblod.info/id/adressen/72d4d8b8-70a6-428b-8a4e-1ab6039fca94>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "72d4d8b8-70a6-428b-8a4e-1ab6039fca94" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Vorst" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2" ;
      <http://www.w3.org/ns/locn#fullAddress> "Pastoorsstraat 2, 1190 Vorst, België" ;
      <http://www.w3.org/ns/locn#postCode> "1190" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Pastoorsstraat" .
  }
}