INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/cd00668d-9233-4108-b690-f70e2f2e28a0>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "cd00668d-9233-4108-b690-f70e2f2e28a0" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Evere" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21006> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025863>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "56c4b098-45e7-4115-b2f7-a56f8fb9a1e0" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Evere" ;
      <http://www.w3.org/ns/regorg#legalName> "Evere" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025863>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/cd00668d-9233-4108-b690-f70e2f2e28a0> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/ecb0f120-36b3-492c-b20e-8009fa8e4828> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/80edaf56-2f42-451d-aa7f-473450386b67> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/9080f879-d78d-47fc-b083-8912fb31474e> ;
      <http://purl.org/dc/terms/source> <https://data.vlaanderen.be/doc/organisatie> .

    <http://data.lblod.info/id/identificatoren/ecb0f120-36b3-492c-b20e-8009fa8e4828>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/cc8deba0-3d7c-4ecc-96b0-9aea331d5bda>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "ecb0f120-36b3-492c-b20e-8009fa8e4828" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/cc8deba0-3d7c-4ecc-96b0-9aea331d5bda>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207365709" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "cc8deba0-3d7c-4ecc-96b0-9aea331d5bda" .

    <http://data.lblod.info/id/identificatoren/80edaf56-2f42-451d-aa7f-473450386b67>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/248e8391-e2dc-4b4b-a687-8c839376495f>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "80edaf56-2f42-451d-aa7f-473450386b67" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/248e8391-e2dc-4b4b-a687-8c839376495f>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025863" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "248e8391-e2dc-4b4b-a687-8c839376495f" .

    <http://data.lblod.info/id/vestigingen/9080f879-d78d-47fc-b083-8912fb31474e>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9080f879-d78d-47fc-b083-8912fb31474e" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/e6255d3e-e826-4b82-87cf-52cc1d72b090> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/6f1c3769-098a-4640-be42-cdfb55a422b6> .

    <http://data.lblod.info/id/contact-punten/e6255d3e-e826-4b82-87cf-52cc1d72b090>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e6255d3e-e826-4b82-87cf-52cc1d72b090" ;
      <http://schema.org/email> "evere@brutele.be" ;
      <http://schema.org/telephone> "tel:+3222476262" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://evere.brussels/" .

    <http://data.lblod.info/id/adressen/6f1c3769-098a-4640-be42-cdfb55a422b6>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6f1c3769-098a-4640-be42-cdfb55a422b6" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Evere" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10" ;
      <http://www.w3.org/ns/locn#fullAddress> "S. Hoedemaekerssquare 10, 1140 Evere, België" ;
      <http://www.w3.org/ns/locn#postCode> "1140" ;
      <http://www.w3.org/ns/locn#thoroughfare> "S. Hoedemaekerssquare" .
  }
}