INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/aaec0a10-8bb9-4644-8be5-89da0920dbed>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "aaec0a10-8bb9-4644-8be5-89da0920dbed" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Schaarbeek" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21015> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025820>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "1a5177fd-6068-4640-ab8c-6454400033d8" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Schaarbeek" ;
      <http://www.w3.org/ns/regorg#legalName> "Schaarbeek" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025820>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/aaec0a10-8bb9-4644-8be5-89da0920dbed> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/d9ea7d1d-87f3-4178-856c-265a95acbc91> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/14e75d82-eff1-49fc-a753-cb96420f8c8a> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/be200efc-8399-4cd6-a913-d64a239bce78> ;
      <http://purl.org/dc/terms/source> <https://data.vlaanderen.be/doc/organisatie> .

    <http://data.lblod.info/id/identificatoren/d9ea7d1d-87f3-4178-856c-265a95acbc91>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/e9479cf1-e50e-4761-8128-b8992216263f>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "d9ea7d1d-87f3-4178-856c-265a95acbc91" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/e9479cf1-e50e-4761-8128-b8992216263f>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207367687" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e9479cf1-e50e-4761-8128-b8992216263f" .

    <http://data.lblod.info/id/identificatoren/14e75d82-eff1-49fc-a753-cb96420f8c8a>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/6c6f25f4-0ecc-4280-93b5-b6afb2cee605>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "14e75d82-eff1-49fc-a753-cb96420f8c8a" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/6c6f25f4-0ecc-4280-93b5-b6afb2cee605>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025820" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6c6f25f4-0ecc-4280-93b5-b6afb2cee605" .

    <http://data.lblod.info/id/vestigingen/be200efc-8399-4cd6-a913-d64a239bce78>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "be200efc-8399-4cd6-a913-d64a239bce78" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/968afe2c-70b9-4d7a-8ca1-5f6c36575ddd> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/9dffbe51-9a41-4f98-80e5-33b76b76b586> .

    <http://data.lblod.info/id/contact-punten/968afe2c-70b9-4d7a-8ca1-5f6c36575ddd>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "968afe2c-70b9-4d7a-8ca1-5f6c36575ddd" ;
      <http://schema.org/email> "info@1030.be" ;
      <http://schema.org/telephone> "tel:+3222447511" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.1030.be/" .

    <http://data.lblod.info/id/adressen/9dffbe51-9a41-4f98-80e5-33b76b76b586>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9dffbe51-9a41-4f98-80e5-33b76b76b586" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Schaarbeek" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "100" ;
      <http://www.w3.org/ns/locn#fullAddress> "Colignonplein 100, 1030 Schaarbeek, België" ;
      <http://www.w3.org/ns/locn#postCode> "1030" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Colignonplein" .
  }
}