  DELETE {
    GRAPH  <http://mu.semte.ch/application> {
      ?s ?p ?o .
    }
  } INSERT {
    GRAPH  <http://mu.semte.ch/graphs/contacthub/141d9d6b-54af-4d17-b313-8d1c30bc3f5b/ChAdmin> {
      ?s ?p ?o .
    }
  } WHERE {
    GRAPH  <http://mu.semte.ch/application> {
      ?s a ?type ; ?p ?o .
      VALUES ?type {
          <http://www.w3.org/ns/org#Organization>
          <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid>
          <http://data.lblod.info/vocabularies/erediensten/BestuurVanDeEredienst>
          <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>
          <http://data.lblod.info/vocabularies/erediensten/Eredienstbestuursorgaan>
          <http://www.w3.org/ns/adms#Identifier>
          <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator>
          <http://www.w3.org/ns/org#ChangeEvent>
          <http://data.lblod.info/vocabularies/erediensten/BetrokkenLokaleBesturen>
          <http://www.w3.org/ns/prov#Location>
          <http://www.w3.org/ns/org#Site>
          <http://www.w3.org/ns/locn#Address>                          
          <http://www.w3.org/ns/person#Person>
          <http://data.vlaanderen.be/ns/mandaat#Mandaat>
          <http://data.vlaanderen.be/ns/mandaat#Mandataris>
          <http://data.lblod.info/vocabularies/erediensten/EredienstMandataris>
          <http://schema.org/ContactPoint>                          
          <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie>
          <http://data.lblod.info/vocabularies/erediensten/CentraalBestuurVanDeEredienst>
          <http://data.lblod.info/vocabularies/erediensten/CentraleBestuursorgaan>
          <http://data.lblod.info/vocabularies/erediensten/RepresentatiefOrgaan>                          
          <http://www.w3.org/ns/org#Role>
          <http://www.w3.org/ns/org#Post>
          <http://data.lblod.info/vocabularies/contacthub/AgentInPositie>
          <http://lblod.data.gift/vocabularies/organisatie/OrganisatieStatusCode>
          <http://lblod.data.gift/vocabularies/organisatie/BestuursfunctieCode>
          <http://lblod.data.gift/vocabularies/organisatie/BestuursorgaanClassificatieCode>
          <http://lblod.data.gift/vocabularies/organisatie/TypeEredienst>
          <http://lblod.data.gift/vocabularies/organisatie/HelftVerkiezing>
          <http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis>
          <http://lblod.data.gift/vocabularies/organisatie/MandatarisStatusCode>
          <http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode>
          <http://lblod.data.gift/vocabularies/organisatie/TypeBetrokkenheid>
          <http://www.w3.org/2004/02/skos/core#ConceptScheme>
          <http://www.w3.org/2004/02/skos/core#Concept>
          <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject>
          <http://xmlns.com/foaf/0.1/Image>
      }
    }
  }