PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


DELETE {
    GRAPH ?g {
      ?bestuurseenheid rdfs:label ?label .
    }
} INSERT {
    GRAPH ?g {
      ?bestuurseenheid skos:prefLabel ?label .
    }
} WHERE {
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid ;
            rdfs:label ?label .
  }
}


