DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/41c41a1aca62f09bdb57dc93cc83af49> ?p ?o.
  }
}

;

DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/bestuurseenheden/25fc615f81f2032ee7126108474e842b418c890c3755f9e1efc58ac6dc59d1fc> <http://data.lblod.info/vocabularies/erediensten/betrokkenBestuur> <http://data.lblod.info/id/betrokkenLokaleBesturen/41c41a1aca62f09bdb57dc93cc83af49>.
  }
}

;

DELETE {
  GRAPH ?g {
      ?localInvolvementKapellen <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
  }
}
INSERT {
  GRAPH ?g {
    ?localInvolvementKapellen <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> 100.
  }
}
WHERE {
  BIND(<http://mu.semte.ch/graphs/worship-service> AS ?g)
  GRAPH ?g {
    ?localInvolvementKapellen <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
  }
  VALUES ?localInvolvementKapellen {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/f7450dc34b53dd33b17e0b231470e64c>
  }
}
