DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/ce6a7228a87e079fbb7b0e7a018af176> ?p ?o.
  }
}

;

DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/bestuurseenheden/7d457bc3985fbb70ba748c121043c89d498a3926e8c59ffdf9438c2896791248> <http://data.lblod.info/vocabularies/erediensten/betrokkenBestuur> <http://data.lblod.info/id/betrokkenLokaleBesturen/ce6a7228a87e079fbb7b0e7a018af176>.
  }
}

;

DELETE {
  GRAPH ?g {
      ?localInvolvementKalmthout <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
  }
}
INSERT {
  GRAPH ?g {
    ?localInvolvementKalmthout <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> 100.
  }
}
WHERE {
  BIND(<http://mu.semte.ch/graphs/worship-service> AS ?g)
  GRAPH ?g {
    ?localInvolvementKalmthout <http://data.lblod.info/vocabularies/erediensten/financieringspercentage> ?percentage.
  }
  VALUES ?localInvolvementKalmthout {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/3cec37859c0504f26edf0cbc505a1b1d>
  }
}
