PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Westhoek" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "c74e71fb4ccf2e143731873471a890b87076a9b1dcc470b937b339d7c191fce4" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Antwerpen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "c8d171d9735146131fcb9e2ad7f4e271585b0bf68f7a43d8873b6848576d13a1" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Centrum" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "4bb83a0635b69132a4de91667c0a30f228720bda01584b3a01c4cf7ddfc12664" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Kempen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "215d1409dda860a1ce4f39f1f6c082c5662620d9d29de456f4242fb6cc6df0b5" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Midwest" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b312420a9e4331da36afd70237db5061825cacadcdaa68e6ad0f1ea8a9426f77" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Oost-Limburg" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "7800a6f5e9c3f646e274b280703730ed5e83fe0cba1f0d6c7fb18141337fe781" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Rand" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "2d25be1712e809bbeed7d439c93bace752e0742f6b2ed9802302dec9a8906e2a" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Brandweer Zone Vlaams-Brabant West" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b3e202bf5ab9d30f1928f7a1ea8911c60da595819774702eb1745e83c25cf106" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Fluvia" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "9d0e3fc23f4fb9c23cbcc30474a1e518c9725c069255090d46eb58c13d62baef" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Meetjesland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "0e951dd15341d38413bf809f16ef5f1bd163092001ac04ce78a4de5b5e9cdd37" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Noord-Limburg" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "505e727b7b078c3eb9a05f754d834fca559d28cb3cdb02d5e4cdb3be300ea699" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Oost" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "db299add14cc24e7a99ce4eb51015f32925690fb9816962e500f3341842ef6fa" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Oost-Vlaams-Brabant" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "9fdf19f0cfc9e12bd58fc10c4da6e8c6c40e813ec5b9f3bdde92cb00ecd972fe" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Rivierenland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "98967d1e1e3dd66ac9e32bd1d536ee8e85c9126cc5fc04354a335d5aabcf9b01" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Taxandria" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "c1fcc0a6c6132cb34dff9ed6e6f361d1587c211ac8ec1ddef409510bf68b724b" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Vlaamse Ardennen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "bfc36f138e0c7d11757eb321d034cfbffce281679eae93c2bc5df1048aa05789" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Waasland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "e8bd746e2dc3c5a72fe4fb3da0c92803b0728150bdd66e860d6218bc83098941" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Zone 1" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "2c1fc56876479e83c7b144e98b84174dd10087ae59621204b9d6701d968e8aba" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Zuid-Oost" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "db5adb1e2e7ad0e33725b83edda44f9b4638e328a1534a1b4eef2683d337975a" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "HVZ Zuid-West-Limburg" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "a3b32431cfbb18905e2c7deeaf9ef7af35cd17c55d053a05ed9cd8fdec550724" .
  }
}
