PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5408 AMOW" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "90688b32e0808b6ebbb7b36030526750236527e8019414449065f57ea384ce71" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5462 ARRO IEPER" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "195d911f1417b20a4b715b1a54e8ae6e92b9a23cde908f2fb03a0081910d8fce" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5359 BoDuKaP" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "f4838c2bb548a35f92a6ddcf725676b9f137f3fcb11e6737caa7cab1f1314e27" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5399 BRT" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "81083789b63917e32ab90ef1a45adf893f370ee38da2e0542e5c035db4f60794" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5426 Brakel" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b7af3483cb5d0021c6f5864a433b211fce30246ef685621d104b1951915c21c4" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5909 CARMA" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "e7692f99-9a36-43e3-af78-b320390318dc" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5396 Demerdal-DSZ" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "41e3bb71cb1fe2763a64ce47ee758fbeb532fbd4348281f34a86a5f88dd71980" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5402 Druivenstreek" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b5aee7f43fc9c5d0df74e2cbb9214c03c425cf026b1fd77dd1e3b08e5fc7f875" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5458 Gavers" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "479036ca47b011e16fefafbe4d3512a44c564804dc26d331ce4dcbe0fa3366d2" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5910 Getevallei" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "81334af3-1b6f-4308-aca3-107121462d56" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5350 GRENS" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "4ffd00c0ba7ceab20db24832a4b9963112ed66914dcca05f3e5dc8b8b9d4479d" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5455 Grensleie" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "e39d8bf95a03ade08ef25a79ebc050abfc81a69731f1de66fe6d031d27135aac" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5372 HANO" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "77801115dec7f63400134c21d897a41bddb775eb438d81b354ad18fb6d7ab956" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5349 HEKLA" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "bb9a9db9c00189c27a851f0b772772675cba77e2463ab734477d00e4294db5df" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5389 Hageland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "39e0e2e69be463a4628f87bffe7dc6206aa6daa4a5516fb4ce11907f57d77079" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5362 Heist" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "52bda330e11552b586106748bf652e5dd41163670d5c4226b2c02bfa2f579946" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5393 HerKo" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b6fb86dcca01c89d6787801c958d6b8551f3755ec6f1c35bb97c0cf37b9ddc2c" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5447 Het Houtsche" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "2ca642d589b8012fe65bf54df3a87f740acac78624a902ad378dc4ee6c50a848" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5409 K - L - M" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "c7778ecc532ee037ab821de348f7c6d98ed5b2401abce2e7da64687290c08962" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5412 KASTZE" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "7ddda00fc45a0994092bc26f30d97352b7586676438d5557b3f5cc336daab063" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5379 PZ Kanton Borgloon" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "150440a8bb763d6f53d24ca1c6f1460cb5817c8a261fd90e74aadac3292c3efe" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5367 Kempen N-O" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "306340a51c1504e59f1c3b85c1ba1b62de8c70cb94d3998f27819761bcee5a98" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5377 Kempenland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "ee07affaf869f10517967da1ba7e79151646a1f3621b3cbca591cec2b8c549b7" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5452 Kouter" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "a32dc005ecbc001abd3338cdacb111895d3053b313654136ef1903035c10a53c" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5853 LaMA" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "1db0e6fb09e60db1e8534b20c69abb03584870612717a454937717be9b7fd019" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5907 Limburg Regio Hoofdstad" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "ff7d80dc-ec00-43ac-ac7e-d51694df37ff" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5454 MIDOW" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "fa52110c7c3e70feab724980e2d991a97712a1deeeb25b168ef6de7b16de41ae" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5351 Minos" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "80a9ab8eb46716ab23c597d13313ce24b17884ffcbdf00d216b877d57a52ade4" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5457 Mira" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "7b6bbae823b20191525038cd52089d22128163fb3c7f851ce56149938628d941" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5383 Maasland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "97028faf77fd95eb5016a13c19f3a3a8ccf97c6c937398ba96976e52d171dbd8" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5417 Meetjesland Centrum" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "d8d1b52a9170168ad481f2495652e1b9753aea23385f79710abd86549f1373fa" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5888 MidLim" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "3efb7cb7fad9f61917093d42513c8a7153120906e9701b08e3560c8f109e64c1" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5369 Neteland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "97a393c64a3c30e619bc115ab8b2bbe0bd7a83265ebb8960c0f1154b9628d340" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5348 Noord" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "0594a740b99274c7347f3492ae4d05f9b05d057a1cbad30683634296e189cc38" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5363 PZ Noorderkempen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "b2fdc615ffb131e53a200e14c74ac92d4ed6dac176e3e6ea2c79d227835077c9" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5405 Pajottenland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "7cb2089a8c6746d514711908abfd38414a2b01f6ad9a83f28be2e835888b3da7" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5460 Polder" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "95871bddebd4ad93db54cb1b40d41af29f7ce08f0b59698b0540be129a9a3433" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5453 RIHO" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "5ba4a42bd459dda75ce452a253ddc09547174265456ad1e3f9389a3ff139a1f9" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5416 Regio Puyenbroeck" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "9cb5a65d9190da4bb96d0f59882cbcfb34248d354e6bd27101fccba186f4c7b7" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5418 Regio Rhode & Schelde" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "93389f5157ceb037c5e38d7b8119cef632528b870e91e209c033bc2eac220cc1" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5448 Regio Tielt" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "39e3e46f7cf031133152e763eaa26cab3df81f842f9912a25c69c445f0c428b8" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5364 Regio Turnhout" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "a31131dd72b614c89184b331821c10a0f8feb109881a1b164749e9c8941c5e6b" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5913 Rivierenland" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "81dd243d-f66c-4157-b105-5407aa83cb62" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5403 Politiezone Rode" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "a691d36ff95b67005d30d5fb89594dab69ec7fdbf975ffdcd36ef9bb39efb06d" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5347 Politiezone Rupel" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "46616861cfaae13b550a36ae5c05187638df0873024f13043d3f40f24cabf4e6" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5419 Schelde-Leie" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "c16d166294750ae2c48acae9855a49cd3280a3597c0d8f3257021c68fdede345" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5459 Spoorkin" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "a62fddadcb0a8fb878c3edbdc71a4eb1e6c419b212d41a8bd589fb1a370eb112" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5407 TARL" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "0610b306e95fae751dc07050565e987f31ba06420863bc44616b2e05452d8822" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5456 VLAS" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "477e468496131b7d35f145b0361bca5c2cad577fd9ec27d385d703942dc944d0" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5425 Vlaamse Ardennen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "4deae42b2b25bff407f5abc7cbb6d62eb02afaf2892086341c324fdf2c0e6e92" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5908 Voer en Dijle" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "cdcd4403-d4cd-4400-80a3-9882d79933f4" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5355 Voorkempen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "5dab8a7b0656aaf0db13044fcafc0088f9f0b7776c294a6e9abfdbf7420effae" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5401 Wokra" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "beff71011cde3ac0ee0d94b592462be141cc9f0deb5c6ea996ea191bf79ae2fe" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5904 Waasland-Noord" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "541c1603eb8c01968f95d1f262854134499e00d135cd7c9147d307ccbd1e20fd" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5461 Westkust" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "68ad1301fbb5f209b4ef0fe2b11e77c7bea6011f5e28f8f6875597a7b08f0f1e" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5354 ZARA" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "805a977a29725d94f50bf7f0d91a0de1a727c4eec88940e90035f71c6c9b1655" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5905 Zennevallei" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "e4f4aa293734f92302439270cf98805e4b617088cb19144b558db2dff087d886" .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s skos:altLabel "5365 Zuiderkempen" .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?s core:uuid "dbfedd56289924d8a7cc26a5aada392281547e053a10c0678238fc08a219fb6e" .
  }
}
