
        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214639730" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.wzga.be/" .
            ?contact <http://schema.org/email> "info@wzga.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696665975" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232228400" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.amate.be/over-amate/woonzorg-wuustwezel" .
            ?contact <http://schema.org/email> "info.amandina@amate.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696899963" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3255237455" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://delinderonse.be/" .
            ?contact <http://schema.org/email> "wzc@delinderonse.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0212165922" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3252251320" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.waasmunster.be/product/197/woonzorgcentrum-t-heuverveld" .
            ?contact <http://schema.org/email> "info@samenouder.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698838775" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3224472747" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.metsense.be/nl/onze-uitbatingen#buurtrestaurants" .
            ?contact <http://schema.org/email> "buurtrestaurant@tvondel.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0712777279" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251488172" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.dezonnewende.gvo.be/nl/home/" .
            ?contact <http://schema.org/email> "dezonnewende@gvo.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0735627214" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215321741" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.duffel.be/huishoudhulp" .
            ?contact <http://schema.org/email> "dco.duffel@skynet.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0462239939" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237606060" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://vitaz.be/" .
            ?contact <http://schema.org/email> "info@vitaz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881291322" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3257208071" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://wieltjesgracht.be/" .
            ?contact <http://schema.org/email> "info@wieltjesgracht.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262925527" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251237111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azdelta.be/nl" .
            ?contact <http://schema.org/email> "info@azdelta.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505931808" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232177111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zna.be/nl" .
            ?contact <http://schema.org/email> "communicatie@zna.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862382656" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250277530" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://terluchte.be/" .
            ?contact <http://schema.org/email> "info@terluchte.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0738896510" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211335577" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.jessazh.be/" .
            ?contact <http://schema.org/email> "info@jessazh.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821142117" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214406011" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azturnhout.be/" .
            ?contact <http://schema.org/email> "info@azturnhout.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0897191602" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214246111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azherentals.be/" .
            ?contact <http://schema.org/email> "directiesecretariaat@azherentals.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821734213" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3255336111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azoudenaarde.be/" .
            ?contact <http://schema.org/email> "info@azoudenaarde.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870757023" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zmk.be/index.html" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0475777476" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3222546400" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azjanportaels.be/nl" .
            ?contact <http://schema.org/email> "info@azjanportaels.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267386438" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3256636363" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azgroeninge.be/start" .
            ?contact <http://schema.org/email> "info@azgroeninge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472222625" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214234085" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.het-pareltje.be/" .
            ?contact <http://schema.org/email> "info@het-pareltje.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0883325451" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      


        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svkbodukam.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865010069" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215226855" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svkonderdak.be/" .
            ?contact <http://schema.org/email> "info@svkonderdak.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473360790" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214254580" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.terkempen.be/" .
            ?contact <http://schema.org/email> "info@terkempen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871619135" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.wzcdebuurt.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870855409" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232943734" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sensespraktijkhuis.be/" .
            ?contact <http://schema.org/email> "info@sensespraktijkhuis.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0632607670" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      



        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3228010180" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.ahasverus.be/" .
            ?contact <http://schema.org/email> "directie@ahasverus.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0471364174" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3216885864" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://onshartkloptvooru.be/voorziening/deycken-brug/" .
            ?contact <http://schema.org/email> "algemeen@deyckenbrug.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0861157387" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237661340" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.drietakt.be/" .
            ?contact <http://schema.org/email> "info@drietakt.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0476803795" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      


        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3216791000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.korian.be/nl/woonzorgcentra/kor/131-woonzorgzone-de-kouter" .
            ?contact <http://schema.org/email> "info@wzzdekouter.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0848738221" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251655278" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.amphora.gvo.be/nl/home/" .
            ?contact <http://schema.org/email> "amphora@gvo.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0833161902" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3256264434" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.vzwmentor.be/" .
            ?contact <http://schema.org/email> "info@mentorvzw.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472751175" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250826636" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorg-en-welzijn-zedelgem.gvo.be/" .
            ?contact <http://schema.org/email> "info@zwz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0832024923" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3293113000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.wzczilverbos.be/" .
            ?contact <http://schema.org/email> "info@wzczilverbos.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0644984078" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253667137" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.vanlierde-wzc.be/" .
            ?contact <http://schema.org/email> "onthaal@wzcvanlierde.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0633854022" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251567301" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.blijvelde.be/" .
            ?contact <http://schema.org/email> "info@blijvelde.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0566983014" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3289206597" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://wil.be/nl" .
            ?contact <http://schema.org/email> "info@svkhetscharnier.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881602118" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      


        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3259416111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azoostende.be/" .
            ?contact <http://schema.org/email> "info@azoostende.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0800023336" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253764111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.asz.be/" .
            ?contact <http://schema.org/email> "info@asz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0729523736" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3289480100" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://gerkenberg.be/" .
            ?contact <http://schema.org/email> "info@gerkenberg.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0867804659" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215237393" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.dekringwinkel.be/zuiderkempen" .
            ?contact <http://schema.org/email> "info@dekringwinkelzuiderkempen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459644990" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.kaagent.be/nl" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?org <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0823319370" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      