PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX adms: <http://www.w3.org/ns/adms#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212177305" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0267386438" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0208038769" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212181956" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212240552" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212239859" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212246094" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212212541" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212214620" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212216895" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0208038769" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212217885" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212218974" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212221251" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212223726" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0216769165" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207713127" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212196705" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212203930" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212209868" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212178590" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207504675" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0222947570" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0862457484" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0459644990" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212247777" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0462239939" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207534864" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0462239939" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212236493" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0471364174" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0253973219" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0471364174" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212189676" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0472222625" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212189676" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0472751175" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212171860" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0476803795" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207464192" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0476803795" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212174137" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0505931808" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207432520" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0505931808" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212189280" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0566983014" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207532488" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0566983014" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212200861" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0632607670" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0231884636" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0633854022" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212185817" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0644984078" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207449346" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0644984078" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212236097" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0696665975" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207505368" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0696665975" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212185421" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0696899963" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207537735" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0696899963" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212179778" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0698838775" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207447069" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0698838775" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212215511" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0712777279" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207535458" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0712777279" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212198782" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0735627214" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212205514" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0738896510" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207529520" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0738896510" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212165922" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0778279401" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207460432" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0778279401" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207832792" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0799574166" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212205118" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0800023336" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0473908049" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0800023336" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212216402" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0821142117" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0267302405" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0821142117" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0208038769" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0821734213" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207504675" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0821734213" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212214125" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0823319370" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207451227" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0823319370" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212185718" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0832024923" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207531302" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0832024923" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212184728" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0833161902" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207495470" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0833161902" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212207096" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0848738221" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207523679" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0848738221" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212240948" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0861157387" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212235604" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0862382656" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207500123" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0862382656" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0809699184" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0862382656" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212243720" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0867804659" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207471617" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0867804659" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212207789" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0870757023" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0465810133" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0870757023" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212240552" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212246094" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0216772333" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0216769165" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212196705" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212211452" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212174533" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0222947570" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871619135" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212171860" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881291322" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212215907" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881291322" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207464192" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881291322" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207445782" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881291322" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0871206587" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881291322" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212236196" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881602118" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207148052" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881602118" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0697664382" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881602118" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212375065" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0881602118" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212181956" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0883325451" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207505566" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0883325451" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212239166" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0884212804" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212214521" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0884212804" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212220063" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0884212804" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0216769759" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0884212804" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0216772729" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0887953044" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0212175721" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0897191602" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0207533082" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0897191602" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant org:memberOf ?association .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?participant adms:identifier ?idParticipant .
    FILTER NOT EXISTS { ?participant a ext:KboOrganisatie . }
    ?idParticipant skos:notation ?kboLabel ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "0263545337" .

    ?association adms:identifier ?idAssociation .
    ?idAssociation skos:notation "KBO nummer" ;
      generiek:gestructureerdeIdentificator/generiek:lokaleIdentificator "1005154085" .

    FILTER (?kboLabel IN ("KBO nummer"@nl, "KBO nummer"))
  }
}
;
