
      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "100";
            
            <http://www.w3.org/ns/locn#postCode> "2370";
            <http://www.w3.org/ns/locn#adminUnitL2> "Arendonk";
            <http://www.w3.org/ns/locn#thoroughfare> "Vrijheid";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Arendonk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Vrijheid 100, 2370 Arendonk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696665975" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "737";
            
            <http://www.w3.org/ns/locn#postCode> "2990";
            <http://www.w3.org/ns/locn#adminUnitL2> "Wuustwezel";
            <http://www.w3.org/ns/locn#thoroughfare> "Bredabaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Wuustwezel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bredabaan 737, 2990 Wuustwezel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696899963" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "68";
            
            <http://www.w3.org/ns/locn#postCode> "9600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ronse";
            <http://www.w3.org/ns/locn#thoroughfare> "Oscar Delghuststraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ronse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Oscar Delghuststraat 68, 9600 Ronse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0212165922" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "41";
            
            <http://www.w3.org/ns/locn#postCode> "9250";
            <http://www.w3.org/ns/locn#adminUnitL2> "Waasmunster";
            <http://www.w3.org/ns/locn#thoroughfare> "Molenstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Waasmunster";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Molenstraat 41, 9250 Waasmunster, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698838775" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "40";
            
            <http://www.w3.org/ns/locn#postCode> "1500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Halle";
            <http://www.w3.org/ns/locn#thoroughfare> "Joseph Possozplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Halle";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Joseph Possozplein 40, 1500 Halle, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0712777279" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "68";
            
            <http://www.w3.org/ns/locn#postCode> "8760";
            <http://www.w3.org/ns/locn#adminUnitL2> "Meulebeke";
            <http://www.w3.org/ns/locn#thoroughfare> "Karel van Manderstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Meulebeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Karel van Manderstraat 68, 8760 Meulebeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0735627214" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2570";
            <http://www.w3.org/ns/locn#adminUnitL2> "Duffel";
            <http://www.w3.org/ns/locn#thoroughfare> "Kwakkelenberg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Duffel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kwakkelenberg 1, 2570 Duffel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0462239939" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9100";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Niklaas";
            <http://www.w3.org/ns/locn#thoroughfare> "Moerlandstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Niklaas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Moerlandstraat 1, 9100 Sint-Niklaas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881291322" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "29";
            
            <http://www.w3.org/ns/locn#postCode> "8900";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ieper";
            <http://www.w3.org/ns/locn#thoroughfare> "Lange Torhoutstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ieper";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lange Torhoutstraat 29, 8900 Ieper, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262925527" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Roeselare";
            <http://www.w3.org/ns/locn#thoroughfare> "Deltalaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Roeselare";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Deltalaan 1, 8800 Roeselare, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505931808" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "26";
            
            <http://www.w3.org/ns/locn#postCode> "2000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Leopoldstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Leopoldstraat 26, 2000 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862382656" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "87";
            
            <http://www.w3.org/ns/locn#postCode> "8020";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oostkamp";
            <http://www.w3.org/ns/locn#thoroughfare> "Sint-Elooisstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oostkamp";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Sint-Elooisstraat 87, 8020 Oostkamp, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0738896510" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "20";
            
            <http://www.w3.org/ns/locn#postCode> "3500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Hasselt";
            <http://www.w3.org/ns/locn#thoroughfare> "Salvatorstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hasselt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Salvatorstraat 20, 3500 Hasselt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821142117" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "44";
            
            <http://www.w3.org/ns/locn#postCode> "2300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Turnhout";
            <http://www.w3.org/ns/locn#thoroughfare> "Steenweg op Merksplas";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Turnhout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Steenweg op Merksplas 44, 2300 Turnhout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0897191602" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "133";
            
            <http://www.w3.org/ns/locn#postCode> "2200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Herentals";
            <http://www.w3.org/ns/locn#thoroughfare> "Nederrij";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herentals";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Nederrij 133, 2200 Herentals, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821734213" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "9700";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oudenaarde";
            <http://www.w3.org/ns/locn#thoroughfare> "Minderbroederstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oudenaarde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Minderbroederstraat 3, 9700 Oudenaarde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870757023" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "425";
            
            <http://www.w3.org/ns/locn#postCode> "3680";
            <http://www.w3.org/ns/locn#adminUnitL2> "Maaseik";
            <http://www.w3.org/ns/locn#thoroughfare> "Diestersteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maaseik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Diestersteenweg 425, 3680 Maaseik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0475777476" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "65";
            
            <http://www.w3.org/ns/locn#postCode> "1800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vilvoorde";
            <http://www.w3.org/ns/locn#thoroughfare> "Gendarmeriestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Vilvoorde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gendarmeriestraat 65, 1800 Vilvoorde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267386438" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Kortrijk";
            <http://www.w3.org/ns/locn#thoroughfare> "President Kennedylaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "President Kennedylaan 4, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472222625" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "22_1";
            
            <http://www.w3.org/ns/locn#postCode> "2260";
            <http://www.w3.org/ns/locn#adminUnitL2> "Westerlo";
            <http://www.w3.org/ns/locn#thoroughfare> "Verlorenkost";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Westerlo";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Verlorenkost 22_1, 2260 Westerlo, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0883325451" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus 4";
            <http://www.w3.org/ns/locn#postCode> "2500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Lier";
            <http://www.w3.org/ns/locn#thoroughfare> "Paradeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lier";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Paradeplein 2 - Bus 4, 2500 Lier, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865013039" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6";
            
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Mechelen";
            <http://www.w3.org/ns/locn#thoroughfare> "Lijsterstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lijsterstraat 6, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865010069" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "2220";
            <http://www.w3.org/ns/locn#adminUnitL2> "Heist-Op-Den-Berg";
            <http://www.w3.org/ns/locn#thoroughfare> "Stationstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Heist-op-den-Berg";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stationstraat 2, 2220 Heist-op-den-Berg, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473360790" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "8";
            
            <http://www.w3.org/ns/locn#postCode> "2450";
            <http://www.w3.org/ns/locn#adminUnitL2> "Meerhout";
            <http://www.w3.org/ns/locn#thoroughfare> "Smissestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Meerhout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Smissestraat 8, 2450 Meerhout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871619135" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "9";
            
            <http://www.w3.org/ns/locn#postCode> "2980";
            <http://www.w3.org/ns/locn#adminUnitL2> "Zoersel";
            <http://www.w3.org/ns/locn#thoroughfare> "Kermisplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Zoersel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kermisplein 9, 2980 Zoersel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870855409" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6";
            
            <http://www.w3.org/ns/locn#postCode> "2640";
            <http://www.w3.org/ns/locn#adminUnitL2> "Mortsel";
            <http://www.w3.org/ns/locn#thoroughfare> "Meerminne";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mortsel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Meerminne 6, 2640 Mortsel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0632607670" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3930";
            <http://www.w3.org/ns/locn#adminUnitL2> "Hamont-Achel";
            <http://www.w3.org/ns/locn#thoroughfare> "Michielsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hamont-Achel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Michielsplein 1, 3930 Hamont-Achel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0887953044" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "18";
            
            <http://www.w3.org/ns/locn#postCode> "3620";
            <http://www.w3.org/ns/locn#adminUnitL2> "Lanaken";
            <http://www.w3.org/ns/locn#thoroughfare> "Gasthuisstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lanaken";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gasthuisstraat 18, 3620 Lanaken, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0838654674" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "38";
            
            <http://www.w3.org/ns/locn#postCode> "1730";
            <http://www.w3.org/ns/locn#adminUnitL2> "Asse";
            <http://www.w3.org/ns/locn#thoroughfare> "Muurveld";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Asse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Muurveld 38, 1730 Asse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0471364174" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "5";
            
            <http://www.w3.org/ns/locn#postCode> "3360";
            <http://www.w3.org/ns/locn#adminUnitL2> "Bierbeek";
            <http://www.w3.org/ns/locn#thoroughfare> "Bergenlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bierbeek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bergenlaan 5, 3360 Bierbeek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0861157387" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "22";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "bus 0001";
            <http://www.w3.org/ns/locn#postCode> "9100";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Niklaas";
            <http://www.w3.org/ns/locn#thoroughfare> "Pater Segersstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Niklaas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pater Segersstraat 22 - bus 0001, 9100 Sint-Niklaas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0476803795" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "152";
            
            <http://www.w3.org/ns/locn#postCode> "3460";
            <http://www.w3.org/ns/locn#adminUnitL2> "Bekkevoort";
            <http://www.w3.org/ns/locn#thoroughfare> "Staatsbaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bekkevoort";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Staatsbaan 152, 3460 Bekkevoort, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0884212804" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "3054";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oud-Heverlee";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeentestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oud-Heverlee";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeentestraat 10, 3054 Oud-Heverlee, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0848738221" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "8750";
            <http://www.w3.org/ns/locn#adminUnitL2> "Wingene";
            <http://www.w3.org/ns/locn#thoroughfare> "Sint-Amandsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Wingene";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Sint-Amandsstraat 2, 8750 Wingene, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0833161902" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "27";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Kortrijk";
            <http://www.w3.org/ns/locn#thoroughfare> "Budastraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Budastraat 27, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472751175" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "89";
            
            <http://www.w3.org/ns/locn#postCode> "8210";
            <http://www.w3.org/ns/locn#adminUnitL2> "Zedelgem";
            <http://www.w3.org/ns/locn#thoroughfare> "Fazantlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Zedelgem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Fazantlaan 89, 8210 Zedelgem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0832024923" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "9060";
            <http://www.w3.org/ns/locn#adminUnitL2> "Zelzate";
            <http://www.w3.org/ns/locn#thoroughfare> "Bloemenboslaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Zelzate";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bloemenboslaan 30, 9060 Zelzate, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0644984078" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "1790";
            <http://www.w3.org/ns/locn#adminUnitL2> "Affligem";
            <http://www.w3.org/ns/locn#thoroughfare> "Bellestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Affligem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bellestraat 3, 1790 Affligem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0633854022" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "29";
            
            <http://www.w3.org/ns/locn#postCode> "8610";
            <http://www.w3.org/ns/locn#adminUnitL2> "Kortemark";
            <http://www.w3.org/ns/locn#thoroughfare> "Hospitaalstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortemark";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hospitaalstraat 29, 8610 Kortemark, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0566983014" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "65";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus BU31";
            <http://www.w3.org/ns/locn#postCode> "3600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Genk";
            <http://www.w3.org/ns/locn#thoroughfare> "Grotestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Genk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grotestraat 65 - Bus BU31, 3600 Genk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881602118" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0799574166" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "100";
            
            <http://www.w3.org/ns/locn#postCode> "8400";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oostende";
            <http://www.w3.org/ns/locn#thoroughfare> "Gouwelozestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oostende";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gouwelozestraat 100, 8400 Oostende, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0800023336" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "164";
            
            <http://www.w3.org/ns/locn#postCode> "9300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Aalst";
            <http://www.w3.org/ns/locn#thoroughfare> "Moorselbaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalst";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Moorselbaan 164, 9300 Aalst, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "1005154085" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "90a";
            
            <http://www.w3.org/ns/locn#postCode> "3960";
            <http://www.w3.org/ns/locn#adminUnitL2> "Bree";
            <http://www.w3.org/ns/locn#thoroughfare> "Meeuwerkiezel";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bree";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Meeuwerkiezel 90a, 3960 Bree, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0867804659" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "25";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus 1";
            <http://www.w3.org/ns/locn#postCode> "2220";
            <http://www.w3.org/ns/locn#adminUnitL2> "Heist-Op-Den-Berg";
            <http://www.w3.org/ns/locn#thoroughfare> "Noordstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Heist-op-den-Berg";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Noordstraat 25 - Bus 1, 2220 Heist-op-den-Berg, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459644990" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "808";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Gent";
            <http://www.w3.org/ns/locn#thoroughfare> "Ottergemsesteenweg-Zuid";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ottergemsesteenweg-Zuid 808, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?org <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0823319370" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    