PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/administrative-unit>
{
  <http://data.lblod.info/doc/conceptscheme#ProvincesConceptScheme> a skos:ConceptScheme .
      <http://data.lblod.info/doc/conceptscheme#ProvincesConceptScheme> skos:prefLabel "Provinces Concept Scheme" .
<http://data.lblod.info/doc/conceptscheme#ProvincesConceptScheme>  <http://purl.org/dc/terms/description> "A concept scheme containing all the location entities that are provinces"
  }
}


INSERT 
{ 
GRAPH <http://mu.semte.ch/graphs/administrative-unit>  
{ 
?province_uri rdf:type skos:Concept .
?province_uri skos:inScheme <http://data.lblod.info/doc/conceptscheme#ProvincesConceptScheme> .

} 
} 

WHERE { ?address rdf:type <http://www.w3.org/ns/locn#Address> . ?address <http://www.w3.org/ns/locn#adminUnitL2> ?province_literal . 
?province_uri rdfs:label ?province_literal. 
?province_uri <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Provincie".
}
