INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/00cfb328-1082-470d-9328-e615fbe42308>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "00cfb328-1082-470d-9328-e615fbe42308" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "testgemeente" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/13013> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "115d9fdc-4858-4fc8-b0ac-033263425222" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "testgemeente" ;
      <http://www.w3.org/ns/regorg#legalName> "testgemeente" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .

    <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4>
      <http://www.w3.org/ns/org#hasSubOrganization> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222>
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/6d60f06a-2eab-4b05-9f2d-138a13a5d1f8> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/cfaf6807-5982-4015-ad3c-276ad72dcce2> ;
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/00cfb328-1082-470d-9328-e615fbe42308> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/e407c87e-4923-43c9-aa95-3cd6a576c81e> .

    <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4>
      <http://www.w3.org/ns/org#hasSubOrganization> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .

    <http://data.lblod.info/id/veranderingsgebeurtenissen/7e1c02a2-7175-4b63-812e-40a6c49e4f13>
      a <http://www.w3.org/ns/org#ChangeEvent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "7e1c02a2-7175-4b63-812e-40a6c49e4f13" ;
      <http://data.lblod.info/vocabularies/contacthub/typeWijziging> <http://lblod.data.gift/concepts/e4c3d1ef-a34d-43b0-a18c-f4e60e2c8af3> ;
      <http://www.w3.org/ns/org#originalOrganization> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> ;
      <http://www.w3.org/ns/org#resultingOrganization> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> ;
      <http://lblod.data.gift/vocabularies/organisatie/veranderingsgebeurtenisResultaat> <http://lblod.data.info/id/veranderingsgebeurtenis-resultaten/3d2654c3-4805-4adc-bc88-047d87464556> .

    <http://lblod.data.info/id/veranderingsgebeurtenis-resultaten/3d2654c3-4805-4adc-bc88-047d87464556>
      a <http://lblod.data.gift/vocabularies/organisatie/VeranderingsgebeurtenisResultaat> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "3d2654c3-4805-4adc-bc88-047d87464556" ;
      <http://mu.semte.ch/vocabularies/ext/resultingOrganization> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> ;
      <http://lblod.data.gift/vocabularies/organisatie/resulterendeStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .

    <http://data.lblod.info/id/identificatoren/6d60f06a-2eab-4b05-9f2d-138a13a5d1f8>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/1341545c-f03a-4108-8f44-e695c74b2781>;
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/adms#Identifier>;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6d60f06a-2eab-4b05-9f2d-138a13a5d1f8" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/1341545c-f03a-4108-8f44-e695c74b2781>
      <http://mu.semte.ch/vocabularies/core/uuid> "1341545c-f03a-4108-8f44-e695c74b2781";
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator>;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0209999999" .

    <http://data.lblod.info/id/identificatoren/cfaf6807-5982-4015-ad3c-276ad72dcce2>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/48572385-540f-4437-bf72-415208e8ca15>;
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/adms#Identifier>;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "cfaf6807-5982-4015-ad3c-276ad72dcce2" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/48572385-540f-4437-bf72-415208e8ca15>
      <http://mu.semte.ch/vocabularies/core/uuid> "48572385-540f-4437-bf72-415208e8ca15";
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator>.

    <http://data.lblod.info/id/vestigingen/e407c87e-4923-43c9-aa95-3cd6a576c81e>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e407c87e-4923-43c9-aa95-3cd6a576c81e" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/a0de1669-d2ad-4081-99c9-a9e2697caf7c> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/bccac74c-408c-4254-ad4f-3443585c7fe6> .

    <http://data.lblod.info/id/contact-punten/a0de1669-d2ad-4081-99c9-a9e2697caf7c>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a0de1669-d2ad-4081-99c9-a9e2697caf7c" ;
      <http://schema.org/email> "test@test.be" ;
      <http://schema.org/telephone> "tel:+3222999999" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.example.com" .

    <http://data.lblod.info/id/adressen/bccac74c-408c-4254-ad4f-3443585c7fe6>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid>"bccac74c-408c-4254-ad4f-3443585c7fe6" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herselt" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1" ;
      <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" ;
      <http://www.w3.org/ns/locn#fullAddress> "Testeltsebaan 1, 2230 Herselt, België" ;
      <http://www.w3.org/ns/locn#postCode> "2230" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Testeltsebaan" ;
      <https://data.vlaanderen.be/ns/adres#adresIsGelegenIn> <http://data.lblod.info/id/werkingsgebieden/00cfb328-1082-470d-9328-e615fbe42308>.

    <http://data.lblod.info/id/lidmaatschap/825e1945-1623-405e-aea6-75c580b7ae9a>
      a <http://www.w3.org/ns/org#Membership> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "825e1945-1623-405e-aea6-75c580b7ae9a" ;
      <http://www.w3.org/ns/org#organization> <http://data.lblod.info/id/bestuurseenheden/52cc723a-9717-496d-9897-c6774cf124e4> ;
      <http://www.w3.org/ns/org#member> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> ;
      <http://www.w3.org/ns/org#role> <http://data.lblod.info/id/rollen/4ec7d5c39bdc4e84b4174379b9e22ad8> .

    <http://data.lblod.info/id/bestuursorganen/b93dbe87-27c8-47ee-bc73-430dc95d65ec> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "b93dbe87-27c8-47ee-bc73-430dc95d65ec" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Algemeen directeur Gemeente testgemeente" ;
        <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/39854196-f214-4688-87a1-d6ad12baa2fa> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .

    <http://data.lblod.info/id/bestuursorganen/a20565f4-2d86-4461-9485-bc8bce865950> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "a20565f4-2d86-4461-9485-bc8bce865950" ;
        <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/b93dbe87-27c8-47ee-bc73-430dc95d65ec> ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursorganen/4561ea34-b441-4780-a008-0c772cdbb68a> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "4561ea34-b441-4780-a008-0c772cdbb68a" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "College van Burgemeester en Schepenen testgemeente" ;
        <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000006> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .

    <http://data.lblod.info/id/bestuursorganen/8b1ba8a0-fa45-4211-9129-8a18d24889b8> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "8b1ba8a0-fa45-4211-9129-8a18d24889b8" ;
        <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/4561ea34-b441-4780-a008-0c772cdbb68a> ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursorganen/4fc8d45c-965c-443d-ae25-38562c1afd9f> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "4fc8d45c-965c-443d-ae25-38562c1afd9f" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Financieel directeur Gemeente testgemeente" ;
        <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/62644b9c-4514-41dd-a660-4c35257f2b35> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .

    <http://data.lblod.info/id/bestuursorganen/f4e6ebe1-81f1-4ed0-a780-c6cb4a0a58c1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "f4e6ebe1-81f1-4ed0-a780-c6cb4a0a58c1" ;
        <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/4fc8d45c-965c-443d-ae25-38562c1afd9f> ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursorganen/794324e5-3730-4f6f-8a78-564a5e231582> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "794324e5-3730-4f6f-8a78-564a5e231582" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "Adjunct-algemeen directeur Gemeente testgemeente" ;
        <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/11f0af9e-016c-4e0b-983a-d8bc73804abc> ;
        <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222> .

    <http://data.lblod.info/id/bestuursorganen/945418a9-36dc-4dbb-8a41-fb1176b4ce75> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "945418a9-36dc-4dbb-8a41-fb1176b4ce75" ;
        <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie> <http://data.lblod.info/id/bestuursfuncties/904a6d80-58bf-11f0-8a90-dda5d31bcff4> ;
        <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/794324e5-3730-4f6f-8a78-564a5e231582> ;
        <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursfuncties/904a6d80-58bf-11f0-8a90-dda5d31bcff4> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.lblod.info/vocabularies/leidinggevenden/Bestuursfunctie> ;
        <http://mu.semte.ch/vocabularies/core/uuid> "904a6d80-58bf-11f0-8a90-dda5d31bcff4" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel> "testgemeente Adjunct Algemeen Directeur" ;
        <http://www.w3.org/ns/org#role> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/f7b4e17b-6f4e-48e7-a558-bce61669f59a> .

    <http://data.lblod.info/id/bestuursorganen/9f490864-8b0b-49df-b9ad-8c2b3026a762> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222>;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/4955bd72cd0e4eb895fdbfab08da0284>;
      <http://mu.semte.ch/vocabularies/core/uuid> "9f490864-8b0b-49df-b9ad-8c2b3026a762";
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Burgemeester testgemeente" .

    <http://data.lblod.info/id/bestuursorganen/eb8f1a65-ebac-41e3-8d50-ad4d6f1760c6> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://mu.semte.ch/vocabularies/core/uuid> "eb8f1a65-ebac-41e3-8d50-ad4d6f1760c6" ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/9f490864-8b0b-49df-b9ad-8c2b3026a762>;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursorganen/e776db01-2b65-4350-a768-fe960484507b> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://mu.semte.ch/vocabularies/core/uuid> "e776db01-2b65-4350-a768-fe960484507b";
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222>;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/ed40469e-3b6f-4f38-99ba-18912ee352b0>;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Adjunct-financieel directeur Gemeente testgemeente" .

    <http://data.lblod.info/id/bestuursorganen/47f00c2d-7696-4b9e-a80f-909661ec914b> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://mu.semte.ch/vocabularies/core/uuid> "47f00c2d-7696-4b9e-a80f-909661ec914b" ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/e776db01-2b65-4350-a768-fe960484507b>;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/bestuursorganen/1112989e-2ee5-4575-a305-ea7127ccbbf0> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://data.vlaanderen.be/ns/besluit#bestuurt> <http://data.lblod.info/id/bestuurseenheden/115d9fdc-4858-4fc8-b0ac-033263425222>;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005>;
      <http://mu.semte.ch/vocabularies/core/uuid> "1112989e-2ee5-4575-a305-ea7127ccbbf0";
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Gemeenteraad testgemeente" .

    <http://data.lblod.info/id/bestuursorganen/846a1251-3518-4b93-948e-d469a5c9dd44> a <http://data.vlaanderen.be/ns/besluit#Bestuursorgaan>;
      <http://mu.semte.ch/vocabularies/core/uuid> "846a1251-3518-4b93-948e-d469a5c9dd44" ;
      <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan> <http://data.lblod.info/id/bestuursorganen/1112989e-2ee5-4575-a305-ea7127ccbbf0>;
      <http://www.w3.org/ns/org#hasPost> <http://data.lblod.info/id/mandaten/19413fd7-ca6a-4363-af8c-5b8e30ca13d4> ;
      <http://www.w3.org/ns/org#hasPost> <http://data.lblod.info/id/mandaten/fb84271e-e936-4b75-9534-42527052b554> ;
      <http://data.vlaanderen.be/ns/mandaat#bindingStart> "2019-01-01T00:00:00Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

    <http://data.lblod.info/id/mandaten/19413fd7-ca6a-4363-af8c-5b8e30ca13d4>
      a <http://data.vlaanderen.be/ns/mandaat#Mandaat> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "19413fd7-ca6a-4363-af8c-5b8e30ca13d4" ;
      <http://www.w3.org/ns/org#role> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000011> .

    <http://data.lblod.info/id/mandaten/fb84271e-e936-4b75-9534-42527052b554>
      a <http://data.vlaanderen.be/ns/mandaat#Mandaat> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "fb84271e-e936-4b75-9534-42527052b554" ;
      <http://www.w3.org/ns/org#role> <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000012> .

  }
}
