PREFIX org: <http://www.w3.org/ns/org#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>

DELETE {
  GRAPH ?g {
    ?site ?pSite ?oSite .
    ?contact ?pContact ?oContact .
    ?address ?pAddress ?oAddress .
    ?addressContact ?pAddressContact ?oAddressContact .
  }
} WHERE {
  VALUES ?hasSite {
    <http://www.w3.org/ns/org#hasPrimarySite>
    <http://www.w3.org/ns/org#hasSite>
  }

  FILTER (?site IN
          (
           <http://data.lblod.info/id/vestigingen/43557b6bd03abd95ad981f3f611777c5> ,
           <http://data.lblod.info/id/vestigingen/63639DA88DE5818A7C9F439D> ,
           <http://data.lblod.info/id/vestigingen/d3a88c997bc377fd0172d7555ef2f154> ,
           <http://data.lblod.info/id/vestigingen/866ca7d5975c853890ba18bb189892c4> ,
           <http://data.lblod.info/id/vestigingen/d5283487-d4eb-4e57-afef-de1de153b42f> ,
           <http://data.lblod.info/id/vestigingen/100a61965dc84e9b18a2dd1f1d7c81aa> ,
           <http://data.lblod.info/id/vestigingen/9d97ea7e82a9821a80c19e136afb2efc> ,
           <http://data.lblod.info/id/vestigingen/9f0d58d2127987435056229003e18b56>
           ))

  GRAPH ?organisationGraph {
    ?organisation ?hasSite ?site .
  }

  VALUES ?organisationGraph {
    <http://mu.semte.ch/graphs/administrative-unit>
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/shared>
  }

  GRAPH ?g {
    ?site ?pSite ?oSite .
    {
      ?site org:siteAddress ?contact .
      ?contact ?pContact ?oContact .
      ?contact locn:address ?addressContact .
      ?addressContact ?pAddressContact ?oAddressContact .
    } UNION {
      ?site org:siteAddress ?contact .
      ?contact ?pContact ?oContact .
    } UNION {
      ?site organisatie:bestaatUit ?address .
      ?address ?pAddress ?oAddress .
    }
  }

  VALUES ?g {
    <http://mu.semte.ch/graphs/administrative-unit>
    <http://mu.semte.ch/graphs/worship-service>
    <http://mu.semte.ch/graphs/shared>
  }
}
