DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/contact-punten/5def8bef-2029-403d-b80e-28a23638fe63> <http://schema.org/telephone> "tel:+32 3 410 02 11" .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/contact-punten/5def8bef-2029-403d-b80e-28a23638fe63> <http://schema.org/telephone> "tel:+3234100211" .
  }
}
