PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/418f7041-4b01-4802-992f-5a9412f5b4a0> a skos:Concept ;
      mu:uuid "418f7041-4b01-4802-992f-5a9412f5b4a0" ;
      skos:prefLabel "Overheid van het Brusselse Hoofdstedelijk Gewest" .
  }
}
