DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/jobs> {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?type {
      <http://vocab.deri.ie/cogs#Job>
      <http://redpencil.data.gift/vocabularies/tasks/Task>
      <http://open-services.net/ns/core#Error>
      <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DataContainer>
    }

    ?s a ?type ;
      ?p ?o .
  }
}
