INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/bec2b245-2cc5-4140-98f3-d81e24ca6b0a>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "bec2b245-2cc5-4140-98f3-d81e24ca6b0a" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Jette" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21010> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025864>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "0a162b7b-8576-472f-b0e7-4d244b97e2a6" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Jette" ;
      <http://www.w3.org/ns/regorg#legalName> "Jette" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025864>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/bec2b245-2cc5-4140-98f3-d81e24ca6b0a> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/eeefd726-7c1a-4c16-89d2-c49c154a0e63> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/f9b1f14f-0655-4a80-97ce-6c52ada0dcc7> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/b0d6de26-6759-4174-9ede-e2705504a0ca> .

    <http://data.lblod.info/id/identificatoren/eeefd726-7c1a-4c16-89d2-c49c154a0e63>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/82089dca-7666-4a0e-8054-0f2994a872e8>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "eeefd726-7c1a-4c16-89d2-c49c154a0e63" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/82089dca-7666-4a0e-8054-0f2994a872e8>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207366895" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "82089dca-7666-4a0e-8054-0f2994a872e8" .

    <http://data.lblod.info/id/identificatoren/f9b1f14f-0655-4a80-97ce-6c52ada0dcc7>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/f7017215-3845-46e7-90d4-cfcec08e14f9>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f9b1f14f-0655-4a80-97ce-6c52ada0dcc7" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/f7017215-3845-46e7-90d4-cfcec08e14f9>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025864" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f7017215-3845-46e7-90d4-cfcec08e14f9" .

    <http://data.lblod.info/id/vestigingen/b0d6de26-6759-4174-9ede-e2705504a0ca>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b0d6de26-6759-4174-9ede-e2705504a0ca" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/36b55789-f70b-4212-a93c-35f04fcf6c3f> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/b8b6e0ae-9c03-4878-b196-f60a8c7501ed> .

    <http://data.lblod.info/id/contact-punten/36b55789-f70b-4212-a93c-35f04fcf6c3f>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "36b55789-f70b-4212-a93c-35f04fcf6c3f" ;
      <http://schema.org/email> "info@jette.brussels" ;
      <http://schema.org/telephone> "tel:+3224231211" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://jette.brussels/" .

    <http://data.lblod.info/id/adressen/b8b6e0ae-9c03-4878-b196-f60a8c7501ed>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b8b6e0ae-9c03-4878-b196-f60a8c7501ed" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Jette" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "102" ;
      <http://www.w3.org/ns/locn#fullAddress> "Wemmelse Steenweg 102, 1090 Jette, België" ;
      <http://www.w3.org/ns/locn#postCode> "1090" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Wemmelse Steenweg" .
  }
}
