INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/457e89c4-a41b-41ad-b20d-03086c402639>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "457e89c4-a41b-41ad-b20d-03086c402639" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Koekelberg" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21011> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025865>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "d38eb8bd-3ff1-4cec-b94d-29675eb3f984" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Koekelberg" ;
      <http://www.w3.org/ns/regorg#legalName> "Koekelberg" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025865>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/457e89c4-a41b-41ad-b20d-03086c402639> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/4abab8a9-7c79-4330-8fc7-e4a325604b2d> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/f9ec107a-73cd-4a9e-882b-bf714b6b9485> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/fe1ed9ff-3e07-4f67-bbc3-9fae906f6cc3> .

    <http://data.lblod.info/id/identificatoren/4abab8a9-7c79-4330-8fc7-e4a325604b2d>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/bacf971e-7143-4e74-97c6-89ce746aeb09>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "4abab8a9-7c79-4330-8fc7-e4a325604b2d" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/bacf971e-7143-4e74-97c6-89ce746aeb09>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207372538" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "bacf971e-7143-4e74-97c6-89ce746aeb09" .

    <http://data.lblod.info/id/identificatoren/f9ec107a-73cd-4a9e-882b-bf714b6b9485>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/8a86fb4a-c30c-44b2-9713-93506f1f1d6e>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f9ec107a-73cd-4a9e-882b-bf714b6b9485" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/8a86fb4a-c30c-44b2-9713-93506f1f1d6e>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025865" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8a86fb4a-c30c-44b2-9713-93506f1f1d6e" .

    <http://data.lblod.info/id/vestigingen/fe1ed9ff-3e07-4f67-bbc3-9fae906f6cc3>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "fe1ed9ff-3e07-4f67-bbc3-9fae906f6cc3" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/11f67d9e-0d64-4f09-825c-f1afebdfe11b> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/aed51fac-fbf4-4cb4-8bac-9fbcf65cee49> .

    <http://data.lblod.info/id/contact-punten/11f67d9e-0d64-4f09-825c-f1afebdfe11b>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "11f67d9e-0d64-4f09-825c-f1afebdfe11b" ;
      <http://schema.org/email> "info.1081@koekelberg.brussels" ;
      <http://schema.org/telephone> "tel:+3224121411" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.koekelberg.be/" .

    <http://data.lblod.info/id/adressen/aed51fac-fbf4-4cb4-8bac-9fbcf65cee49>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "aed51fac-fbf4-4cb4-8bac-9fbcf65cee49" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Koekelberg" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6" ;
      <http://www.w3.org/ns/locn#fullAddress> "Henri Vanhuffelplein 6, 1081 Koekelberg, België" ;
      <http://www.w3.org/ns/locn#postCode> "1081" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Henri Vanhuffelplein" .
  }
}
