DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    ?agent ?pagent ?oagent .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> { 
    ?agent a <http://data.lblod.info/vocabularies/contacthub/AgentInPositie> ;
      ?pagent ?oagent .

    # Ensure the agent comes from Loket initially and will be re-synced
    FILTER EXISTS {
      GRAPH <http://mu.semte.ch/graphs/landing-zone/worship-services-sensitive> {
        ?agent a <http://data.lblod.info/vocabularies/contacthub/AgentInPositie> .
      }
    }
  }
}
