PREFIX  ext:  <http://mu.semte.ch/vocabularies/ext/>
 PREFIX  besluit: <http://data.vlaanderen.be/ns/besluit#>
 PREFIX  mu:   <http://mu.semte.ch/vocabularies/core/>
 PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
 PREFIX  dcterms: <http://purl.org/dc/terms/>
 PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
 
 INSERT DATA {
   GRAPH <http://mu.semte.ch/graphs/public> {
     <http://data.lblod.info/id/account/3a91ff60-07c1-4136-ac5e-55cf401e0958> ext:sessionRole "ABBOrganisatiePortaalGebruiker-beheerder" .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> mu:uuid "2fe9885b-d058-4059-b036-69b54444273d" .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> foaf:familyName "WorshipLezer" .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/2fe9885b-d058-4059-b036-69b54444273d> foaf:account <http://data.lblod.info/id/account/8d411fea-5bf0-4925-ba97-14b2223f65ea> .
     <http://data.lblod.info/id/account/8d411fea-5bf0-4925-ba97-14b2223f65ea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/8d411fea-5bf0-4925-ba97-14b2223f65ea> mu:uuid "8d411fea-5bf0-4925-ba97-14b2223f65ea" .
     <http://data.lblod.info/id/account/8d411fea-5bf0-4925-ba97-14b2223f65ea> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/8d411fea-5bf0-4925-ba97-14b2223f65ea> ext:sessionRole "ABBOrganisatiePortaalErediensten-lezer" .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> mu:uuid "4925580c-a1a9-43d4-b3f6-10bd7ff57e25" .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> foaf:familyName "WorshipEditeerder" .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/4925580c-a1a9-43d4-b3f6-10bd7ff57e25> foaf:account <http://data.lblod.info/id/account/fe45b266-715c-481e-9a97-a70f6121166c> .
     <http://data.lblod.info/id/account/fe45b266-715c-481e-9a97-a70f6121166c> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/fe45b266-715c-481e-9a97-a70f6121166c> mu:uuid "fe45b266-715c-481e-9a97-a70f6121166c" .
     <http://data.lblod.info/id/account/fe45b266-715c-481e-9a97-a70f6121166c> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/fe45b266-715c-481e-9a97-a70f6121166c> ext:sessionRole "ABBOrganisatiePortaalErediensten-editeerder" .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:Person .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> mu:uuid "f3610493-f6e1-4490-9723-628fe0213491" .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> foaf:firstName "Josephine" .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> foaf:familyName "WorshipBeheerder" .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> foaf:member <http://data.lblod.info/id/bestuurseenheden/141d9d6b-54af-4d17-b313-8d1c30bc3f5b> .
     <http://data.lblod.info/id/persoon/f3610493-f6e1-4490-9723-628fe0213491> foaf:account <http://data.lblod.info/id/account/2a88a4b4-4672-45eb-b072-c930bf3b40ae> .
     <http://data.lblod.info/id/account/2a88a4b4-4672-45eb-b072-c930bf3b40ae> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> foaf:OnlineAccount .
     <http://data.lblod.info/id/account/2a88a4b4-4672-45eb-b072-c930bf3b40ae> mu:uuid "2a88a4b4-4672-45eb-b072-c930bf3b40ae" .
     <http://data.lblod.info/id/account/2a88a4b4-4672-45eb-b072-c930bf3b40ae> foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service> .
     <http://data.lblod.info/id/account/2a88a4b4-4672-45eb-b072-c930bf3b40ae> ext:sessionRole "ABBOrganisatiePortaalErediensten-beheerder" .
  }
   }
