INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/d6d937a1-aa1f-41fb-9e09-7ac80ad39a9a>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "d6d937a1-aa1f-41fb-9e09-7ac80ad39a9a" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Sint-Lambrechts-Woluwe" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21018> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025823>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f5930a9e-3160-4f80-8134-460a847643af" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Sint-Lambrechts-Woluwe" ;
      <http://www.w3.org/ns/regorg#legalName> "Sint-Lambrechts-Woluwe" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025823>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/d6d937a1-aa1f-41fb-9e09-7ac80ad39a9a> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/9557e115-77f3-42a8-84ad-16755ff51c30> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/9dd47ba7-67b3-45da-a6b8-bf4d0a13d914> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/9dccf2e9-eec6-4a39-b39d-3836c3120330> .

    <http://data.lblod.info/id/identificatoren/9557e115-77f3-42a8-84ad-16755ff51c30>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/819ffbde-7b29-475c-ae16-0c0337b0dbec>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9557e115-77f3-42a8-84ad-16755ff51c30" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/819ffbde-7b29-475c-ae16-0c0337b0dbec>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207389859" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "819ffbde-7b29-475c-ae16-0c0337b0dbec" .

    <http://data.lblod.info/id/identificatoren/9dd47ba7-67b3-45da-a6b8-bf4d0a13d914>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/fdd92962-b2a2-4680-858f-ee56cc88ffd2>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9dd47ba7-67b3-45da-a6b8-bf4d0a13d914" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/fdd92962-b2a2-4680-858f-ee56cc88ffd2>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025823" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "fdd92962-b2a2-4680-858f-ee56cc88ffd2" .

    <http://data.lblod.info/id/vestigingen/9dccf2e9-eec6-4a39-b39d-3836c3120330>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9dccf2e9-eec6-4a39-b39d-3836c3120330" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/1d4be53f-9247-46a9-a16b-e31756466183> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/e9121d98-9a64-4da4-bcbb-36a20298d6d2> .

    <http://data.lblod.info/id/contact-punten/1d4be53f-9247-46a9-a16b-e31756466183>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "1d4be53f-9247-46a9-a16b-e31756466183" ;
      <http://schema.org/email> "infocom@woluwe1200.be" ;
      <http://schema.org/telephone> "tel:+3227612711" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.woluwe1200.be/" .

    <http://data.lblod.info/id/adressen/e9121d98-9a64-4da4-bcbb-36a20298d6d2>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e9121d98-9a64-4da4-bcbb-36a20298d6d2" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Lambrechts-Woluwe" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2" ;
      <http://www.w3.org/ns/locn#fullAddress> "Paul Hymanslaan 2, 1200 Sint-Lambrechts-Woluwe, België" ;
      <http://www.w3.org/ns/locn#postCode> "1200" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Paul Hymanslaan" .
  }
}