INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/77b98d71-5c90-484d-ba2f-2ca9bafe1abb>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "77b98d71-5c90-484d-ba2f-2ca9bafe1abb" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Ganshoren" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21008> ;
      <http://purl.org/dc/terms/source> <https://data.vlaanderen.be/doc/organisatie> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO026992>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "05171f8f-b15f-4462-a46e-4b93695593f8" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Ganshoren" ;
      <http://www.w3.org/ns/regorg#legalName> "Ganshoren" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO026992>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/77b98d71-5c90-484d-ba2f-2ca9bafe1abb> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/9ee7b37b-dcb2-41f7-a623-4b409b21c514> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/f3c1a6c7-23a7-49df-9338-065659186575> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/ed10ce9c-c582-4b49-9ba6-9e228868f860> .

    <http://data.lblod.info/id/identificatoren/9ee7b37b-dcb2-41f7-a623-4b409b21c514>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/63a1ccfa-3545-4883-8f56-2bad82302028>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "9ee7b37b-dcb2-41f7-a623-4b409b21c514" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/63a1ccfa-3545-4883-8f56-2bad82302028>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207401044" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "63a1ccfa-3545-4883-8f56-2bad82302028" .

    <http://data.lblod.info/id/identificatoren/f3c1a6c7-23a7-49df-9338-065659186575>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/6fef2797-0b22-4e6e-b036-4590362bf129>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "f3c1a6c7-23a7-49df-9338-065659186575" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/6fef2797-0b22-4e6e-b036-4590362bf129>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO026992" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6fef2797-0b22-4e6e-b036-4590362bf129" .

    <http://data.lblod.info/id/vestigingen/ed10ce9c-c582-4b49-9ba6-9e228868f860>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "ed10ce9c-c582-4b49-9ba6-9e228868f860" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/8732662e-d6f0-4845-9881-4a8909f3d216> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/a219f021-e4a5-47a9-a774-cefb3b879a1f> .

    <http://data.lblod.info/id/contact-punten/8732662e-d6f0-4845-9881-4a8909f3d216>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8732662e-d6f0-4845-9881-4a8909f3d216" ;
      <http://schema.org/email> "ganshoren@ganshoren.brussels" ;
      <http://schema.org/telephone> "tel:+3224651277" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.ganshoren.be/" .

    <http://data.lblod.info/id/adressen/a219f021-e4a5-47a9-a774-cefb3b879a1f>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a219f021-e4a5-47a9-a774-cefb3b879a1f" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ganshoren" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "140" ;
      <http://www.w3.org/ns/locn#fullAddress> "Keizer Karellaan 140, 1083 Ganshoren, België" ;
      <http://www.w3.org/ns/locn#postCode> "1083" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Keizer Karellaan" .
  }
}