INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/6fa36cc7-0e9a-4b8a-b285-443f52ffa989>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6fa36cc7-0e9a-4b8a-b285-443f52ffa989" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Sint-Pieters-Woluwe" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21019> ;
      <http://purl.org/dc/terms/source> <https://data.vlaanderen.be/doc/organisatie> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025817>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e327536c-f8ce-4138-b84c-2f9a8ce20912" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Sint-Pieters-Woluwe" ;
      <http://www.w3.org/ns/regorg#legalName> "Sint-Pieters-Woluwe" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025817>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/6fa36cc7-0e9a-4b8a-b285-443f52ffa989> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/a4834fea-ab23-4447-b171-92f80c6481f3> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/c137849b-184f-4845-b070-a45d467ae5ba> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/a662844a-c476-4659-b070-fb633a11e294> .

    <http://data.lblod.info/id/identificatoren/a4834fea-ab23-4447-b171-92f80c6481f3>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/439b0802-ac26-4750-829c-b542d0edf4f8>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a4834fea-ab23-4447-b171-92f80c6481f3" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/439b0802-ac26-4750-829c-b542d0edf4f8>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207366994" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "439b0802-ac26-4750-829c-b542d0edf4f8" .

    <http://data.lblod.info/id/identificatoren/c137849b-184f-4845-b070-a45d467ae5ba>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/e7a8f7da-e41e-4d02-ba89-5515dd96fad1>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "c137849b-184f-4845-b070-a45d467ae5ba" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/e7a8f7da-e41e-4d02-ba89-5515dd96fad1>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025817" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e7a8f7da-e41e-4d02-ba89-5515dd96fad1" .

    <http://data.lblod.info/id/vestigingen/a662844a-c476-4659-b070-fb633a11e294>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a662844a-c476-4659-b070-fb633a11e294" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/7eea521a-6be9-472b-9cab-07e958bbcec0> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/a1959366-e8d9-4378-8ee5-e446defde34c> .

    <http://data.lblod.info/id/contact-punten/7eea521a-6be9-472b-9cab-07e958bbcec0>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "7eea521a-6be9-472b-9cab-07e958bbcec0" ;
      <http://schema.org/email> "info@woluwe1150.be" ;
      <http://schema.org/telephone> "tel:+3227730511" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.woluwe1150.be/" .

    <http://data.lblod.info/id/adressen/a1959366-e8d9-4378-8ee5-e446defde34c>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a1959366-e8d9-4378-8ee5-e446defde34c" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Pieters-Woluwe" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "93" ;
      <http://www.w3.org/ns/locn#fullAddress> "Charles Thielemanslaan 93, 1150 Sint-Pieters-Woluwe, België" ;
      <http://www.w3.org/ns/locn#postCode> "1150" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Charles Thielemanslaan" .
  }
}