INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/werkingsgebieden/331fbb80-ba0a-4a33-95e4-5d2674415c72>
      a <http://www.w3.org/ns/prov#Location> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "331fbb80-ba0a-4a33-95e4-5d2674415c72" ;
      <http://www.w3.org/2000/01/rdf-schema#label> "Elsene" ;
      <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau> "Gemeente" ;
      <http://www.w3.org/2004/02/skos/core#exactMatch> <http://vocab.belgif.be/auth/refnis2025/21009> .
  }

  GRAPH <http://mu.semte.ch/graphs/shared> {
    <https://data.vlaanderen.be/id/organisatie/OVO025861>
      a <http://www.w3.org/ns/org#Organization> ,
        <http://data.vlaanderen.be/ns/besluit#Bestuurseenheid> ,
        <http://purl.org/dc/terms/Agent> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "4d892d46-2fda-4c24-89da-d4cdc2ac379d" ;
      <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Elsene" ;
      <http://www.w3.org/ns/regorg#legalName> "Elsene" ;
      <http://www.w3.org/ns/regorg#orgStatus> <http://lblod.data.gift/concepts/63cc561de9188d64ba5840a42ae8f0d6> .
  }

  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <https://data.vlaanderen.be/id/organisatie/OVO025861>
      <http://data.vlaanderen.be/ns/besluit#werkingsgebied> <http://data.lblod.info/id/werkingsgebieden/331fbb80-ba0a-4a33-95e4-5d2674415c72> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/8f918141-e2e8-470c-8edb-fefc45743afb> ;
      <http://www.w3.org/ns/adms#identifier> <http://data.lblod.info/id/identificatoren/2b39418f-c1c2-4880-b3a9-c6e8911d779b> ;
      <http://www.w3.org/ns/org#hasPrimarySite> <http://data.lblod.info/id/vestigingen/6fe561e2-76aa-4c99-83e6-083f2c47c7e0> .

    <http://data.lblod.info/id/identificatoren/8f918141-e2e8-470c-8edb-fefc45743afb>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/644381f5-cfaa-45ab-bf13-79475359c7f9>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "8f918141-e2e8-470c-8edb-fefc45743afb" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/644381f5-cfaa-45ab-bf13-79475359c7f9>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207401341" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "644381f5-cfaa-45ab-bf13-79475359c7f9" .

    <http://data.lblod.info/id/identificatoren/2b39418f-c1c2-4880-b3a9-c6e8911d779b>
      <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> <http://data.lblod.info/id/gestructureerdeIdentificator/1e5698d7-4299-40de-a1a9-c0e2fa571c27>;
      a <http://www.w3.org/ns/adms#Identifier> ;
      <http://www.w3.org/2004/02/skos/core#notation> "OVO-nummer" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "2b39418f-c1c2-4880-b3a9-c6e8911d779b" .

    <http://data.lblod.info/id/gestructureerdeIdentificator/1e5698d7-4299-40de-a1a9-c0e2fa571c27>
      a <https://data.vlaanderen.be/ns/generiek#GestructureerdeIdentificator> ;
      <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025861" ;
      <http://mu.semte.ch/vocabularies/core/uuid> "1e5698d7-4299-40de-a1a9-c0e2fa571c27" .

    <http://data.lblod.info/id/vestigingen/6fe561e2-76aa-4c99-83e6-083f2c47c7e0>
      a <http://www.w3.org/ns/org#Site> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "6fe561e2-76aa-4c99-83e6-083f2c47c7e0" ;
      <http://data.lblod.info/vocabularies/erediensten/vestigingstype> <http://lblod.data.gift/concepts/f1381723dec42c0b6ba6492e41d6f5dd> ;
      <http://www.w3.org/ns/org#siteAddress> <http://data.lblod.info/id/contact-punten/b200bda3-74da-4fe6-a384-95cc3b10460c> ;
      <https://data.vlaanderen.be/ns/organisatie#bestaatUit> <http://data.lblod.info/id/adressen/5ccba902-3d32-4fac-b51f-ad6fa05f9d6c> .

    <http://data.lblod.info/id/contact-punten/b200bda3-74da-4fe6-a384-95cc3b10460c>
      a <http://schema.org/ContactPoint> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "b200bda3-74da-4fe6-a384-95cc3b10460c" ;
      <http://schema.org/email> "secretariaat@elsene.be" ;
      <http://schema.org/telephone> "tel:+3225156111" ;
      <http://schema.org/contactType> "Primary" ;
      <http://xmlns.com/foaf/0.1/page> "https://www.elsene.be/" .

    <http://data.lblod.info/id/adressen/5ccba902-3d32-4fac-b51f-ad6fa05f9d6c>
      a <http://www.w3.org/ns/locn#Address> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "5ccba902-3d32-4fac-b51f-ad6fa05f9d6c" ;
      <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Elsene" ;
      <https://data.vlaanderen.be/ns/adres#land> "België" ;
      <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "168" ;
      <http://www.w3.org/ns/locn#fullAddress> "Elsense Steenweg 168, 1050 Elsene, België" ;
      <http://www.w3.org/ns/locn#postCode> "1050" ;
      <http://www.w3.org/ns/locn#thoroughfare> "Elsense Steenweg" .
  }
}