DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/40022a348133be5a8da995c6770ced56> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0413234648" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/40022a348133be5a8da995c6770ced56> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0408166496" .
  }
}
