PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX scheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX lblodorg: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX concept: <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    concept:2ad46df5-5c79-4d67-84d5-604c1377231e a skos:Concept ;
      a lblodorg:BestuurseenheidClassificatieCode ;
      a ext:BestuurseenheidClassificatieCode ;
      a ext:OrganizationClassificationCode ;
      core:uuid "2ad46df5-5c79-4d67-84d5-604c1377231e" ;
      skos:prefLabel "PEVA gemeente" ;
      skos:inScheme scheme:BestuurseenheidClassificatieCode ;
      skos:topConceptOf scheme:BestuurseenheidClassificatieCode .
  }
}
