PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX scheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX lblodorg: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX concept: <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    concept:088784b6-e188-48bf-b94f-94665f9e1f53 a skos:Concept ;
      a lblodorg:BestuurseenheidClassificatieCode ;
      a ext:BestuurseenheidClassificatieCode ;
      a ext:OrganizationClassificationCode ;
      core:uuid "088784b6-e188-48bf-b94f-94665f9e1f53" ;
      skos:prefLabel "PEVA provincie" ;
      skos:inScheme scheme:BestuurseenheidClassificatieCode ;
      skos:topConceptOf scheme:BestuurseenheidClassificatieCode .
  }
}
