PREFIX org: <http://www.w3.org/ns/org#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

# All graphs authorized for regorg:RegisteredOrganization (see config/authorization/config.lisp),
# so no dangling org:classification survives the code deletion in the next migration.
DELETE {
  GRAPH ?g { ?org org:classification ?legacy . }
}
INSERT {
  GRAPH ?g { ?org org:classification <http://data.vlaanderen.be/id/concept/GeregistreerdeOrganisatieClassificatieCode/7a199d27-31c3-44bb-a58f-b3a64673a8b6> . }
}
WHERE {
  VALUES ?g {
    <http://mu.semte.ch/graphs/administrative-unit>
    <http://mu.semte.ch/graphs/shared>
    <http://mu.semte.ch/graphs/worship-service>
  }
  VALUES ?legacy {
    <http://data.vlaanderen.be/id/concept/GeregistreerdeOrganisatieClassificatieCode/3e5c8e30-95a7-47b0-b0a4-210d5bd440a7>
    <http://data.vlaanderen.be/id/concept/GeregistreerdeOrganisatieClassificatieCode/b9ed22af-3661-4c3e-b07f-b641d80ebf61>
  }
  GRAPH ?g { ?org org:classification ?legacy . }
}
