CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  VALUES ?p {
    <http://data.lblod.info/vocabularies/contacthub/startdatum>
    <http://data.lblod.info/vocabularies/contacthub/eindedatum>
    <http://data.lblod.info/vocabularies/erediensten/geplandeEinddatumAanstelling>
    <http://data.lblod.info/vocabularies/leidinggevenden/adresRegisterId>
    <http://data.lblod.info/vocabularies/leidinggevenden/heeftBestuursfunctie>
    <http://data.vlaanderen.be/ns/besluit#bestuurt>
    <http://data.vlaanderen.be/ns/besluit#werkingsgebied>
    <http://data.vlaanderen.be/ns/mandaat#aantalHouders>
    <http://data.vlaanderen.be/ns/mandaat#beleidsdomein>
    <http://data.vlaanderen.be/ns/mandaat#bindingEinde>
    <http://data.vlaanderen.be/ns/mandaat#bindingStart>
    <http://data.vlaanderen.be/ns/mandaat#einde>
    <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan>
    <http://data.vlaanderen.be/ns/mandaat#isTijdelijkVervangenDoor>
    <http://data.vlaanderen.be/ns/mandaat#rangorde>
    <http://data.vlaanderen.be/ns/mandaat#start>
    <http://data.vlaanderen.be/ns/mandaat#status>
    <https://data.vlaanderen.be/ns/generiek#isTijdspecialisatieVan>
    <https://data.vlaanderen.be/ns/persoon#gebruikteVoornaam>
    <http://mu.semte.ch/vocabularies/core/uuid>
    <http://mu.semte.ch/vocabularies/ext/secondaryContactPoint>
    <http://mu.semte.ch/vocabularies/ext/werkingsgebiedNiveau>
    <http://schema.org/contactPoint>
    <http://schema.org/contactType>
    <http://schema.org/email>
    <http://schema.org/faxNumber>
    <http://schema.org/telephone>
    <http://schema.org/url>
    <http://www.w3.org/2000/01/rdf-schema#label>
    <http://www.w3.org/2004/02/skos/core#altLabel>
    <http://www.w3.org/2004/02/skos/core#prefLabel>
    <http://www.w3.org/2004/02/skos/core#scopeNote>
    <http://www.w3.org/ns/locn#address>
    <http://www.w3.org/ns/locn#addressArea>
    <http://www.w3.org/ns/locn#adminUnit1>
    <http://www.w3.org/ns/locn#adminUnit2>
    <http://www.w3.org/ns/locn#adminUnitL2>
    <http://www.w3.org/ns/locn#fullAddress>
    <http://www.w3.org/ns/locn#postCode>
    <http://www.w3.org/ns/locn#thoroughfare>
    <http://www.w3.org/ns/org#classification>
    <http://www.w3.org/ns/org#hasMembership>
    <http://www.w3.org/ns/org#hasPost>
    <http://www.w3.org/ns/org#heldBy>
    <http://www.w3.org/ns/org#holds>
    <http://www.w3.org/ns/org#linkedTo>
    <http://www.w3.org/ns/org#memberOf>
    <http://www.w3.org/ns/org#organisation>
    <http://www.w3.org/ns/org#role>
    <http://xmlns.com/foaf/0.1/familyName>
    <http://xmlns.com/foaf/0.1/givenName>
    <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer>
    <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer>
    <https://data.vlaanderen.be/ns/adres#gemeentenaam>
    <https://data.vlaanderen.be/ns/adres#land>
    <https://data.vlaanderen.be/ns/adres#postcode>
    <https://data.vlaanderen.be/ns/adres#verwijstNaar>
    <https://www.w3.org/ns/regorg#legalName>
  }

  ?s ?p ?o .
}
