DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/betrokkenLokaleBesturen/623B1D5CB72F9F4B3350823E> ?p ?o.
  }
}

;

DELETE WHERE {
  graph <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/bestuurseenheden/a3bd0845853278f478f90b14436d3efa99e73249a84d462f0ddc2e5b6e37a156> <http://data.lblod.info/vocabularies/erediensten/betrokkenBestuur> <http://data.lblod.info/id/betrokkenLokaleBesturen/623B1D5CB72F9F4B3350823E>.
  }
}
