DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuurseenheden/ba8ffc97-5490-4ecc-b24e-aab26b23c026>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/identificatoren/6e8a9d7c55868b80d176fe00db97816b>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuursorganen/be697a9b-248f-431e-90cd-474ee79a5c6a>
    <http://data.lblod.info/id/bestuursorganen/dddb39fb-a19b-491b-b1bf-a431406e383f>
    <http://data.lblod.info/id/bestuursorganen/e5645fd6-ef7b-4705-8eed-9ee7de102f8c>
    <http://data.lblod.info/id/bestuursorganen/bfc5523b-6fe8-425e-a65f-6202f73c7d42>
    <http://data.lblod.info/id/bestuursorganen/ea7ecf04-ad05-486e-b77e-437b8577b7df>
    <http://data.lblod.info/id/bestuursorganen/4824c430-9c4f-4258-842e-bd631d910377>
    <http://data.lblod.info/id/bestuursorganen/a974b0dc-cbd6-4f9b-8211-cd487c4ede35>
    <http://data.lblod.info/id/bestuursorganen/f5e8775d-b723-4fa3-9ddd-66751057ea34>
    <http://data.lblod.info/id/bestuursorganen/0c0b86269ddc09cbcffc2cb4e39f458df15265f24d7a46f3a8f45c9567a1b44d>
    <http://data.lblod.info/id/bestuursorganen/4a7c956f6d418d0031de1a1b15de74d6a87edf824f464caf02a1145b461cd1d9>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/gestructureerdeIdentificator/e6795bc0c5c2cf66591e7ff62e770bf5>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}
