DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/adressen/cb091a60-2397-11ef-bbd8-0fbcdf882161>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuursorganen/688a6c6ee994118067e951daf5ae36a61a5006727fcb245d2275c4dfd1f560df>
    <http://data.lblod.info/id/bestuursorganen/26ad3d6848a85b60ddf95c1abf0cca7cde7eaa9b62b44e04daa37eb99c951dbe>
    <http://data.lblod.info/id/bestuursorganen/8ed710c24ece66d6aa9f31ca209d89cba2070521c74cdb7fed9149c2a08553f8>
    <http://data.lblod.info/id/bestuursorganen/2a6533fc650e80a10af547dedde0eb162eda0715835fb056f265da847d88a154>
    <http://data.lblod.info/id/bestuursorganen/3cc108abec6c37a6e56fc04d78ba162a3c8412b0507711b576945d146bac3b32>
    <http://data.lblod.info/id/bestuursorganen/7bacffa8fb9d5d83b16ab5c79d6c52e6f5bb11941eb9256d993c5ef091ed9211>
    <http://data.lblod.info/id/bestuursorganen/02b9d64da7cf5c9ef20b3b036400aeb2c5fc7078ee0b0cb0b9429ca07ad5c93c>
    <http://data.lblod.info/id/bestuursorganen/2df471c3c8a592d527220d612538e4cc3d722398d80e28d159c0ce3417a7c382>
    <http://data.lblod.info/id/bestuursorganen/d0ff01118d5b6aee2260754bd14bbd59c6b2347dd3501d501bfae4def2a22032>
    <http://data.lblod.info/id/bestuursorganen/8075960c2054f38245e14c106d276ed8ca90ad67d89c68d0d89253d2f576b748>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuursfuncties/0da9c13a61c6a7d9b1585573607aa1910bab5a0cb4694d2039db72de34a9aa72>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/kboOrganisaties/cb091a64-2397-11ef-bbd8-0fbcdf882161>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/identificatoren/06f4d030-834a-11ee-8e4b-c582e0b3e4df>
    <http://data.lblod.info/id/identificatoren/c23b22d46df71b01700172c440cef58b>
    <http://data.lblod.info/id/identificatoren/cb091a62-2397-11ef-bbd8-0fbcdf882161>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/bestuurseenheden/9af828073bb4c53989fe0693526a31aec47d85a4bc6ac9d485ca6878eb3b3f1c>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/contact-punten/cb091a61-2397-11ef-bbd8-0fbcdf882161>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}

;

DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
}
WHERE {
  VALUES ?s {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/06f4d031-834a-11ee-8e4b-c582e0b3e4df>
    <http://data.lblod.info/id/gestructureerdeIdentificator/7fdaf88760a2fe54f93281fbd815aa40>
    <http://data.lblod.info/id/gestructureerdeIdentificator/cb091a63-2397-11ef-bbd8-0fbcdf882161>
  }

  GRAPH ?g {
    ?s ?p ?o .
  }
}
