PREFIX org: <http://www.w3.org/ns/org#>
PREFIX dc_terms: <http://purl.org/dc/terms/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?org a dc_terms:Agent .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    ?org a org:Organization .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    ?org a dc_terms:Agent .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    ?org a org:Organization .
  }
}

INSERT {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?org a dc_terms:Agent .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?org a org:Organization .
  }
}
