PREFIX org: <http://www.w3.org/ns/org#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX schema: <http://schema.org/>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX euro: <http://data.europa.eu/m8g/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX organisatie: <https://data.vlaanderen.be/ns/organisatie#>
PREFIX persoon: <https://data.vlaanderen.be/ns/persoon#>
PREFIX adres: <https://data.vlaanderen.be/ns/adres#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX lblodlg: <http://data.lblod.info/vocabularies/leidinggevenden/>
PREFIX dc_terms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX euvoc: <http://publications.europa.eu/ontology/euvoc#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX ch: <http://data.lblod.info/vocabularies/contacthub/>
PREFIX code: <http://lblod.data.gift/vocabularies/organisatie/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE {
  GRAPH ?g {
    ?address locn:fullAddress ?fullAddress .
  }
} WHERE {
  GRAPH ?g {
    ?address locn:fullAddress ?fullAddress .
  }
};

INSERT {
  GRAPH ?g {
    ?address locn:fullAddress ?fullAddress .
  }
} WHERE {
  GRAPH ?g {
    ?address
      a locn:Address;
      locn:thoroughfare ?straatnaam;
      adres:Adresvoorstelling.huisnummer ?huisnummer;
      locn:postCode ?postcode;
      adres:gemeentenaam ?gemeentenaam;
      adres:land ?land .

    OPTIONAL {
      ?address adres:Adresvoorstelling.busnummer ?busnummer .
    }

    BIND(IF(BOUND(?busnummer), CONCAT(?straatnaam, " ", ?huisnummer, " ", ?busnummer, ", ", ?postcode, " ", ?gemeentenaam, ", ", ?land), CONCAT(?straatnaam, " ", ?huisnummer, ", ", ?postcode, " ", ?gemeentenaam, ", ", ?land)) AS ?fullAddress)
  }
};

