
      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "2200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Augustijnenlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herentals";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Augustijnenlaan 30, 2200 Herentals, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0872086121".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "14";
            
            <http://www.w3.org/ns/locn#postCode> "3540";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Pikkeleerstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herk-de-Stad";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pikkeleerstraat 14, 3540 Herk-de-Stad, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537728111".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "17";
            
            <http://www.w3.org/ns/locn#postCode> "1540";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Centrum";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herne";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Centrum 17, 1540 Herne, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0809154303".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2230";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herselt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkstraat 1, 2230 Herselt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881917070".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "20";
            
            <http://www.w3.org/ns/locn#postCode> "9550";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herzele";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 20, 9550 Herzele, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0875059665".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            
            
            <http://www.w3.org/ns/locn#postCode> "1560";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Jan van Ruusbroecpark";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hoeilaart";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Jan van Ruusbroecpark , 1560 Hoeilaart, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0816874414".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "3530";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Pastorijstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Houthalen-Helchteren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pastorijstraat 30, 3530 Houthalen-Helchteren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0898822982".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "3530";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Pastorijstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Houthalen-Helchteren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pastorijstraat 30, 3530 Houthalen-Helchteren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0811923652".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2540";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Geelhandlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hove";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Geelhandlaan 1, 2540 Hove, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0834868508".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "2235";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Prof. Dr. Vital Celenplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hulshout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Prof. Dr. Vital Celenplein 2, 2235 Hulshout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0809823801".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "34";
            
            <http://www.w3.org/ns/locn#postCode> "8900";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ieper";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 34, 8900 Ieper, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0880696553".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "34";
            
            <http://www.w3.org/ns/locn#postCode> "8900";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ieper";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 34, 8900 Ieper, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877643330".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "8870";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Prins Albertlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Izegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Prins Albertlaan 3, 8870 Izegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0207559115".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "13";
            
            <http://www.w3.org/ns/locn#postCode> "2920";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkeneind";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kalmthout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkeneind 13, 2920 Kalmthout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0666563610".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "130";
            
            <http://www.w3.org/ns/locn#postCode> "2950";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Bruggeske";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kapellen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bruggeske 130, 2950 Kapellen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643817110".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9970";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Veld";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kaprijke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Veld 1, 9970 Kaprijke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643818692".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "3140";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeenteplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Keerbergen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeenteplein 10, 3140 Keerbergen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877654713".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "146";
            
            <http://www.w3.org/ns/locn#postCode> "3640";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Breeërsteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kinrooi";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Breeërsteenweg 146, 3640 Kinrooi, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878368058".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8300";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Alfred Verweeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Knokke-Heist";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Alfred Verweeplein 1, 8300 Knokke-Heist, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0892000419".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8300";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Alfred Verweeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Knokke-Heist";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Alfred Verweeplein 1, 8300 Knokke-Heist, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?adminUnit <http://www.w3.org/2004/02/skos/core#prefLabel> "Vrijetijdsbedrijf Knokke-Heist AG".
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "303";
            
            <http://www.w3.org/ns/locn#postCode> "8670";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Zeelaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Koksijde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Zeelaan 303, 8670 Koksijde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267390495".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2550";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeenteplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kontich";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeenteplein 1, 2550 Kontich, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871968335".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "35";
            
            <http://www.w3.org/ns/locn#postCode> "3470";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortenaken";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsplein 35, 3470 Kortenaken, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0535811469".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "54";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 54, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0365251025".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "11";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 11, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267307650".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "54";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 54, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0893104140".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "20";
            
            <http://www.w3.org/ns/locn#postCode> "9150";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "O.L.Vrouwplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kruibeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "O.L.Vrouwplein 20, 9150 Kruibeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878836925".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            
            <http://www.w3.org/ns/locn#postCode> "2430";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Laakdal";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkstraat 21, 2430 Laakdal, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0652972425".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "4";
            <http://www.w3.org/ns/locn#postCode> "3620";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Aan De Engelse Hof";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lanaken";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Aan De Engelse Hof 10 - 4, 3620 Lanaken, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871907561".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "29";
            
            <http://www.w3.org/ns/locn#postCode> "3400";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Stationsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Landen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stationsstraat 29, 3400 Landen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0820480141".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9280";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Flor Hofmanslaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lebbeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Flor Hofmanslaan 1, 9280 Lebbeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0897939886".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8860";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lendelede";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsplein 1, 8860 Lendelede, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0841352165".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Professor Roger Van Overstraetenplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Leuven";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Professor Roger Van Overstraetenplein 1, 3000 Leuven, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870310526".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Professor Roger Van Overstraetenplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Leuven";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Professor Roger Van Overstraetenplein 1, 3000 Leuven, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0896728376".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Professor Roger Van Overstraetenplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Leuven";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Professor Roger Van Overstraetenplein 1, 3000 Leuven, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?adminUnit <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB LEUVEN (Parkeerbedrijf)".
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "7";
            <http://www.w3.org/ns/locn#postCode> "2500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Paradeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lier";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Paradeplein 2 - 7, 2500 Lier, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866000162".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "44";
            
            <http://www.w3.org/ns/locn#postCode> "2275";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Rechtestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lille";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Rechtestraat 44, 2275 Lille, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0879926689".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3920";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Hertog Janplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lommel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hertog Janplein 1, 3920 Lommel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0882833820".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3920";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Hertog Janplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lommel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hertog Janplein 1, 3920 Lommel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871485513".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3680";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maaseik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 1, 3680 Maaseik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0828259640".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3680";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maaseik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 1, 3680 Maaseik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0887694015".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "239";
            
            <http://www.w3.org/ns/locn#postCode> "3630";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Heirstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maasmechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Heirstraat 239, 3630 Maasmechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0882009815".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "7";
            
            <http://www.w3.org/ns/locn#postCode> "9990";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Marktstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maldegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Marktstraat 7, 9990 Maldegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870672097".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 21, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871106718".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "1";
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 21 - 1, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0843922170".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 21, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0546688337".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "44";
            
            <http://www.w3.org/ns/locn#postCode> "3670";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oudsbergen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsstraat 44, 3670 Oudsbergen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0837447619".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8930";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Menen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 1, 8930 Menen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862941197".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "1785";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Nieuwstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Merchtem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Nieuwstraat 1, 1785 Merchtem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0824869093".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "353";
            
            <http://www.w3.org/ns/locn#postCode> "9820";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Hundelgemsesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Merelbeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hundelgemsesteenweg 353, 9820 Merelbeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0661984022".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2330";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Merksplas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 1, 2330 Merksplas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0832586335".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8430";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Spermaliestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Middelkerke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Spermaliestraat 1, 8430 Middelkerke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0890434957".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2640";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Stadsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mortsel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stadsplein 1, 2640 Mortsel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885082438".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9810";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorp";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Nazareth";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorp 1, 9810 Nazareth, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643819583".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2845";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Niel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsstraat 1, 2845 Niel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877222567".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "7";
            
            <http://www.w3.org/ns/locn#postCode> "8620";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Marktplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Nieuwpoort";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Marktplein 7, 8620 Nieuwpoort, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0894194401".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "7";
            
            <http://www.w3.org/ns/locn#postCode> "8620";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Marktplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Nieuwpoort";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Marktplein 7, 8620 Nieuwpoort, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0633829969".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "2560";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Nijlen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkstraat 4, 2560 Nijlen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863925550".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "9400";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Parklaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ninove";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Parklaan 3, 9400 Ninove, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877586912".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2250";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorp";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Olen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorp 1, 2250 Olen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0894234288".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
