DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://www.w3.org/ns/dcat#Dataset> ;
      <http://purl.org/dc/terms/subject> <http://data.lblod.info/datasets/delta-producer/dumps/AdministrativeUnitsCacheGraphDump> ;
      ?p ?o .
  }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://vocab.deri.ie/cogs#Job> ;
      <http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/deltaDumpFileCreation/administrative-units> ;
      ?p ?o .
  }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://vocab.deri.ie/cogs#Job> ;
      <http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/initialPublicationGraphSyncing/administrative-units> ;
      ?p ?o .
  }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://vocab.deri.ie/cogs#Job> ;
      <http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/healingOperation/administrative-units> ;
      ?p ?o .
  }
}
;
DELETE {
  GRAPH ?g {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH ?g {
    ?s a <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject> ;
      <http://purl.org/dc/terms/publisher> <http://data.lblod.info/services/delta-production-json-diff-file-manager/administrative-units> ;
      ?p ?o .
  }
}
;
CLEAR GRAPH <http://redpencil.data.gift/id/deltas/producer/administrative-units>
