PREFIX core: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX lblodorg: <http://lblod.data.gift/vocabularies/organisatie/>

DELETE WHERE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    ?event a org:ChangeEvent ;
           core:uuid "65699ADF6DEE214B7207D42F" ;
           lblodorg:veranderingsgebeurtenisResultaat ?result ;
           ?ep ?eo .

    ?result a lblodorg:VeranderingsgebeurtenisResultaat ;
            ?rp ?ro .
  }
}
