delete {
graph <http://mu.semte.ch/graphs/organisatieportaal> {
    ?s <http://xmlns.com/foaf/0.1/givenName> ?givenName.
  }
}

insert {
graph <http://mu.semte.ch/graphs/organisatieportaal> {
     ?s <http://xmlns.com/foaf/0.1/givenName> "André".
}
}

where {
graph <http://mu.semte.ch/graphs/organisatieportaal> {
    ?s  <http://xmlns.com/foaf/0.1/givenName> ?givenName.

    FILTER (?s in(
         <http://data.lblod.info/id/personen/6246DD30D5CA8D65E42B3030>,
         <http://data.lblod.info/id/personen/62384F97B72F9F4B33508056>,
         <http://data.lblod.info/id/personen/6246DDA3D5CA8D65E42B3031>,
         <http://data.lblod.info/id/personen/623993F1B72F9F4B3350808E>
    ))
}

}
