delete {
  graph ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://data.lblod.info/vocabularies/contacthub/typeWijziging>
    <http://lblod.data.gift/concepts/3dd7550843eaf18e1fa1ca6c6c3f2610>.
  }
}
insert {
  graph ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://data.lblod.info/vocabularies/contacthub/typeWijziging>
    <http://lblod.data.gift/concepts/9f19f14910245f9b14737f1f1a2067f2>.

  }
}
where {
  graph ?g {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/6380DDD34B5FEAF28DEDE982> <http://data.lblod.info/vocabularies/contacthub/typeWijziging>
      <http://lblod.data.gift/concepts/3dd7550843eaf18e1fa1ca6c6c3f2610>.
  }
}
