prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos:	<http://www.w3.org/2004/02/skos/core#> 
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>



INSERT {
 graph ?g {

  ?code a <http://mu.semte.ch/vocabularies/ext/OrganizationClassificationCode>.
  
 }
}
WHERE {
 graph ?g {

    ?code a ?type.
    filter (?type in (<http://mu.semte.ch/vocabularies/ext/RepresentatieveOrgaanClassificatieCode>, 
                     <http://lblod.data.gift/vocabularies/organisatie/BestuurseenheidClassificatieCode>))
    
 }

}
