
      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "9";
            
            <http://www.w3.org/ns/locn#postCode> "9300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Werf";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalst";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Werf 9, 9300 Aalst, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0829241320".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "9";
            
            <http://www.w3.org/ns/locn#postCode> "9300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Werf";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalst";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Werf 9, 9300 Aalst, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0543527226".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "22";
            
            <http://www.w3.org/ns/locn#postCode> "9880";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Europalaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalter";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Europalaan 22, 9880 Aalter, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0891176315".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Ten Drossaarde";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aarschot";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ten Drossaarde 1, 3200 Aarschot, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881848972".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "22";
            
            <http://www.w3.org/ns/locn#postCode> "3200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Ten Drossaarde";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aarschot";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ten Drossaarde 22, 3200 Aarschot, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0544646981".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "25";
            
            <http://www.w3.org/ns/locn#postCode> "2000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 25, 2000 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267396039".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "25";
            
            <http://www.w3.org/ns/locn#postCode> "2018";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Paradeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Paradeplein 25, 2018 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267402076".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 1, 2000 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0820307620".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "71-73";
            
            <http://www.w3.org/ns/locn#postCode> "2000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Frankrijklei";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Frankrijklei 71-73, 2000 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0824037071".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "139";
            
            <http://www.w3.org/ns/locn#postCode> "2140";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Turnhoutsebaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Turnhoutsebaan 139, 2140 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0834660452".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "15";
            
            <http://www.w3.org/ns/locn#postCode> "8850";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Polenplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ardooie";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Polenplein 15, 8850 Ardooie, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878654407".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "29";
            
            <http://www.w3.org/ns/locn#postCode> "2370";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Vrijheid";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Arendonk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Vrijheid 29, 2370 Arendonk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505848961".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "1730";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeenteplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Asse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeenteplein 1, 1730 Asse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0876249005".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1-3";
            
            <http://www.w3.org/ns/locn#postCode> "9960";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kasteelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Assenede";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kasteelstraat 1-3, 9960 Assenede, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0812330062".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "31";
            
            <http://www.w3.org/ns/locn#postCode> "2340";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Rerum Novarumlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Beerse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Rerum Novarumlaan 31, 2340 Beerse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0842894861".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1046";
            
            <http://www.w3.org/ns/locn#postCode> "1652";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Alsembergsteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Beersel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Alsembergsteenweg 1046, 1652 Beersel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878129617".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "3360";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bierbeek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsstraat 2, 3360 Bierbeek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885850718".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3740";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Deken Paquayplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bilzen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Deken Paquayplein 1, 3740 Bilzen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0888873653".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8370";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "J.F. Kennedyplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Blankenberge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "J.F. Kennedyplein 1, 8370 Blankenberge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877301751".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "16";
            
            <http://www.w3.org/ns/locn#postCode> "3950";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bocholt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsstraat 16, 3950 Bocholt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0807465513".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "91";
            
            <http://www.w3.org/ns/locn#postCode> "2530";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Heuvelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Boechout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Heuvelstraat 91, 2530 Boechout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0547988929".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "2820";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Jacques Morrensplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bonheiden";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Jacques Morrensplein 10, 2820 Bonheiden, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881524122".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "44";
            
            <http://www.w3.org/ns/locn#postCode> "2850";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Antwerpsestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Boom";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Antwerpsestraat 44, 2850 Boom, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862976336".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "3190";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Pastorijstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Boortmeerbeek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pastorijstraat 2, 3190 Boortmeerbeek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0864141227".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "3840";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Speelhof";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Borgloon";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Speelhof 10, 3840 Borgloon, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0820533292".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "13";
            
            <http://www.w3.org/ns/locn#postCode> "2880";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Hingenesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bornem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hingenesteenweg 13, 2880 Bornem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0877556624".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "182";
            
            <http://www.w3.org/ns/locn#postCode> "2930";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Bredabaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brasschaat";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bredabaan 182, 2930 Brasschaat, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878670837".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "76";
            
            <http://www.w3.org/ns/locn#postCode> "8450";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kapelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bredene";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kapelstraat 76, 8450 Bredene, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0874963754".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "23";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "bus 1";
            <http://www.w3.org/ns/locn#postCode> "3960";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Witte Torenwal";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bree";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Witte Torenwal 23 - bus 1, 3960 Bree, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871439585".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "12";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Burg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Burg 12, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?adminUnit <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB BRUGGE".
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            
            <http://www.w3.org/ns/locn#postCode> "8660";
            <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Zeelaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "De Panne";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Zeelaan 21, 8660 De Panne, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0843511307".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "9800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Brielstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Deinze";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Brielstraat 2, 9800 Deinze, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0837741785".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "11";
            
            <http://www.w3.org/ns/locn#postCode> "9200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Franz Courtensstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Dendermonde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Franz Courtensstraat 11, 9200 Dendermonde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0882924979".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "14";
            
            <http://www.w3.org/ns/locn#postCode> "3590";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Dorpsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Diepenbeek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dorpsstraat 14, 3590 Diepenbeek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885640088".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3290";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Diest";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Markt 1, 3290 Diest, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0895494003".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3290";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Nijverheidslaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Diest";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Nijverheidslaan 1, 3290 Diest, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0845332432".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "21";
            
            <http://www.w3.org/ns/locn#postCode> "2570";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeentestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Duffel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeentestraat 21, 2570 Duffel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0544582447".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2650";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Gemeenteplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Edegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gemeenteplein 1, 2650 Edegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505867272".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "23";
            
            <http://www.w3.org/ns/locn#postCode> "2910";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Heuvelplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Essen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Heuvelplein 23, 2910 Essen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0890708339".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "11";
            
            <http://www.w3.org/ns/locn#postCode> "9940";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Fortune De Kokerlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Evergem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Fortune De Kokerlaan 11, 9940 Evergem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878328763".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "20";
            
            <http://www.w3.org/ns/locn#postCode> "2440";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Werft";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Geel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Werft 20, 2440 Geel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0876030556".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "32";
            
            <http://www.w3.org/ns/locn#postCode> "2440";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Werft";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Geel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Werft 32, 2440 Geel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537631705".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Stadsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Genk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stadsplein 1, 3600 Genk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0872093742".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Voldersstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Voldersstraat 1, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0367300594".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Botermarkt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Botermarkt 1, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537522332".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Botermarkt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Botermarkt 1, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537520055".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "20";
            
            <http://www.w3.org/ns/locn#postCode> "9500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Weverijstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Geraardsbergen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Weverijstraat 20, 9500 Geraardsbergen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0879188796".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "33";
            
            <http://www.w3.org/ns/locn#postCode> "3380";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Grotestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Glabbeek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grotestraat 33, 3380 Glabbeek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537864307".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "1755";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Koekoekstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gooik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Koekoekstraat 2, 1755 Gooik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0895112436".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "1850";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Prinsenstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Grimbergen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Prinsenstraat 3, 1850 Grimbergen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0831016024".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "85";
            
            <http://www.w3.org/ns/locn#postCode> "3150";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Wespelaarsesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Haacht";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Wespelaarsesteenweg 85, 3150 Haacht, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866021938".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "14";
            
            <http://www.w3.org/ns/locn#postCode> "3545";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Halen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 14, 3545 Halen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0842479642".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "9220";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen";
            <http://www.w3.org/ns/locn#thoroughfare> "Marktplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hamme";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Marktplein 1, 9220 Hamme, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0265753274".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "40";
            
            <http://www.w3.org/ns/locn#postCode> "3930";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Stad";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hamont-Achel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stad 40, 3930 Hamont-Achel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0827418710".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Limburg";
            <http://www.w3.org/ns/locn#thoroughfare> "Limburgplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hasselt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Limburgplein 1, 3500 Hasselt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0864952958".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "17";
            
            <http://www.w3.org/ns/locn#postCode> "2220";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Heist-op-den-Berg";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkplein 17, 2220 Heist-op-den-Berg, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0888322238".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "2620";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Sint-Bernardusabdij";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hemiksem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Sint-Bernardusabdij 1, 2620 Hemiksem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0640725679".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6";
            
            <http://www.w3.org/ns/locn#postCode> "3020";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant";
            <http://www.w3.org/ns/locn#thoroughfare> "Spoorwegstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Spoorwegstraat 6, 3020 Herent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0845210389".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "2200";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Augustijnenlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Herentals";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Augustijnenlaan 30, 2200 Herentals, België".
        }
      }
      WHERE {
        GRAPH ?g {
          
        ?structuredId <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0872383257".
        ?identificator <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredId.
        ?adminUnit <http://www.w3.org/ns/adms#identifier> ?identificator.
        ?adminUnit <http://www.w3.org/ns/org#hasPrimarySite> ?site.
        ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?addressUriREAL.
        BIND( ?addressUriREAL AS ?addressUri)
      
        }
      }
