DELETE {
  graph <http://mu.semte.ch/graphs/public> {
    ?instance rdf:type ?oldClass
  }
}
INSERT {
  graph <http://mu.semte.ch/graphs/public>{
    ?instance rdf:type ?newClass
  }
}
where { 
  graph <http://mu.semte.ch/graphs/public>{
    BIND (<http://lblod.data.gift/vocabularies/organisatie/BedienaarFinanceringCode> as ?oldClass)
    BIND (<http://lblod.data.gift/vocabularies/organisatie/BedienaarFinancieringCode> as  ?newClass)
   ?instance rdf:type ?oldClass . 
  }
}