DELETE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/mandatarissen/fb8ce507f9dfc141e8353d33a7c0070f> ?p ?o .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/worship-service> {
    <http://data.lblod.info/id/mandatarissen/fb8ce507f9dfc141e8353d33a7c0070f> ?p ?o .
  }
}
