

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/02c2bc6e15785114f5526b1ab5d29c6049e664bc6a5fab8bb27ae75ac4ad25c2> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003709>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/b5dc37cf-011e-4e44-a797-9fd59bc8bf61> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003709".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/b5dc37cf-011e-4e44-a797-9fd59bc8bf61> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/03c466beb217e884d90f62a2d78674cf6403c2671f9b4517e1aa8b93ed8aa41b> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003310>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/79e89e4f-c4b2-44b8-9c40-761220f05345> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003310".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/79e89e4f-c4b2-44b8-9c40-761220f05345> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/0f316807-839b-4554-a4d8-8656e9f83201> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO025850>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/565745e8-f2dd-4545-9d0e-18ff0be8bec4> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025850".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/565745e8-f2dd-4545-9d0e-18ff0be8bec4> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/bb58563c6b5d4ca1ebb32e72c137b9b9500369c6cd8a37d177ed6365bfd31484> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO052255>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/aeef546d-bf5f-431f-aad3-a917bc04b56d> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO052255".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/aeef546d-bf5f-431f-aad3-a917bc04b56d> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/24904455b8208a966475e0f6eeb1af64e688779f30edf2e56f582fdc5907f082> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003311>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/4501c6f2-b50d-4486-b495-14d4a2483dc6> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003311".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/4501c6f2-b50d-4486-b495-14d4a2483dc6> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/ebc8589470b92ac994448573f072f7a0408e4ab893364ed118fd65537c3b9ed0> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003301>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/ce6dd74d-f5ca-49d5-9aa8-9cbe41bab4d4> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003301".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/ce6dd74d-f5ca-49d5-9aa8-9cbe41bab4d4> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/469298eac85cce8381c45c07c150cfaf104e55e465a2100155f802d105ee284b> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003309>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/2c40e905-aa52-43ed-9023-a22d91eb94e1> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003309".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/2c40e905-aa52-43ed-9023-a22d91eb94e1> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/b27a3032161dde49a0014809982dc41f12b32d93195611b4fcbe6bc21c36162f> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO025332>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/cb47a5a6-d947-4908-ba91-d8a887711c7e> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025332".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/cb47a5a6-d947-4908-ba91-d8a887711c7e> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/5202c9ba-40fb-44e2-8116-6eceadc1e60a> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO052351>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/a57287d4-f37b-4936-824b-7cc80fe73192> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO052351".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/a57287d4-f37b-4936-824b-7cc80fe73192> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/ca68202ecd1d5ce242c56444eadc6662844394e568180dfb011fac1d72078b1b> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003380>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/f37eb949-ef75-4a6f-9889-4998d27d49ee> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003380".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/f37eb949-ef75-4a6f-9889-4998d27d49ee> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/686e3c12c1be2a8ead91fca38652b40f11e3f62752631d6bbc6746d686f4f661> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO025333>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/05ee9f7d-525e-4e4b-acf8-17a78e90a8d7> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025333".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/05ee9f7d-525e-4e4b-acf8-17a78e90a8d7> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/abd55b65c3192a96451b1ed25e1f2b694ea193ed28e0380ad4d7bdcf183226e5> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO002964>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/4b492245-dccc-4454-82eb-bc021c43a195> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO002964".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/4b492245-dccc-4454-82eb-bc021c43a195> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/4c6a1597c80c61844bafbb4577a83a05babe77b6ac90811a5784c5e689f9d8ae> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO025331>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/6c338d33-52e8-431c-a094-439dd38cc8be> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025331".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/6c338d33-52e8-431c-a094-439dd38cc8be> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/3ebc33e54a7b6908651014c5a90594c311d76ca29b00c03bc6a4cbf07a5f5796> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003305>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/a9996594-b5de-490c-8e22-8c88290f3f9f> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003305".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/a9996594-b5de-490c-8e22-8c88290f3f9f> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/1aabd6b049a964c3d11df43e787bf9b278500df3c3e55302997748359b9b7081> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO025385>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/46ccab89-ff20-4f52-a277-50c8a0e6c027> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO025385".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/46ccab89-ff20-4f52-a277-50c8a0e6c027> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/93da82a640436139987d3bbf2cccf7468ce357e6bd93f223e4045583a669052a> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003300>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/217af079-a0fc-43f2-911e-801027627957> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003300".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/217af079-a0fc-43f2-911e-801027627957> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/a1d72f5d4763982035e10c5e071c114d2db743717af82a92da0b296cf8a02082> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO018769>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/aa8104ef-2d39-401f-8e65-71cec0d693df> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO018769".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/aa8104ef-2d39-401f-8e65-71cec0d693df> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/9805c75c20f76bbeae11240e0e51644d48a141a41d6ba2c2fe8a52eb8094894d> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO015130>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/801d1316-45f8-45f7-81d1-bbe165e35a75> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO015130".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/801d1316-45f8-45f7-81d1-bbe165e35a75> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/462c152b4e3f8c6b831e4d6ffb727c112797e3e927ca6ef361296f117d2eede9> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003324>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/2895a50d-74c5-4f04-898b-8eeacfa0647b> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003324".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/2895a50d-74c5-4f04-898b-8eeacfa0647b> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/6b7176c419ba01cb0e13fb6f03bc2b2b4807787781ec6ef4b53042cdca9c510d> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003299>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/a2573b87-af08-484b-a46f-ebcb7a3f0944> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003299".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/a2573b87-af08-484b-a46f-ebcb7a3f0944> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/6f55c7250419fd7b00aefa818665acb069243d95219be598a962ae19e463fe56> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO052350>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/382d2504-d954-4e5b-b469-5314a6ceb57a> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO052350".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/382d2504-d954-4e5b-b469-5314a6ceb57a> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }

    INSERT DATA {
      GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
        <http://data.lblod.info/id/bestuurseenheden/edc85ae64bd6a8ed73aa98750904f14dcb7e9445d4003f9e970db7a65a2076f4> <http://www.w3.org/2002/07/owl#sameAs> <http://data.vlaanderen.be/id/organisatie/OVO003297>  . 
        <http://data.lblod.info/id/gestructureerdeIdentificatoren/764c6929-70c5-440e-93be-48609959ecdb> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "OVO003297".
      }
    }
    DELETE WHERE {
       GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          <http://data.lblod.info/id/gestructureerdeIdentificatoren/764c6929-70c5-440e-93be-48609959ecdb> <https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .
      }
    }
