DELETE {
  GRAPH ?g {
  ?s <http://schema.org/telephone> ?o .
  }
}
INSERT {
 GRAPH ?g {
   ?s <http://schema.org/telephone> ?newPhoneNumber .
 }
}
WHERE {
  GRAPH ?g {
    ?s <http://schema.org/telephone> ?o .
  }
  
  FILTER (SUBSTR(?o, 1, 1) != "+" AND STRLEN(STR(?o)) > 4)
  BIND(REPLACE(STR(?o),"[. - /]","") AS ?removedSpaces) .
  BIND (CONCAT('tel:+32', SUBSTR(?removedSpaces, 2)) as ?newPhoneNumber)
}
;
DELETE {
  GRAPH ?g {
  ?s <http://schema.org/telephone> ?o .
  }
}
INSERT {
 GRAPH ?g {
   ?s <http://schema.org/telephone> ?newPhoneNumber .
 }
}
WHERE {
  GRAPH ?g {
    ?s <http://schema.org/telephone> ?o .
  }
  
  FILTER (SUBSTR(?o, 1, 1) = "+")
  BIND(REPLACE(STR(?o),"[. - /]","") AS ?removedSpaces) .
  BIND (CONCAT('tel:', ?removedSpaces, 2) as ?newPhoneNumber)
}



