DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Begijnendijk ".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Begijnendijk".
  }
}

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Beleko ".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Beleko".
  }
}

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Pelt ".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB Pelt".
  }
}

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB  voor infrastructuur- en patrimoniumbeheer Turnhout".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "AGB voor infrastructuur- en patrimoniumbeheer Turnhout".
  }
}

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "Stadsontwikkelingsbedrijf Kortrijk ".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "Stadsontwikkelingsbedrijf Kortrijk".
  }
}

DELETE {
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "Stedelijk Parkeerbedrijf van de stad Gent ".
  }
}
INSERT { 
  GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
    <http://data.lblod.info/id/bestuurseenheden/e852a0c8-e610-4359-9d8f-baa42e1bf5cf> <http://www.w3.org/2004/02/skos/core#prefLabel> "Stedelijk Parkeerbedrijf van de stad Gent".
  }
}