PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?s ?p ?o .
  }
} INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/shared> {
    ?s ?p ?o .
    VALUES ?p {
      geo:sfWithin
      skos:exactMatch
    }
  }
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a prov:Location .
  }
}
