      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0685516024" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0809699184" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696665975" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689553994" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0686537789" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0875376696" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267393663" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696899963" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0694597697" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0711824305" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684891363" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0212165922" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698838775" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0687742074" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0712777279" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684493762" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0688812935" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0735627214" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0630835639" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871009916" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0680439360" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698817989" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0697787118" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0729523736" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0462239939" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871206587" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881291322" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0242469910" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0266559859" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473908049" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262925527" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505931808" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885714720" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862382656" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0666615870" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926319" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537951706" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926616" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    
