      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0663810590" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329989" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0466193777" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878405769" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0479985593" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0873440458" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865506155" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0897191602" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821734213" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870757023" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0475777476" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267386438" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472222625" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0883325451" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865013039" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865010069" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473360790" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871619135" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0870855409" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0632607670" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0887953044" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0838654674" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0471364174" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0861157387" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0476803795" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0884212804" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0848738221" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0833161902" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0472751175" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0832024923" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0644984078" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0633854022" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0566983014" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0881602118" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0263545337" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0465810133" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0781430812" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0786960406" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0780658572" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0799574166" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0800023336" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "1005154085" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0867804659" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0264998753" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866242662" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0889412695" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0874267037" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0836906793" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0834358069" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459993992" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459644990" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0823319370" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    