      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0682844465" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0445508132" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0665553622" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643926085" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0844179716" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871928743" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0807042275" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0222947570" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0894999895" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329296" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0831970978" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267404056" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0860256673" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0677764437" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0233210764" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0738896510" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267302405" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0821142117" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0827396340" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0458878195" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886198829" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267313291" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0647949706" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0664681216" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0480589567" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886485770" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267314875" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683473579" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684613726" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696715960" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0256543917" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505849852" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Vlaams-Brabant" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0467270576" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0736364909" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689674948" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "West-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683771509" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862943474" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Oost-Vlaanderen" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262562568" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      DELETE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> ?province .
        }
      }
      INSERT {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?addressUri <http://www.w3.org/ns/locn#adminUnitL2> "Limburg" .
        }
      }
      WHERE {
        GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0249211806" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .
          ?boundAddress <http://www.w3.org/ns/locn#adminUnitL2> ?province .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
