
        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3234508400" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.woonzorgnetwerkedegem.be/" .
            ?contact <http://schema.org/email> "immaculata@wznedegem.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0685516024" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3234313131" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgbedrijf.antwerpen.be/" .
            ?contact <http://schema.org/email> "klantendienst@zorgbedrijf.antwerpen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0809699184" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211550180" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorggroeplommel.be/" .
            ?contact <http://schema.org/email> "e-mailinfo@zorggroeplommel.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689553994" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3256300200" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.wzbwervik.be/" .
            ?contact <http://schema.org/email> "callcenter@wzbwervik.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0686537789" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      


        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211238700" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://welzijnsregio.be/" .
            ?contact <http://schema.org/email> "gezinszorg@welzijnsregio.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267393663" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232695100" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://wzgvoorkempen.be/" .
            ?contact <http://schema.org/email> "info@wzgvoorkempen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0694597697" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251427979" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.ztielt.be/" .
            ?contact <http://schema.org/email> "info@ztielt.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0711824305" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3256735390" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zbharelbeke.be/nl" .
            ?contact <http://schema.org/email> "onthaal@zbharelbeke.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684891363" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211697044" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgbedrijfsinttruiden.be/" .
            ?contact <http://schema.org/email> "info@zorgbedrijfsinttruiden.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0687742074" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3252365940" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://opcura.opwijk.be/" .
            ?contact <http://schema.org/email> "info@opcura.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684493762" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211492000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.houthalen-helchteren.be/zorg-houthalen-helchteren" .
            ?contact <http://schema.org/email> "info@houthalen-helchteren.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0688812935" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3256241620" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.welzijn13.be/" .
            ?contact <http://schema.org/email> "info@konektizwvl.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0630835639" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292471081" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.welzijnsband.be/" .
            ?contact <http://schema.org/email> "info@welzijnsband.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871009916" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215306997" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgbedrijfrivierenland.be/" .
            ?contact <http://schema.org/email> "info@zbrivierenland.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0680439360" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292722000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgband.be/" .
            ?contact <http://schema.org/email> "info@zorgband.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698817989" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3224470700" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgvilvoorde.be" .
            ?contact <http://schema.org/email> "info@zorgvilvoorde.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0697787118" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253764111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "http://www.asz.be/" .
            ?contact <http://schema.org/email> "info@asz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0729523736" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237606060" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://vitaz.be/" .
            ?contact <http://schema.org/email> "info@vitaz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871206587" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3212396111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azvesalius.be/" .
            ?contact <http://schema.org/email> "directiesecretariaat@azvesalius.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0242469910" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250452111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azsintjan.be/nl" .
            ?contact <http://schema.org/email> "info@azsintjan.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0266559859" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3259555297" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azsintjan.be/nl/diensten/gynaecologie-verloskunde/materniteit/campus-henri-serruys" .
            ?contact <http://schema.org/email> "cardiologie.oostende@azsintjan.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473908049" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svkleieenschelde.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885714720" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292103070" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgbedrijfmeetjesland.be/" .
            ?contact <http://schema.org/email> "info@zorgbedrijfmeetjesland.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0666615870" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3257353535" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://yperman.net/" .
            ?contact <http://schema.org/email> "info@yperman.net" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926319" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251805200" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://motena.be/nl" .
            ?contact <http://schema.org/email> "info@motena.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537951706" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292247111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.janpalfijn.be/" .
            ?contact <http://schema.org/email> "info@janpalfijngent.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926616" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250327000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.mintus.be/" .
            ?contact <http://schema.org/email> "info@mintus.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0682844465" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232187209" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.kina.be/" .
            ?contact <http://schema.org/email> "home@kina.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0445508132" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214284000" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorggroep-orion.be/" .
            ?contact <http://schema.org/email> "secretariaat@zorggroep-orion.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0665553622" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292669561" .
            
            ?contact <http://schema.org/email> "info@sociaalverhuurkantoor.gent.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643926085" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214577777" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.ziekenhuisgeel.be/" .
            ?contact <http://schema.org/email> "administratie@ziekenhuisgeel.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0844179716" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250327678" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.ocmw-brugge.be/inloophuis-t-sas" .
            ?contact <http://schema.org/email> "inloophuis@sasbrugge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871928743" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250326087" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.spoorbrugge.be/" .
            ?contact <http://schema.org/email> "info@spoorbrugge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0807042275" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214535350" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.welzijnszorgkempen.be/" .
            ?contact <http://schema.org/email> "wzk.secretariaat@iok.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0222947570" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250327240" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.maaltijdzorgplatform.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0894999895" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250327555" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.deblauwelelie.be/" .
            ?contact <http://schema.org/email> "onthaalouders@deblauwelelie.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329296" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.deschakelaar.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0831970978" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250326325" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.wokbrugge.be/" .
            ?contact <http://schema.org/email> "info@wokbrugge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267404056" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svk-brugge.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0860256673" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3293375036" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.slaatjepraatje.be/weldenderend/" .
            ?contact <http://schema.org/email> "info@slaatjepraatje.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0677764437" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3257226282" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.votjeugdhulp.be/" .
            ?contact <http://schema.org/email> "administratie@votjeugdhulp.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0233210764" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3211335511" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.jessazh.be/" .
            ?contact <http://schema.org/email> "info@jessazh.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267302405" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3222115585" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.audio-lokaal.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0827396340" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3232981470" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://beschutwonenantwerpen.be/" .
            ?contact <http://schema.org/email> "administratie@beschutwonenantwerpen.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0458878195" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3213663416​" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://heteepos.weebly.com/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886198829" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      



        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3234313131" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgbedrijfvlaanderen.be/woonzorgcentra/vesalius" .
            ?contact <http://schema.org/email> "wzc.vesalius@zorgbedrijf.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0647949706" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3238901530" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.puurs-sint-amands.be/zorgbedrijfkleinbrabant" .
            ?contact <http://schema.org/email> "info@zorgbedrijf.klein-brabant.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0664681216" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3255237411" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.ronse.be/nl/overo" .
            ?contact <http://schema.org/email> "sociaalhuis@ronse.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0480589567" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3255432700" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.najaarszon.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886485770" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237786963" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svkwaasland.be/" .
            ?contact <http://schema.org/email> "info@svkwaasland.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267314875" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237271460" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sint-gillis-waas.be/welzijn/welzijnsvereniging" .
            ?contact <http://schema.org/email> "info@welzijnsvereniging.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683473579" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3292350100" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://zorgbedrijf-sakura.lokeren.be/" .
            ?contact <http://schema.org/email> "info@zorgbedrijfsakura.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684613726" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3233755410" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://zorgpuntwaasland.be/" .
            ?contact <http://schema.org/email> "info@zpw.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696715960" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3289325050" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zol.be/" .
            ?contact <http://schema.org/email> "info@zol.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0256543917" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3289573500" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zoggenk.be/nl" .
            ?contact <http://schema.org/email> "info@zoggenk.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505849852" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3225680990" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.welzijnskoepelwb.be/" .
            ?contact <http://schema.org/email> "vraag@welzijnskoepelwb.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0467270576" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237102560" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.sleutelzorgtemse.be/" .
            ?contact <http://schema.org/email> "info@sleutelzorgtemse.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0736364909" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3234322900" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgstekene.be/" .
            ?contact <http://schema.org/email> "info@zorgstekene.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689674948" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251336677" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.izegem.be/zorg" .
            ?contact <http://schema.org/email> "info@zorgizegem.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683771509" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237786240" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://schuldbemiddelingwaasland.be/" .
            ?contact <http://schema.org/email> "info@schuldbemiddelingwaasland.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862943474" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3237606060" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://vitaz.be/" .
            ?contact <http://schema.org/email> "info@vitaz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262562568" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zol.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0249211806" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3216248011" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zorgleuven.be/" .
            ?contact <http://schema.org/email> "info@zorgleuven.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0663810590" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250530080" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.hetdak.org/" .
            ?contact <http://schema.org/email> "dak@knokke-heist.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329989" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3251321622" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.woondienst.be/" .
            ?contact <http://schema.org/email> "info@woondienst.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0466193777" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250327190" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.onshuisbrugge.be/" .
            ?contact <http://schema.org/email> "info@onshuisbrugge.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878405769" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.svkbredeneoostende.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0479985593" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3259342273" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.woonpuntinfo.be/" .
            ?contact <http://schema.org/email> "loket@woonpuntinfo.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0873440458" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3250530930" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.knokke-heist.be/openingsuren-en-contactinfo/de-woonwinkel" .
            ?contact <http://schema.org/email> "woonwinkel@knokke-heist.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865506155" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3253764111" .
            
            ?contact <http://schema.org/email> "info@asz.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0263545337" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3255336111" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.azoudenaarde.be/" .
            ?contact <http://schema.org/email> "info@azoudenaarde.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0465810133" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215246330" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.zilverenzwaan.be/" .
            
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0781430812" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3214508120" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.grobbendonk.be/thema/detail/3003/woonzorgcentrum-de-wijngaard" .
            ?contact <http://schema.org/email> "info.wzc@grobbendonk.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0786960406" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
      

        INSERT {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?contact <http://schema.org/telephone> "tel:+3215229390" .
            ?contact <http://xmlns.com/foaf/0.1/page> "https://www.hulshout.be/nl/welzijn/ouderen/woonzorgcentrum-ter-nethe" .
            ?contact <http://schema.org/email> "wzcternethe@hulshout.be" .
          }
        }
        WHERE {
          GRAPH <http://mu.semte.ch/graphs/administrative-unit> {
            ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
              <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite .
            ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
              <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0780658572" .

            ?primarySite <http://www.w3.org/ns/org#siteAddress> ?contact .

            ?contact <http://schema.org/contactType> "Primary" .
          }
        }
