
      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "110";
            
            <http://www.w3.org/ns/locn#postCode> "2650";
            <http://www.w3.org/ns/locn#adminUnitL2> "Edegem";
            <http://www.w3.org/ns/locn#thoroughfare> "Oude-Godstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Edegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Oude-Godstraat 110, 2650 Edegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0685516024" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "35";
            
            <http://www.w3.org/ns/locn#postCode> "2018";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Ballaarstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ballaarstraat 35, 2018 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0809699184" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3920";
            <http://www.w3.org/ns/locn#adminUnitL2> "Lommel";
            <http://www.w3.org/ns/locn#thoroughfare> "Kapittelhof";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lommel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kapittelhof 1, 3920 Lommel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689553994" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "8940";
            <http://www.w3.org/ns/locn#adminUnitL2> "Wervik";
            <http://www.w3.org/ns/locn#thoroughfare> "Steenakker";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Wervik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Steenakker 30, 8940 Wervik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0686537789" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "15";
            
            <http://www.w3.org/ns/locn#postCode> "2820";
            <http://www.w3.org/ns/locn#adminUnitL2> "Bonheiden";
            <http://www.w3.org/ns/locn#thoroughfare> "Baxbos";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Bonheiden";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Baxbos 15, 2820 Bonheiden, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0875376696" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "70";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus 3";
            <http://www.w3.org/ns/locn#postCode> "3910";
            <http://www.w3.org/ns/locn#adminUnitL2> "Pelt";
            <http://www.w3.org/ns/locn#thoroughfare> "Hoekstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Pelt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hoekstraat 70 - Bus 3, 3910 Pelt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267393663" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "25";
            
            <http://www.w3.org/ns/locn#postCode> "2900";
            <http://www.w3.org/ns/locn#adminUnitL2> "Schoten";
            <http://www.w3.org/ns/locn#thoroughfare> "Verbertstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Schoten";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Verbertstraat 25, 2900 Schoten, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0694597697" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "17";
            
            <http://www.w3.org/ns/locn#postCode> "8700";
            <http://www.w3.org/ns/locn#adminUnitL2> "Tielt";
            <http://www.w3.org/ns/locn#thoroughfare> "Deken Darraslaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Tielt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Deken Darraslaan 17, 8700 Tielt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0711824305" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "5";
            
            <http://www.w3.org/ns/locn#postCode> "8530";
            <http://www.w3.org/ns/locn#adminUnitL2> "Harelbeke";
            <http://www.w3.org/ns/locn#thoroughfare> "Kollegeplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Harelbeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kollegeplein 5, 8530 Harelbeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684891363" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "12";
            
            <http://www.w3.org/ns/locn#postCode> "3800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Truiden";
            <http://www.w3.org/ns/locn#thoroughfare> "Clement Cartuyvelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Truiden";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Clement Cartuyvelstraat 12, 3800 Sint-Truiden, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0687742074" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "75";
            
            <http://www.w3.org/ns/locn#postCode> "1745";
            <http://www.w3.org/ns/locn#adminUnitL2> "Opwijk";
            <http://www.w3.org/ns/locn#thoroughfare> "Kloosterstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Opwijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kloosterstraat 75, 1745 Opwijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684493762" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "3530";
            <http://www.w3.org/ns/locn#adminUnitL2> "Houthalen-Helchteren";
            <http://www.w3.org/ns/locn#thoroughfare> "Pastorijstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Houthalen-Helchteren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Pastorijstraat 30, 3530 Houthalen-Helchteren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0688812935" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "8500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Kortrijk";
            <http://www.w3.org/ns/locn#thoroughfare> "President Kennedypark";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortrijk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "President Kennedypark 10, 8500 Kortrijk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0630835639" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "91";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus 1";
            <http://www.w3.org/ns/locn#postCode> "9900";
            <http://www.w3.org/ns/locn#adminUnitL2> "Eeklo";
            <http://www.w3.org/ns/locn#thoroughfare> "Oostveldstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Eeklo";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Oostveldstraat 91 - Bus 1, 9900 Eeklo, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871009916" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "28";
            
            <http://www.w3.org/ns/locn#postCode> "2860";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Katelijne-Waver";
            <http://www.w3.org/ns/locn#thoroughfare> "Wilsonstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Katelijne-Waver";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Wilsonstraat 28, 2860 Sint-Katelijne-Waver, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0680439360" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "100";
            
            <http://www.w3.org/ns/locn#postCode> "9820";
            <http://www.w3.org/ns/locn#adminUnitL2> "Merelbeke";
            <http://www.w3.org/ns/locn#thoroughfare> "Salisburylaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Merelbeke";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Salisburylaan 100, 9820 Merelbeke, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0698817989" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "72";
            
            <http://www.w3.org/ns/locn#postCode> "1800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Vilvoorde";
            <http://www.w3.org/ns/locn#thoroughfare> "Harensesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Vilvoorde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Harensesteenweg 72, 1800 Vilvoorde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0697787118" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "80";
            
            <http://www.w3.org/ns/locn#postCode> "9300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Aalst";
            <http://www.w3.org/ns/locn#thoroughfare> "Merestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalst";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Merestraat 80, 9300 Aalst, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0729523736" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "9160";
            <http://www.w3.org/ns/locn#adminUnitL2> "Lokeren";
            <http://www.w3.org/ns/locn#thoroughfare> "Lepelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lokeren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lepelstraat 2, 9160 Lokeren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871206587" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "51";
            
            <http://www.w3.org/ns/locn#postCode> "3700";
            <http://www.w3.org/ns/locn#adminUnitL2> "Tongeren";
            <http://www.w3.org/ns/locn#thoroughfare> "Hazelereik";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Tongeren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Hazelereik 51, 3700 Tongeren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0242469910" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 10, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0266559859" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "84";
            
            <http://www.w3.org/ns/locn#postCode> "8400";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oostende";
            <http://www.w3.org/ns/locn#thoroughfare> "Kaïrostraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oostende";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kaïrostraat 84, 8400 Oostende, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0473908049" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "9810";
            <http://www.w3.org/ns/locn#adminUnitL2> "Nazareth";
            <http://www.w3.org/ns/locn#thoroughfare> "Zwanestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Nazareth";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Zwanestraat 30, 9810 Nazareth, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0885714720" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "43";
            
            <http://www.w3.org/ns/locn#postCode> "9940";
            <http://www.w3.org/ns/locn#adminUnitL2> "Evergem";
            <http://www.w3.org/ns/locn#thoroughfare> "Sleidinge-dorp";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Evergem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Sleidinge-dorp 43, 9940 Evergem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0666615870" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "12";
            
            <http://www.w3.org/ns/locn#postCode> "8900";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ieper";
            <http://www.w3.org/ns/locn#thoroughfare> "Briekestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ieper";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Briekestraat 12, 8900 Ieper, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926319" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "8800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Roeselare";
            <http://www.w3.org/ns/locn#thoroughfare> "Gasthuisstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Roeselare";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Gasthuisstraat 10, 8800 Roeselare, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0537951706" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "5";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Gent";
            <http://www.w3.org/ns/locn#thoroughfare> "Watersportlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Watersportlaan 5, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262926616" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0682844465" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "503";
            
            <http://www.w3.org/ns/locn#postCode> "2390";
            <http://www.w3.org/ns/locn#adminUnitL2> "Malle";
            <http://www.w3.org/ns/locn#thoroughfare> "Antwerpsesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Malle";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Antwerpsesteenweg 503, 2390 Malle, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0445508132" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "18";
            
            <http://www.w3.org/ns/locn#postCode> "2300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Turnhout";
            <http://www.w3.org/ns/locn#thoroughfare> "Albert Van Dyckstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Turnhout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Albert Van Dyckstraat 18, 2300 Turnhout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0665553622" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "86";
            
            <http://www.w3.org/ns/locn#postCode> "9000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Gent";
            <http://www.w3.org/ns/locn#thoroughfare> "Onderbergen";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Gent";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Onderbergen 86, 9000 Gent, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0643926085" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "2440";
            <http://www.w3.org/ns/locn#adminUnitL2> "Geel";
            <http://www.w3.org/ns/locn#thoroughfare> "J.B.-Stessensstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Geel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "J.B.-Stessensstraat 2, 2440 Geel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0844179716" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Professor Dr. J. Sebrechtsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Professor Dr. J. Sebrechtsstraat 2, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0871928743" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0807042275" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "200";
            
            <http://www.w3.org/ns/locn#postCode> "2300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Turnhout";
            <http://www.w3.org/ns/locn#thoroughfare> "Campus Blairon";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Turnhout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Campus Blairon 200, 2300 Turnhout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0222947570" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0894999895" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329296" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0831970978" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267404056" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "4";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Ruddershove";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Ruddershove 4, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0860256673" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "29A";
            
            <http://www.w3.org/ns/locn#postCode> "9290";
            <http://www.w3.org/ns/locn#adminUnitL2> "Berlare";
            <http://www.w3.org/ns/locn#thoroughfare> "Baron Tibbautstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Berlare";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Baron Tibbautstraat 29A, 9290 Berlare, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0677764437" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "8900";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ieper";
            <http://www.w3.org/ns/locn#thoroughfare> "Poperingseweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ieper";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Poperingseweg 30, 8900 Ieper, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0233210764" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "11";
            
            <http://www.w3.org/ns/locn#postCode> "3500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Hasselt";
            <http://www.w3.org/ns/locn#thoroughfare> "Stadsomvaart";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hasselt";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stadsomvaart 11, 3500 Hasselt, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267302405" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "27";
            
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Mechelen";
            <http://www.w3.org/ns/locn#thoroughfare> "Lange Schipstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lange Schipstraat 27, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0827396340" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "51";
            
            <http://www.w3.org/ns/locn#postCode> "2000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Antwerpen";
            <http://www.w3.org/ns/locn#thoroughfare> "Falconrui";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Antwerpen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Falconrui 51, 2000 Antwerpen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0458878195" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "19";
            
            <http://www.w3.org/ns/locn#postCode> "2430";
            <http://www.w3.org/ns/locn#adminUnitL2> "Laakdal";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Laakdal";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 19, 2430 Laakdal, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886198829" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "27";
            
            <http://www.w3.org/ns/locn#postCode> "2800";
            <http://www.w3.org/ns/locn#adminUnitL2> "Mechelen";
            <http://www.w3.org/ns/locn#thoroughfare> "Lange Schipstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Mechelen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lange Schipstraat 27, 2800 Mechelen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267313291" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "75";
            
            <http://www.w3.org/ns/locn#postCode> "2930";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brasschaat";
            <http://www.w3.org/ns/locn#thoroughfare> "Prins Kavellei";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brasschaat";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Prins Kavellei 75, 2930 Brasschaat, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0647949706" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "44";
            
            <http://www.w3.org/ns/locn#postCode> "2870";
            <http://www.w3.org/ns/locn#adminUnitL2> "Puurs-Sint-Amands";
            <http://www.w3.org/ns/locn#thoroughfare> "Palingstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Puurs-Sint-Amands";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Palingstraat 44, 2870 Puurs-Sint-Amands, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0664681216" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "62";
            
            <http://www.w3.org/ns/locn#postCode> "9600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ronse";
            <http://www.w3.org/ns/locn#thoroughfare> "Oscar Delghuststraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ronse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Oscar Delghuststraat 62, 9600 Ronse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0480589567" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "50";
            
            <http://www.w3.org/ns/locn#postCode> "9660";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brakel";
            <http://www.w3.org/ns/locn#thoroughfare> "Kasteelstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brakel";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kasteelstraat 50, 9660 Brakel, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0886485770" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "99";
            
            <http://www.w3.org/ns/locn#postCode> "9100";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Niklaas";
            <http://www.w3.org/ns/locn#thoroughfare> "Abingdonstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Niklaas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Abingdonstraat 99, 9100 Sint-Niklaas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0267314875" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "9170";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Gillis-Waas";
            <http://www.w3.org/ns/locn#thoroughfare> "Zwanenhoekstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Gillis-Waas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Zwanenhoekstraat 3, 9170 Sint-Gillis-Waas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683473579" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "9160";
            <http://www.w3.org/ns/locn#adminUnitL2> "Lokeren";
            <http://www.w3.org/ns/locn#thoroughfare> "Polderstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Lokeren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Polderstraat 2, 9160 Lokeren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0684613726" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "92";
            
            <http://www.w3.org/ns/locn#postCode> "9120";
            <http://www.w3.org/ns/locn#adminUnitL2> "Beveren";
            <http://www.w3.org/ns/locn#thoroughfare> "Oude Zandstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Beveren";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Oude Zandstraat 92, 9120 Beveren, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0696715960" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6";
            
            <http://www.w3.org/ns/locn#postCode> "3600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Genk";
            <http://www.w3.org/ns/locn#thoroughfare> "Schiepse Bos";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Genk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Schiepse Bos 6, 3600 Genk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0256543917" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "15";
            
            <http://www.w3.org/ns/locn#postCode> "3600";
            <http://www.w3.org/ns/locn#adminUnitL2> "Genk";
            <http://www.w3.org/ns/locn#thoroughfare> "Welzijnscampus";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Genk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Welzijnscampus 15, 3600 Genk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0505849852" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "8";
            
            <http://www.w3.org/ns/locn#postCode> "1742";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ternat";
            <http://www.w3.org/ns/locn#thoroughfare> "Kapelleveld";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ternat";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kapelleveld 8, 1742 Ternat, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0467270576" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "8";
            
            <http://www.w3.org/ns/locn#postCode> "9140";
            <http://www.w3.org/ns/locn#adminUnitL2> "Temse";
            <http://www.w3.org/ns/locn#thoroughfare> "Clement D'hooghelaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Temse";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Clement D'hooghelaan 8, 9140 Temse, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0736364909" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "14A";
            
            <http://www.w3.org/ns/locn#postCode> "9190";
            <http://www.w3.org/ns/locn#adminUnitL2> "Stekene";
            <http://www.w3.org/ns/locn#thoroughfare> "Kerkstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Stekene";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kerkstraat 14A, 9190 Stekene, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0689674948" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "8870";
            <http://www.w3.org/ns/locn#adminUnitL2> "Izegem";
            <http://www.w3.org/ns/locn#thoroughfare> "Kokelarestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Izegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kokelarestraat 2, 8870 Izegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0683771509" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "99";
            
            <http://www.w3.org/ns/locn#postCode> "9100";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Niklaas";
            <http://www.w3.org/ns/locn#thoroughfare> "Abingdonstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Niklaas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Abingdonstraat 99, 9100 Sint-Niklaas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0862943474" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "5";
            
            <http://www.w3.org/ns/locn#postCode> "9100";
            <http://www.w3.org/ns/locn#adminUnitL2> "Sint-Niklaas";
            <http://www.w3.org/ns/locn#thoroughfare> "Lodewijk De Meesterstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Sint-Niklaas";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Lodewijk De Meesterstraat 5, 9100 Sint-Niklaas, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0262562568" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "3680";
            <http://www.w3.org/ns/locn#adminUnitL2> "Maaseik";
            <http://www.w3.org/ns/locn#thoroughfare> "Markt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Maaseik";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Markt 1, 3680 Maaseik, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0249211806" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "47";
            
            <http://www.w3.org/ns/locn#postCode> "3000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Leuven";
            <http://www.w3.org/ns/locn#thoroughfare> "Andreas Vesaliusstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Leuven";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Andreas Vesaliusstraat 47, 3000 Leuven, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0663810590" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "31";
            
            <http://www.w3.org/ns/locn#postCode> "8301";
            <http://www.w3.org/ns/locn#adminUnitL2> "Knokke-Heist";
            <http://www.w3.org/ns/locn#thoroughfare> "Noordhinder";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Knokke-Heist";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Noordhinder 31, 8301 Knokke-Heist, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0863329989" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "10";
            
            <http://www.w3.org/ns/locn#postCode> "8870";
            <http://www.w3.org/ns/locn#adminUnitL2> "Izegem";
            <http://www.w3.org/ns/locn#thoroughfare> "Korenmarkt";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Izegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Korenmarkt 10, 8870 Izegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0466193777" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "6";
            
            <http://www.w3.org/ns/locn#postCode> "8000";
            <http://www.w3.org/ns/locn#adminUnitL2> "Brugge";
            <http://www.w3.org/ns/locn#thoroughfare> "Sint-Annarei";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Brugge";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Sint-Annarei 6, 8000 Brugge, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0878405769" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "401A";
            
            <http://www.w3.org/ns/locn#postCode> "8400";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oostende";
            <http://www.w3.org/ns/locn#thoroughfare> "Stuiverstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oostende";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stuiverstraat 401A, 8400 Oostende, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0479985593" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            
            <http://www.w3.org/ns/locn#postCode> "8480";
            <http://www.w3.org/ns/locn#adminUnitL2> "Ichtegem";
            <http://www.w3.org/ns/locn#thoroughfare> "Stationstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Ichtegem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stationstraat 1, 8480 Ichtegem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0873440458" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "1";
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.busnummer> "Bus 3";
            <http://www.w3.org/ns/locn#postCode> "8301";
            <http://www.w3.org/ns/locn#adminUnitL2> "Knokke-Heist";
            <http://www.w3.org/ns/locn#thoroughfare> "Kraaiennestplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Knokke-Heist";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kraaiennestplein 1 - Bus 3, 8301 Knokke-Heist, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0865506155" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "80";
            
            <http://www.w3.org/ns/locn#postCode> "9300";
            <http://www.w3.org/ns/locn#adminUnitL2> "Aalst";
            <http://www.w3.org/ns/locn#thoroughfare> "Merestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Aalst";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Merestraat 80, 9300 Aalst, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0263545337" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "9700";
            <http://www.w3.org/ns/locn#adminUnitL2> "Oudenaarde";
            <http://www.w3.org/ns/locn#thoroughfare> "Minderbroedersstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Oudenaarde";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Minderbroedersstraat 3, 9700 Oudenaarde, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0465810133" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "2";
            
            <http://www.w3.org/ns/locn#postCode> "2220";
            <http://www.w3.org/ns/locn#adminUnitL2> "Heist-Op-Den-Berg";
            <http://www.w3.org/ns/locn#thoroughfare> "Stationsstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Heist-op-den-Berg";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Stationsstraat 2, 2220 Heist-op-den-Berg, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0781430812" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "55";
            
            <http://www.w3.org/ns/locn#postCode> "2280";
            <http://www.w3.org/ns/locn#adminUnitL2> "Grobbendonk";
            <http://www.w3.org/ns/locn#thoroughfare> "Schransstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Grobbendonk";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Schransstraat 55, 2280 Grobbendonk, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0786960406" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "264";
            
            <http://www.w3.org/ns/locn#postCode> "2235";
            <http://www.w3.org/ns/locn#adminUnitL2> "Hulshout";
            <http://www.w3.org/ns/locn#thoroughfare> "Grote Baan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Hulshout";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Grote Baan 264, 2235 Hulshout, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0780658572" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "1500";
            <http://www.w3.org/ns/locn#adminUnitL2> "Halle";
            <http://www.w3.org/ns/locn#thoroughfare> "Auguste Demaeghtlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Halle";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Auguste Demaeghtlaan 30, 1500 Halle, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0264998753" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "50";
            
            <http://www.w3.org/ns/locn#postCode> "2870";
            <http://www.w3.org/ns/locn#adminUnitL2> "Puurs-Sint-Amands";
            <http://www.w3.org/ns/locn#thoroughfare> "Palingstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Puurs-Sint-Amands";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Palingstraat 50, 2870 Puurs-Sint-Amands, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0866242662" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "30";
            
            <http://www.w3.org/ns/locn#postCode> "3070";
            <http://www.w3.org/ns/locn#adminUnitL2> "Kortenberg";
            <http://www.w3.org/ns/locn#thoroughfare> "Dr. V. De Walsplein";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Kortenberg";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Dr. V. De Walsplein 30, 3070 Kortenberg, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0889412695" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "19";
            
            <http://www.w3.org/ns/locn#postCode> "9070";
            <http://www.w3.org/ns/locn#adminUnitL2> "Destelbergen";
            <http://www.w3.org/ns/locn#thoroughfare> "Kouterlaan";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Destelbergen";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kouterlaan 19, 9070 Destelbergen, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0874267037" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "120";
            
            <http://www.w3.org/ns/locn#postCode> "2890";
            <http://www.w3.org/ns/locn#adminUnitL2> "Puurs-Sint-Amands";
            <http://www.w3.org/ns/locn#thoroughfare> "Kuitegemstraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Puurs-Sint-Amands";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Kuitegemstraat 120, 2890 Puurs-Sint-Amands, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0836906793" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "3";
            
            <http://www.w3.org/ns/locn#postCode> "1790";
            <http://www.w3.org/ns/locn#adminUnitL2> "Affligem";
            <http://www.w3.org/ns/locn#thoroughfare> "Bellestraat";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Affligem";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Bellestraat 3, 1790 Affligem, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0834358069" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    

      INSERT {
        GRAPH ?g {
          ?addressUri 
            <https://data.vlaanderen.be/ns/adres#Adresvoorstelling.huisnummer> "27";
            
            <http://www.w3.org/ns/locn#postCode> "2830";
            <http://www.w3.org/ns/locn#adminUnitL2> "Willebroek";
            <http://www.w3.org/ns/locn#thoroughfare> "Tisseltsesteenweg";
            <https://data.vlaanderen.be/ns/adres#gemeentenaam> "Willebroek";
            <https://data.vlaanderen.be/ns/adres#land> "België";
            <http://www.w3.org/ns/locn#fullAddress> "Tisseltsesteenweg 27, 2830 Willebroek, België".
        }
      }
      WHERE {
        GRAPH ?g {
          ?adminUnit <http://www.w3.org/ns/adms#identifier> ?id ;
            <http://www.w3.org/ns/org#hasPrimarySite> ?site .

          ?id <http://www.w3.org/2004/02/skos/core#notation> "KBO nummer" ;
            <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator>/<https://data.vlaanderen.be/ns/generiek#lokaleIdentificator> "0459993992" .

          ?site <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?boundAddress .

          BIND( ?boundAddress AS ?addressUri )
        }
      }
    