INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/7fec2e93-b585-43dc-88d3-04de5e055215>
      rdf:type	<http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis> ;
      <http://mu.semte.ch/vocabularies/core/uuid>	"7fec2e93-b585-43dc-88d3-04de5e055215" ;
      skos:prefLabel	"Wijziging werkingsgebied" ;
      skos:inScheme	<http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> , <http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b> ;
      skos:topConceptOf	<http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> .
  }
}
