INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/organisatie/TypeVestiging> .
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://www.w3.org/2004/02/skos/core#prefLabel> "Hoofdcommissariaat" .
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://mu.semte.ch/vocabularies/core/uuid> "0ed15289-1f3d-4172-8c46-0506de5aa2a3" .
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/f8319ccf40fc2a1697edc5cf7e03018f> .
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/f8319ccf40fc2a1697edc5cf7e03018f> .
    <http://lblod.data.gift/concepts/0ed15289-1f3d-4172-8c46-0506de5aa2a3> <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b> .    
  }
}
