PREFIX org: <http://www.w3.org/ns/org#>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>

DELETE {
  GRAPH ?g {
    ?role ere:functie <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2> . # Priester
  }
} INSERT {
  GRAPH ?g {
    ?role ere:functie <http://lblod.data.gift/concepts/04d3b5325f2ebc5eaf96849519af4254> . # Rector
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/rollenBedienaar/6332B4D3036B579F0A26FF1D> org:holds ?role .
    ?role ere:functie <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2> .
  }
}
