PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/6130DFFB375CFC000A0000A1> generiek:lokaleIdentificator ?kbo1 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/61DFFBF9BA00DD4BE2501BC2> generiek:lokaleIdentificator ?kbo2 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/5d50bc3fdf941de8b56c8def78407436> generiek:lokaleIdentificator ?kbo3 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/52c1f29b51e8a92972c57f2c7b229b5a> generiek:lokaleIdentificator ?kbo4 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/406fec8a5923e85511ca92c39edfd6ec> generiek:lokaleIdentificator ?kbo5 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/fa7c56c097294e0c31aca1ac99fd0b6a> generiek:lokaleIdentificator ?kbo6 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b48f6b751fd53f9ef0e249b0234480ff> generiek:lokaleIdentificator ?kbo7 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b4af7f119ea6a0b012e01ef8494c5f72> generiek:lokaleIdentificator ?kbo8 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/40022a348133be5a8da995c6770ced56> generiek:lokaleIdentificator ?kbo9 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/d5c5db3a99201463e6f18daba19efb52> generiek:lokaleIdentificator ?kbo10 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/79cd43bc157fcf9d4440edf4c40ebd2b> generiek:lokaleIdentificator ?kbo11 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/2dbeed0bd11f472a304580748b1c30a9> generiek:lokaleIdentificator ?kbo12 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/bf7c674a89e693d52bd1152e0026b550> generiek:lokaleIdentificator ?kbo13 .
  }
} INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/6130DFFB375CFC000A0000A1> generiek:lokaleIdentificator "0777683642" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/61DFFBF9BA00DD4BE2501BC2> generiek:lokaleIdentificator "0780386972" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/5d50bc3fdf941de8b56c8def78407436> generiek:lokaleIdentificator "0408140861" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/52c1f29b51e8a92972c57f2c7b229b5a> generiek:lokaleIdentificator "0408472839" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/406fec8a5923e85511ca92c39edfd6ec> generiek:lokaleIdentificator "0409677223" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/fa7c56c097294e0c31aca1ac99fd0b6a> generiek:lokaleIdentificator "0409771253" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b48f6b751fd53f9ef0e249b0234480ff> generiek:lokaleIdentificator "0410195380" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b4af7f119ea6a0b012e01ef8494c5f72> generiek:lokaleIdentificator "0412914944" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/40022a348133be5a8da995c6770ced56> generiek:lokaleIdentificator "0413234648" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/d5c5db3a99201463e6f18daba19efb52> generiek:lokaleIdentificator "0464533790" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/79cd43bc157fcf9d4440edf4c40ebd2b> generiek:lokaleIdentificator "0687815914" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/2dbeed0bd11f472a304580748b1c30a9> generiek:lokaleIdentificator "0864330673" .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/bf7c674a89e693d52bd1152e0026b550> generiek:lokaleIdentificator "0898987189" .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/6130DFFB375CFC000A0000A1> generiek:lokaleIdentificator ?kbo1 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/61DFFBF9BA00DD4BE2501BC2> generiek:lokaleIdentificator ?kbo2 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/5d50bc3fdf941de8b56c8def78407436> generiek:lokaleIdentificator ?kbo3 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/52c1f29b51e8a92972c57f2c7b229b5a> generiek:lokaleIdentificator ?kbo4 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/406fec8a5923e85511ca92c39edfd6ec> generiek:lokaleIdentificator ?kbo5 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/fa7c56c097294e0c31aca1ac99fd0b6a> generiek:lokaleIdentificator ?kbo6 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b48f6b751fd53f9ef0e249b0234480ff> generiek:lokaleIdentificator ?kbo7 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/b4af7f119ea6a0b012e01ef8494c5f72> generiek:lokaleIdentificator ?kbo8 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/40022a348133be5a8da995c6770ced56> generiek:lokaleIdentificator ?kbo9 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/d5c5db3a99201463e6f18daba19efb52> generiek:lokaleIdentificator ?kbo10 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/79cd43bc157fcf9d4440edf4c40ebd2b> generiek:lokaleIdentificator ?kbo11 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/2dbeed0bd11f472a304580748b1c30a9> generiek:lokaleIdentificator ?kbo12 .
    <http://data.lblod.info/id/gestructureerdeIdentificatoren/bf7c674a89e693d52bd1152e0026b550> generiek:lokaleIdentificator ?kbo13 .
  }
}
