# OP-1929 : Delete duplicated members from worship service

# Delete wrong mandatarissen
DELETE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> { ?s ?p ?o . }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> { 
    VALUES ?s {
        <http://data.lblod.info/id/mandatarissen/6380A02F4B5FEAF28DEDE975>
        <http://data.lblod.info/id/mandatarissen/6380BBB04B5FEAF28DEDE97E>
        <http://data.lblod.info/id/mandatarissen/63809FC24B5FEAF28DEDE974>
        <http://data.lblod.info/id/mandatarissen/63809F414B5FEAF28DEDE972>
        <http://data.lblod.info/id/mandatarissen/6380A0F04B5FEAF28DEDE979>
        <http://data.lblod.info/id/mandatarissen/6380D0854B5FEAF28DEDE97F>
    }
    ?s ?p ?o. 
  }
}
;
# Delete duplicate person
DELETE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
      <http://data.lblod.info/id/personen/6380A0934B5FEAF28DEDE976> ?p ?o .
  }
} 
WHERE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
      <http://data.lblod.info/id/personen/6380A0934B5FEAF28DEDE976> ?p ?o .
  }
}
;
# Delete duplicate person sensitive data
DELETE {
  GRAPH <http://mu.semte.ch/graphs/privacy-centric-graph> {
      <http://data.lblod.info/id/personen/6380A0934B5FEAF28DEDE976> ?p ?o .
  }
} 
WHERE {
  GRAPH <http://mu.semte.ch/graphs/privacy-centric-graph> {
      <http://data.lblod.info/id/personen/6380A0934B5FEAF28DEDE976> ?p ?o .
  }
}


