INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://lblod.data.gift/concepts/e4c3d1ef-a34d-43b0-a18c-f4e60e2c8af3>
      a <http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "e4c3d1ef-a34d-43b0-a18c-f4e60e2c8af3" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Stadstitel" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b> ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> .
  }
}
