PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>

# Orthodox
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/84bcd6896f575bae4857ff8d2764bed8> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/59837b12c14f215a4efadae950be0072> # Onderpastoor
      <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2> # Bedienaar
      <http://lblod.data.gift/concepts/04d3b5325f2ebc5eaf96849519af4254> # Pastoor-deken
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}

;

# Islamitisch
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/9d8bd472a00bf0a5c7b7186606365a52> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/e357bc8f4cc3a694fde2239748768a22> # Eerste Imam in rang
      <http://lblod.data.gift/concepts/c4a3fd586211b17b06f574885e23f355> # Tweede Imam in rang
      <http://lblod.data.gift/concepts/5ebb798bd59c3b48c25116032caa02b7> # Derde Imam in rang
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}

;

# Rooms-Katholiek
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/b13d1d623626bc1ee75c7d20bc60e3c0> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/ea58c73d9b4fc8a24a4b3eaa73a33995> # Kapelaan
      <http://lblod.data.gift/concepts/689b3123e29cff78e310df38a774b9bb> # Kerkbedienaar
      <http://lblod.data.gift/concepts/59837b12c14f215a4efadae950be0072> # Onderpastoor
      <http://lblod.data.gift/concepts/84b3a2321d1b69b6de782bb04e1a6862> # Parochieassistent
      <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d> # Pastoor
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}

;

# Israëlitisch
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/1a1abeafc973d27cebcb2d7a15b2d823> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/17e7177aba2596705ad3c209019c729a> # Officiërend bedienaar
      <http://lblod.data.gift/concepts/27b3d149dd2a726effe749572177682e> # Rabbijn
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}

;

# Anglicaans
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/99536dd6eb0d2ef38a89efafb17e7389> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/67548f1fe5bf52e5a7ad33dcce47472d> # Kapelaan van de andere kerken
      <http://lblod.data.gift/concepts/fa4191f9d7050fe62ec3fc0e16541711> # Kapelaan van de kerken te Antwerpen en te Elsene (Geünifieerde anglikaanse kerk)
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}

;

# Protestants
INSERT {
  GRAPH ?g {
    ?bestuurseenheid ere:wordtBediendDoor ?newMinisterPosition .

    ?newMinisterPosition a org:Post , ere:PositieBedienaar ;
      mu:uuid ?uuidNewMinisterPosition ;
      ere:functie ?functie .
  }
}
WHERE {
  GRAPH ?g {
    ?bestuurseenheid a ere:BestuurVanDeEredienst ;
      ere:typeEredienst <http://lblod.data.gift/concepts/e8cba1540b35a32e9cb45126c38c03c6> .

    VALUES ?functie {
      <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6> # Eerste predikant
      <http://lblod.data.gift/concepts/92aad8fc5cc7a13a7b0ddc7cc13c02aa> # Hulppredikant
      <http://lblod.data.gift/concepts/85543bba7601ca598212f0feb9bdb4c2> # Predikant bij het voorzitterschap van de Synode
      <http://lblod.data.gift/concepts/97083de35cd36b36a72185807e941c8a> # Tweede predikant bij het voorzitterschap van de Synode
      <http://lblod.data.gift/concepts/158b739bc1087d5246df2fa54acff29c> # Secretaris bij het voorzitterschap van de Synode
    }

    FILTER NOT EXISTS {
      ?bestuurseenheid ere:wordtBediendDoor ?ministerPosition .
      ?ministerPosition ere:functie ?functie .
    }

    BIND(MD5(CONCAT(?bestuurseenheid, ?functie)) as ?uuidNewMinisterPosition)
    BIND(IRI(CONCAT("http://data.lblod.info/id/positiesBedienaar/", ?uuidNewMinisterPosition)) AS ?newMinisterPosition)
  }
}
