INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://lblod.data.gift/concepts/fa80032794c841ecac73ff874f856db1>
      <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis> ;
    <http://mu.semte.ch/vocabularies/core/uuid> "fa80032794c841ecac73ff874f856db1" ;
    <http://www.w3.org/2004/02/skos/core#prefLabel> "Fusie" ;
    <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> ;
    <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b> ;
    <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> .
  }
}
