DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://lblod.data.gift/concepts/fa4191f9d7050fe62ec3fc0e16541711> <http://www.w3.org/2004/02/skos/core#prefLabel> "Kapelaan van de kerken te Antwerpen en te Elsene (Geünifieerde anglikaanse kerk)" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://lblod.data.gift/concepts/fa4191f9d7050fe62ec3fc0e16541711> <http://www.w3.org/2004/02/skos/core#prefLabel> "Kapelaan van de kerken te Antwerpen en te Elsene (Geünifieerde anglicaanse kerk)" .
  }
}