DELETE {
  GRAPH ?g {
    ?representatieveOrgaan <http://www.w3.org/ns/org#linkedTo> ?bestuur .
    ?bestuur ?pbestuur ?obestuur .
    ?primarySite ?pprimarySite ?oprimarySite .
    ?address ?paddress ?oaddress .
    ?identifier ?pidentifier ?oidentifier .
    ?structuredIdentifier ?pstructuredIdentifier ?ostructuredIdentifier .
  }
} WHERE {
  GRAPH ?g {
    VALUES ?bestuur {
      <http://data.lblod.info/id/besturenVanDeEredienst/578bf96f86056e2260dc21cee91aa519>
    }

    ?representatieveOrgaan <http://www.w3.org/ns/org#linkedTo> ?bestuur .

    ?bestuur <http://www.w3.org/ns/org#hasPrimarySite> ?primarySite ;
      <http://www.w3.org/ns/adms#identifier> ?identifier ;
      ?pbestuur ?obestuur .

    ?primarySite <https://data.vlaanderen.be/ns/organisatie#bestaatUit> ?address ;
      ?pprimarySite ?oprimarySite .

    ?address ?paddress ?oaddress .

    ?identifier <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredIdentifier ;
      ?pidentifier ?oidentifier .

    ?structuredIdentifier ?pstructuredIdentifier ?ostructuredIdentifier .
  }
}