DELETE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    ?identifier ?pidentifier ?oidentifier .
    ?structuredIdentifier ?pstructuredIdentifier ?ostructuredIdentifier .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    VALUES ?bestuur {
      <http://data.lblod.info/id/besturenVanDeEredienst/999b011fe6b90b3b546612c25db4b607> # OP-1980
      <http://data.lblod.info/id/besturenVanDeEredienst/da2184c3dca9eb7c4828a50c0e9f5af4> # OP-1978
      <http://data.lblod.info/id/besturenVanDeEredienst/a6b5c5db3a261ca024a42fe9489496a9> # OP-1979
      <http://data.lblod.info/id/besturenVanDeEredienst/260312c07d8e00358064a362dee3506f> # OP-1977
    }
   
    OPTIONAL { 
      ?bestuur <http://www.w3.org/ns/adms#identifier> ?identifier . 
      ?identifier ?pidentifier ?oidentifier .
    }
        
    OPTIONAL {
      ?identifier <https://data.vlaanderen.be/ns/generiek#gestructureerdeIdentificator> ?structuredIdentifier.
      ?structuredIdentifier ?pstructuredIdentifier ?ostructuredIdentifier .
    }
  }
}

# The associated call to trigger a reindex is :

# curl --location --request POST '172.20.0.15/update' \
# --header 'Content-Type: application/vnd.api+json' \
# --data-raw ' [
#   {
#     "deletes": [
#       {
#         "subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/999b011fe6b90b3b546612c25db4b607" },
#         "predicate": { "type": "uri", "value": "http://mu.semte.ch/vocabularies/core/uuid" },
#         "object": { "type": "string", "value": "999b011fe6b90b3b546612c25db4b607" }
#       },
#       {
#         "subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/da2184c3dca9eb7c4828a50c0e9f5af4" },
#         "predicate": { "type": "uri", "value": "http://mu.semte.ch/vocabularies/core/uuid" },
#         "object": { "type": "string", "value": "da2184c3dca9eb7c4828a50c0e9f5af4" }
#       },
#       {
#         "subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/a6b5c5db3a261ca024a42fe9489496a9" },
#         "predicate": { "type": "uri", "value": "http://mu.semte.ch/vocabularies/core/uuid" },
#         "object": { "type": "string", "value": "a6b5c5db3a261ca024a42fe9489496a9" }
#       },
#       {
#         "subject": { "type": "uri", "value": "http://data.lblod.info/id/besturenVanDeEredienst/260312c07d8e00358064a362dee3506f" },
#         "predicate": { "type": "uri", "value": "http://mu.semte.ch/vocabularies/core/uuid" },
#         "object": { "type": "string", "value": "260312c07d8e00358064a362dee3506f" }
#       }
#     ],
#     "inserts": []
#   }
# ]'