
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

DELETE {
    graph ?g {
      <http://data.lblod.info/id/positiesBedienaar/62A98293D7779543F777951B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1029375CFC000A0005E4> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/616436FD375CFC000A00077B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62EE1A0DD7779543F77796C8> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62F21194D7779543F77796CD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621E191A5747C883CA1D36D0> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62177EC55747C883CA1D347B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621C93CA5747C883CA1D35D6> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217A07A5747C883CA1D34CF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217822D5747C883CA1D3496> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620E28AE5747C883CA1D2E99> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62596CC78A3D153ADACC046A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62B17981D7779543F7779528> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621755E85747C883CA1D341C> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62179D345747C883CA1D34AB> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62173DDE5747C883CA1D33F7> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/61B747D63C1A230C43B451E5> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6231B914B72F9F4B33507F89> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217410D5747C883CA1D33FD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620E5BD35747C883CA1D2ECE> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621DDEBE5747C883CA1D3666> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621DDAA85747C883CA1D3646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62174F555747C883CA1D3411> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620B6CEE5747C883CA1D2DD1> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C2047375CFC000A000646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C14D4375CFC000A000608> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C365E375CFC000A00064F> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1DB3375CFC000A00063D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C3870375CFC000A00065A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C3F29375CFC000A00066D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1194375CFC000A0005ED> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62596B418A3D153ADACC0458> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1369375CFC000A0005FF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1BB5375CFC000A000634> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
    }
}
INSERT {
    graph ?g {
      <http://data.lblod.info/id/positiesBedienaar/62A98293D7779543F777951B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/fa4191f9d7050fe62ec3fc0e16541711>.
      <http://data.lblod.info/id/positiesBedienaar/615C1029375CFC000A0005E4> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/fa4191f9d7050fe62ec3fc0e16541711>.
      <http://data.lblod.info/id/positiesBedienaar/616436FD375CFC000A00077B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/e357bc8f4cc3a694fde2239748768a22>.
      <http://data.lblod.info/id/positiesBedienaar/62EE1A0DD7779543F77796C8> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/e357bc8f4cc3a694fde2239748768a22>.
      <http://data.lblod.info/id/positiesBedienaar/62F21194D7779543F77796CD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621E191A5747C883CA1D36D0> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62177EC55747C883CA1D347B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621C93CA5747C883CA1D35D6> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/6217A07A5747C883CA1D34CF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/6217822D5747C883CA1D3496> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/620E28AE5747C883CA1D2E99> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62596CC78A3D153ADACC046A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62B17981D7779543F7779528> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621755E85747C883CA1D341C> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62179D345747C883CA1D34AB> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62173DDE5747C883CA1D33F7> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/61B747D63C1A230C43B451E5> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/6231B914B72F9F4B33507F89> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/6217410D5747C883CA1D33FD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/620E5BD35747C883CA1D2ECE> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621DDEBE5747C883CA1D3666> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621DDAA85747C883CA1D3646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/62174F555747C883CA1D3411> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/620B6CEE5747C883CA1D2DD1> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/615C2047375CFC000A000646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C365E375CFC000A00064F> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C1DB3375CFC000A00063D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C3870375CFC000A00065A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C3F29375CFC000A00066D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C1194375CFC000A0005ED> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/62596B418A3D153ADACC0458> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C1369375CFC000A0005FF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.
      <http://data.lblod.info/id/positiesBedienaar/615C1BB5375CFC000A000634> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/83d50e9184ae4a628851370079d162f6>.


    }
}
WHERE {
    graph ?g {
      <http://data.lblod.info/id/positiesBedienaar/62A98293D7779543F777951B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1029375CFC000A0005E4> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/616436FD375CFC000A00077B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62EE1A0DD7779543F77796C8> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62F21194D7779543F77796CD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/5c7fefe1b921dfd4c550924bb7a9331d>.
      <http://data.lblod.info/id/positiesBedienaar/621E191A5747C883CA1D36D0> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62177EC55747C883CA1D347B> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621C93CA5747C883CA1D35D6> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217A07A5747C883CA1D34CF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217822D5747C883CA1D3496> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620E28AE5747C883CA1D2E99> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62596CC78A3D153ADACC046A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62B17981D7779543F7779528> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621755E85747C883CA1D341C> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62179D345747C883CA1D34AB> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62173DDE5747C883CA1D33F7> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/61B747D63C1A230C43B451E5> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6231B914B72F9F4B33507F89> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/6217410D5747C883CA1D33FD> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620E5BD35747C883CA1D2ECE> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621DDEBE5747C883CA1D3666> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/621DDAA85747C883CA1D3646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62174F555747C883CA1D3411> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/620B6CEE5747C883CA1D2DD1> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C2047375CFC000A000646> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C14D4375CFC000A000608> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C365E375CFC000A00064F> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1DB3375CFC000A00063D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C3870375CFC000A00065A> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C3F29375CFC000A00066D> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1194375CFC000A0005ED> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/62596B418A3D153ADACC0458> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1369375CFC000A0005FF> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
      <http://data.lblod.info/id/positiesBedienaar/615C1BB5375CFC000A000634> <http://data.lblod.info/vocabularies/erediensten/functie> <http://lblod.data.gift/concepts/efbf2ff50b5c4f693f129ac03319c4f2>.
    
    
    }
}
