PREFIX org: <http://www.w3.org/ns/org#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://data.lblod.info/id/veranderingsgebeurtenissen/620E5CF95747C883CA1D2ED5>
      org:originalOrganization <http://data.lblod.info/id/besturenVanDeEredienst/6180d2f3e76d711b9bb0ce5881c5b57d> .
  }
}
