DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018> skos:prefLabel "Voorzitter van het Vast Bureau" .
  }
}
