DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/centralebestuursorganen/d2b5a4e1a4e66c9e0319f4704c96bf4c>
      <http://www.w3.org/ns/org#hasPost> ?post .

    ?post ?ppost ?opost .

    ?role <http://www.w3.org/ns/org#holds> ?post ;
      <http://schema.org/contactPoint> ?contactPoint ;
      ?prole ?orole .

    ?contactPoint <http://www.w3.org/ns/locn#address> ?address ;
      ?pcontactPoint ?ocontactPoint .

    ?address ?paddress ?oaddress .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/centralebestuursorganen/d2b5a4e1a4e66c9e0319f4704c96bf4c>
      <http://www.w3.org/ns/org#hasPost> ?post .

    ?post ?ppost ?opost .

    ?role <http://www.w3.org/ns/org#holds> ?post ;
      ?prole ?orole .

    OPTIONAL {
      ?role <http://schema.org/contactPoint> ?contactPoint .

      ?contactPoint ?pcontactPoint ?ocontactPoint .

      OPTIONAL {
        ?contactPoint <http://www.w3.org/ns/locn#address> ?address .
        ?address ?paddress ?oaddress .
      }
    }
  }
}
