INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/a8b5509b-f86b-48f8-94d6-fe463a9b77e3>
      a <http://lblod.data.gift/vocabularies/organisatie/BestuursfunctieCode> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "a8b5509b-f86b-48f8-94d6-fe463a9b77e3" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Bestuurslid van het bestuur van de eredienst (Grote Helft)" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> ;
      <http://mu.semte.ch/vocabularies/ext/appliesTo> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/04f65457bf125b2dc59fd71917ac3d08> .

    <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/2962f0bd-2836-4758-9866-8ce8ea2c536f>
      a <http://lblod.data.gift/vocabularies/organisatie/BestuursfunctieCode> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "2962f0bd-2836-4758-9866-8ce8ea2c536f" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Bestuurslid van het bestuur van de eredienst (Kleine Helft)" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://data.vlaanderen.be/id/conceptscheme/BestuursfunctieCode> ;
      <http://mu.semte.ch/vocabularies/ext/appliesTo> <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/04f65457bf125b2dc59fd71917ac3d08> .
  }
}
