DELETE DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://data.lblod.info/id/representatieveOrganen/0ebb44c2ef14d86978ea85e74d128ad1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Oecumenisch Patriarchaat van Konstantinopel" .
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/organisatieportaal> {
    <http://data.lblod.info/id/representatieveOrganen/0ebb44c2ef14d86978ea85e74d128ad1> <http://www.w3.org/2004/02/skos/core#prefLabel> "Oecumenisch Patriarchaat van Constantinopel" .
  }
}