# We currently only have districts of Antwerpen in the app. We make them automatically sub orgs of
# the municipality of Antwerpen.

INSERT {
  GRAPH ?h {
    <http://data.lblod.info/id/bestuurseenheden/670db1d66c0de3b931962e1044033ccfa9d6e3023aa9828a5f252c3bc69bd32c>
      <http://www.w3.org/ns/org#hasSubOrganization> ?s .
  }
}
WHERE {
  GRAPH ?g {
    ?s <http://www.w3.org/ns/org#classification> <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000003> .
  }
  BIND(?g as ?h)
}
