INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/concepts/bde828e9-09da-4b5d-8d5e-f4915c80d2cf>
      a <http://lblod.data.gift/vocabularies/organisatie/Veranderingsgebeurtenis> ;
      <http://mu.semte.ch/vocabularies/core/uuid> "bde828e9-09da-4b5d-8d5e-f4915c80d2cf" ;
      <http://www.w3.org/2004/02/skos/core#prefLabel> "Wijziging bijkomende kwalificatie(s)" ;
      <http://www.w3.org/2004/02/skos/core#inScheme> <http://lblod.data.gift/concept-schemes/10caf4a4-1ff5-4c05-917e-56489910d68b> ,
                                                       <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> ;
      <http://www.w3.org/2004/02/skos/core#topConceptOf> <http://lblod.data.gift/concept-schemes/e1ff33ee76b5662ec8486f0e2abec384> .
  }
}
